// My advice view: role picker + advisory cards.
export default {
  en: {
    adviceTitle: 'My advice',
    adviceSub: 'Guidance tuned to your role, place and language. Decision support — never an official order.',
    pickRole: 'Who are you today?',
    pickRoleSub: 'The same sky, advice that fits your day.',
    role_general: 'General citizen',
    role_general_d: 'Daily life, health, commute',
    role_farmer: 'Farmer',
    role_farmer_d: 'Crops, spraying, irrigation',
    role_driver: 'Driver',
    role_driver_d: 'Roads, visibility, halts',
    role_fisherman: 'Fisherman',
    role_fisherman_d: 'Sea, wind, harbour signals',
    role_aviation: 'Aviation',
    role_aviation_d: 'Winds aloft, visibility',
    role_commuter: 'Commuter',
    role_commuter_d: 'Two-wheelers, buses, trains',
    role_office: 'Office worker',
    role_office_d: 'Work hours, travel windows',
    cardsTitle: "Today's cards",
    cardsSub: 'Built from current weather, the forecast and official alerts.',
    noCards: 'No cards right now — conditions look routine.',
    basis: 'Why this card',
    validFor: 'Good for',
    briefing: 'Your briefing',
    changeRole: 'Change role',
    roleSaved: 'Role saved',
  },
  hi: {
    adviceTitle: 'मेरी सलाह',
    adviceSub: 'आपकी भूमिका, जगह और भाषा के हिसाब से मार्गदर्शन। निर्णय में सहायता — कोई आधिकारिक आदेश नहीं।',
    pickRole: 'आज आप कौन हैं?',
    pickRoleSub: 'वही आसमान, आपके दिन के हिसाब से सलाह।',
    role_general: 'आम नागरिक',
    role_general_d: 'रोज़मर्रा, स्वास्थ्य, आवागमन',
    role_farmer: 'किसान',
    role_farmer_d: 'फ़सल, छिड़काव, सिंचाई',
    role_driver: 'ड्राइवर',
    role_driver_d: 'सड़कें, दृश्यता, ठहराव',
    role_fisherman: 'मछुआरा',
    role_fisherman_d: 'समुद्र, हवा, हार्बर संकेत',
    role_aviation: 'विमानन',
    role_aviation_d: 'ऊपरी हवाएँ, दृश्यता',
    role_commuter: 'यात्री',
    role_commuter_d: 'दोपहिया, बस, ट्रेन',
    role_office: 'कार्यालय कर्मी',
    role_office_d: 'काम के घंटे, यात्रा समय',
    cardsTitle: 'आज के कार्ड',
    cardsSub: 'मौजूदा मौसम, पूर्वानुमान और आधिकारिक अलर्ट से बने।',
    noCards: 'अभी कोई कार्ड नहीं — हालात सामान्य लग रहे हैं।',
    basis: 'यह कार्ड क्यों',
    validFor: 'इनके लिए सही',
    briefing: 'आपकी ब्रीफ़िंग',
    changeRole: 'भूमिका बदलें',
    roleSaved: 'भूमिका सहेजी गई',
  },
  te: {
    adviceTitle: 'నా సలహా',
    adviceSub: 'మీ పాత్ర, ప్రాంతం, భాషకు తగిన మార్గదర్శకం. నిర్ణయ సహాయం — అధికారిక ఆదేశం కాదు.',
    pickRole: 'ఈరోజు మీరు ఎవరు?',
    pickRoleSub: 'అదే ఆకాశం, మీ రోజుకు తగిన సలహా.',
    role_general: 'సాధారణ పౌరుడు',
    role_general_d: 'రోజువారీ జీవితం, ఆరోగ్యం, ప్రయాణం',
    role_farmer: 'రైతు',
    role_farmer_d: 'పంటలు, పిచికారీ, నీటిపారుదల',
    role_driver: 'డ్రైవర్',
    role_driver_d: 'రోడ్లు, దృశ్యమానత, ఆగే చోట్లు',
    role_fisherman: 'మత్స్యకారుడు',
    role_fisherman_d: 'సముద్రం, గాలి, హార్బర్ సంకేతాలు',
    role_aviation: 'విమానయానం',
    role_aviation_d: 'ఎగువ గాలులు, దృశ్యమానత',
    role_commuter: 'ప్రయాణికుడు',
    role_commuter_d: 'ద్విచక్ర వాహనాలు, బస్సులు, రైళ్లు',
    role_office: 'ఆఫీసు ఉద్యోగి',
    role_office_d: 'పని గంటలు, ప్రయాణ సమయాలు',
    cardsTitle: 'ఈరోజు కార్డులు',
    cardsSub: 'ప్రస్తుత వాతావరణం, అంచనా, అధికారిక హెచ్చరికల ఆధారంగా.',
    noCards: 'ప్రస్తుతం కార్డులు లేవు — పరిస్థితులు సాధారణంగా ఉన్నాయి.',
    basis: 'ఈ కార్డు ఎందుకు',
    validFor: 'దీనికి మంచిది',
    briefing: 'మీ బ్రీఫింగ్',
    changeRole: 'పాత్ర మార్చండి',
    roleSaved: 'పాత్ర సేవ్ అయింది',
  },
};
