// Situation-aware advisory cards (AdviceCards.jsx).
// EN / HI / TE parity is a ship gate — every key below must exist in all three.
export default {
  en: {
    cardsTitle: 'Situation advice',
    cardsSub: 'Cards built from live observations, the 3-day forecast and official alerts — never guessed.',
    kindAgri: 'Farming',
    kindHealth: 'Health',
    kindCommute: 'Travel',
    kindAlert: 'Official alert',
    basedOn: 'Based on',
    validFor: 'Valid for',
    cardsLoading: 'Checking weather and alerts…',
    cardsOfflineTitle: "Couldn't load advice cards",
    cardsOfflineBody: "Couldn't reach the server. Retry when you're back online — cards are built from fresh data, never guesses.",
    cardsRetry: 'Try again',
    cardsEmpty: 'No advice available right now.',
    sevInfo: 'Info',
  },
  hi: {
    cardsTitle: 'स्थिति सलाह',
    cardsSub: 'ताज़ा अवलोकन, 3-दिन के पूर्वानुमान और सरकारी चेतावनियों से बने कार्ड — अनुमान नहीं।',
    kindAgri: 'खेती',
    kindHealth: 'स्वास्थ्य',
    kindCommute: 'यात्रा',
    kindAlert: 'सरकारी चेतावनी',
    basedOn: 'आधार',
    validFor: 'के लिए मान्य',
    cardsLoading: 'मौसम और चेतावनियाँ जाँची जा रही हैं…',
    cardsOfflineTitle: 'सलाह कार्ड लोड नहीं हो सके',
    cardsOfflineBody: 'सर्वर से संपर्क नहीं हो सका। ऑनलाइन आने पर दोबारा कोशिश करें — कार्ड ताज़ा डेटा से बनेंगे, अनुमान से नहीं।',
    cardsRetry: 'दोबारा कोशिश करें',
    cardsEmpty: 'अभी कोई सलाह उपलब्ध नहीं है।',
    sevInfo: 'जानकारी',
  },
  te: {
    cardsTitle: 'పరిస్థితి సలహా',
    cardsSub: 'తాజా పరిశీలనలు, 3 రోజుల అంచనా మరియు అధికారిక హెచ్చరికల నుండి రూపొందిన కార్డులు — ఊహాగానాలు కాదు.',
    kindAgri: 'వ్యవసాయం',
    kindHealth: 'ఆరోగ్యం',
    kindCommute: 'ప్రయాణం',
    kindAlert: 'అధికారిక హెచ్చరిక',
    basedOn: 'ఆధారం',
    validFor: 'కోసం చెల్లుతుంది',
    cardsLoading: 'వాతావరణం మరియు హెచ్చరికలు తనిఖీ చేయబడుతున్నాయి…',
    cardsOfflineTitle: 'సలహా కార్డులు లోడ్ కాలేదు',
    cardsOfflineBody: 'సర్వర్‌ను చేరుకోలేకపోయాం. ఆన్‌లైన్‌కు వచ్చాక మళ్లీ ప్రయత్నించండి — కార్డులు తాజా సమాచారం నుండే రూపొందుతాయి, ఊహ నుండి కాదు.',
    cardsRetry: 'మళ్లీ ప్రయత్నించండి',
    cardsEmpty: 'ప్రస్తుతం సలహా అందుబాటులో లేదు.',
    sevInfo: 'సమాచారం',
  },
};
