// Strings for the Alerts page and the emergency panel.
//
// Written for a reader who may not read: every line is short, every word is a
// word a farmer, driver or fisherman already uses, and no line is bureaucratic.
// Severity CODES (RED/ORANGE/YELLOW/GREEN) are never translated - only the one
// word a person sees next to them.
//
// This file also supplies sevRed / sevOrange / sevYellow / sevGreen /
// sevUnknown / verdictExpired, which the Home hero reads too. They were
// missing, so both screens rendered the raw key name on screen.
//
// Keys already in i18n.js (basisUnverified, staleMay, agoPattern,
// homeUnavailable, nearbyNote) are deliberately NOT redefined here: this file
// only owns the words the Alerts page and the emergency panel need.
export default {
  en: {
    // --- page + cards -------------------------------------------------
    alertsTitle: 'Alerts',
    alertsLoading: 'Checking…',
    alertsRetry: 'Check again',
    alertsListen: 'Listen',
    alertsAsk: 'Ask',
    // --- global alert overlay: one slim pill across all pages -----------
    ovlActiveOne: '1 active alert',
    ovlActiveMany: '{n} active alerts',
    ovlDismiss: 'Dismiss',
    ovlOpenAlerts: 'Open alerts',
    // --- alert lifecycle rail (Calm Command redesign)
    lcDetected: 'Detected',
    lcIssued: 'Issued',
    lcLive: 'Live',
    lcResolved: 'Resolved',
    emgCmdLabel: 'Emergency broadcast',

    // --- severity: ONE word per official code --------------------------
    sevRed: 'Danger',
    sevOrange: 'Be alert',
    sevYellow: 'Be careful',
    sevGreen: 'All clear',
    sevUnknown: 'Not sure',
    verdictExpired: 'Expired',

    // --- empty state 1: service reached us, nothing is active ----------
    alertsNoneTitle: 'All clear here',
    alertsNoneBody: 'We checked. No warning for your district now.',

    // --- details view: nothing selected yet --------------------------------
    detailsNoneTitle: 'No alert selected',
    detailsNoneBody: 'No alert is selected yet. Open the Alerts page, pick a warning, and its full details will appear here.',

    // --- empty state 2: service did NOT reach us. Never a green tick ---
    alertsCannotTitle: 'Cannot check now',
    alertsCannotBody: 'The warning service did not answer. We cannot say it is safe.',

    // --- empty state 3: warnings exist, but for another district -------
    alertsNearbyTitle: 'Warnings nearby',
    alertsNearbyBody: '{n} official warnings in your state. Not for your district.',
    alertsNearbySub: 'Other districts. Not your district.',
    alertsNearbyBadge: 'Nearby',

    // --- community observations ----------------------------------------
    commTitle: "People's reports",
    commSub: 'From people. Not official.',
    commEmpty: 'No reports yet.',
    commWhatPh: 'What do you see?',
    commSend: 'Send',
    commRejected: 'Report not accepted.',
    commOffline: 'Server not reachable — report NOT sent.',
    rtFlooding: 'Flooding',
    rtRoadBlocked: 'Road blocked',
    rtFallenTree: 'Fallen tree',
    rtDamage: 'Damage',
    rtWaterlogging: 'Waterlogging',

    // --- emergency panel -----------------------------------------------
    emgTitle: 'Send SOS',
    emgSub: 'Works without network. Sent when it returns.',
    emgPick: 'What do you need?',
    emgSos: 'Send SOS',
    emgSend: 'Send',
    emgSync: 'Sync',
    emgQrRelay: 'Relay via QR',
    emgSimulate: 'Demo relay',
    emgSimHint: 'Demo only. Simulated.',
    emgMedical: 'Medical help needed',
    emgPeople: 'People',
    emgLess: 'Less',
    emgMore: 'More',
    emgNotePh: 'What do you see?',
    emgQueued: 'Queued {id} via {tr}.',
    emgNotSent: 'Not sent. Server not reachable.',
    emgSynced: 'Synced {n}. Waiting {p}.',
    emgSyncFailed: 'Sync failed. Still offline.',
    emgSimNote: 'Demo relay {id}. Simulated.',
    emgSimFailed: 'Demo failed. Server not reachable.',
    emgInboxTitle: 'Messages',
    emgInboxEmpty: 'No messages yet.',
    emgNearby: 'Nearby',
    emgNoPeers: 'no one yet',
    emgChipLocal: 'local',
    emgChipSynced: 'synced',
    emgHops: 'hops {n}',

    // --- one short word per message type -------------------------------
    mtHelp: 'Help',
    mtHere: 'I am here',
    mtDoctor: 'Doctor',
    mtWater: 'Water',
    mtFood: 'Food',
    mtDanger: 'Danger',
    mtTrapped: 'Trapped',
    mtRoad: 'Road blocked',
    mtSafe: 'I am safe',

    // --- P2P hop diagram -----------------------------------------------
    p2pTitle: 'How your message travels',
    p2pSimulated: 'SIMULATED — FOR DEMO ONLY',
    p2pYou: 'You',
    p2pRelayA: 'Relay A',
    p2pRelayB: 'Relay B',
    p2pRelayC: 'Relay C',
    p2pOut: 'Out',
    p2pSealed: 'Sealed',
    p2pTamper: 'Tamper-proof',
    p2pQueued: 'Queued',
    p2pHops: 'Hops',

    // --- lifecycle states -----------------------------------------------
    stUpcoming: 'Upcoming',
    stPreAlert: 'Pre-alert',
    stActive: 'Active',
    stUpdated: 'Updated',
    stExtended: 'Extended',
    stEnded: 'Ended',
    stCancelled: 'Cancelled',
  },
  hi: {
    alertsTitle: 'चेतावनी',
    alertsLoading: 'जाँच हो रही है…',
    alertsRetry: 'फिर जाँचें',
    alertsListen: 'सुनें',
    alertsAsk: 'पूछें',
    ovlActiveOne: '1 सक्रिय चेतावनी',
    ovlActiveMany: '{n} सक्रिय चेतावनी',
    ovlDismiss: 'हटाएँ',
    ovlOpenAlerts: 'चेतावनी खोलें',
    lcDetected: 'पता चला',
    lcIssued: 'जारी',
    lcLive: 'सक्रिय',
    lcResolved: 'समाप्त',
    emgCmdLabel: 'आपातकालीन प्रसारण',

    sevRed: 'खतरा',
    sevOrange: 'सतर्क रहें',
    sevYellow: 'सावधान',
    sevGreen: 'सब ठीक',
    sevUnknown: 'पता नहीं',
    verdictExpired: 'समय बीत गया',

    alertsNoneTitle: 'यहाँ सब ठीक है',
    alertsNoneBody: 'हमने जाँच लिया। आपके जिले में अभी कोई चेतावनी नहीं है।',

    detailsNoneTitle: 'कोई चेतावनी चयनित नहीं',
    detailsNoneBody: 'अभी कोई चेतावनी चयनित नहीं है। चेतावनी पेज खोलें, एक चेतावनी चुनें, और उसका पूरा विवरण यहाँ दिखेगा।',

    alertsCannotTitle: 'अभी जाँच नहीं हो सकी',
    alertsCannotBody: 'चेतावनी सेवा ने जवाब नहीं दिया। हम यह नहीं कह सकते कि सब ठीक है।',

    alertsNearbyTitle: 'आस-पास चेतावनी',
    alertsNearbyBody: 'आपके राज्य में {n} सरकारी चेतावनियाँ हैं। ये आपके जिले की नहीं हैं।',
    alertsNearbySub: 'दूसरे जिलों की चेतावनी। आपके जिले की नहीं।',
    alertsNearbyBadge: 'पास में',

    commTitle: 'लोगों की रिपोर्ट',
    commSub: 'लोगों से। सरकारी नहीं।',
    commEmpty: 'अभी कोई रिपोर्ट नहीं।',
    commWhatPh: 'आपको क्या दिख रहा है?',
    commSend: 'भेजें',
    commRejected: 'रिपोर्ट स्वीकार नहीं हुई।',
    commOffline: 'सर्वर नहीं मिला — रिपोर्ट नहीं भेजी गई।',
    rtFlooding: 'बाढ़',
    rtRoadBlocked: 'रास्ता बंद',
    rtFallenTree: 'गिरा पेड़',
    rtDamage: 'नुकसान',
    rtWaterlogging: 'पानी भरना',

    emgTitle: 'SOS भेजें',
    emgSub: 'बिना नेटवर्क भी चलता है। नेटवर्क आने पर भेज दिया जाएगा।',
    emgPick: 'आपको क्या चाहिए?',
    emgSos: 'मदद भेजें',
    emgSend: 'भेजें',
    emgSync: 'सिंक',
    emgQrRelay: 'QR से भेजें',
    emgSimulate: 'डेमो रिले',
    emgSimHint: 'सिर्फ़ डेमो। नकली।',
    emgMedical: 'चिकित्सा सहायता चाहिए',
    emgPeople: 'लोग',
    emgLess: 'कम',
    emgMore: 'ज़्यादा',
    emgNotePh: 'आपको क्या दिख रहा है?',
    emgQueued: 'कतार में {id} · {tr}।',
    emgNotSent: 'नहीं भेजा। सर्वर नहीं मिला।',
    emgSynced: '{n} भेजे गए। {p} बाकी।',
    emgSyncFailed: 'सिंक नहीं हुआ। अभी ऑफ़लाइन।',
    emgSimNote: 'डेमो रिले {id}। नकली।',
    emgSimFailed: 'डेमो नहीं चला। सर्वर नहीं मिला।',
    emgInboxTitle: 'संदेश',
    emgInboxEmpty: 'अभी कोई संदेश नहीं।',
    emgNearby: 'पास में',
    emgNoPeers: 'अभी कोई नहीं',
    emgChipLocal: 'यहीं',
    emgChipSynced: 'भेजा गया',
    emgHops: 'चरण {n}',

    mtHelp: 'मदद',
    mtHere: 'मैं यहाँ हूँ',
    mtDoctor: 'डॉक्टर',
    mtWater: 'पानी',
    mtFood: 'खाना',
    mtDanger: 'खतरा',
    mtTrapped: 'फँसे हैं',
    mtRoad: 'रास्ता बंद',
    mtSafe: 'मैं सुरक्षित हूँ',

    // --- P2P hop diagram -----------------------------------------------
    p2pTitle: 'आपका संदेश कैसे जाता है',
    p2pSimulated: 'SIMULATED — FOR DEMO ONLY',
    p2pYou: 'आप',
    p2pRelayA: 'रिले A',
    p2pRelayB: 'रिले B',
    p2pRelayC: 'रिले C',
    p2pOut: 'बाहर',
    p2pSealed: 'सीलबंद',
    p2pTamper: 'छेड़छाड़-रोधी',
    p2pQueued: 'कतार में',
    p2pHops: 'चरण',

    // --- lifecycle states -----------------------------------------------
    stUpcoming: 'आने वाला',
    stPreAlert: 'पहले से चेतावनी',
    stActive: 'चालू',
    stUpdated: 'बदला गया',
    stExtended: 'बढ़ाया गया',
    stEnded: 'समाप्त',
    stCancelled: 'रद्द',
  },
  te: {
    alertsTitle: 'హెచ్చరికలు',
    alertsLoading: 'తనిఖీ చేస్తున్నాం…',
    alertsRetry: 'మళ్లీ తనిఖీ చేయండి',
    alertsListen: 'వినండి',
    alertsAsk: 'అడగండి',
    ovlActiveOne: '1 క్రియాశీల హెచ్చరిక',
    ovlActiveMany: '{n} క్రియాశీల హెచ్చరికలు',
    ovlDismiss: 'తీసివేయి',
    ovlOpenAlerts: 'హెచ్చరికలు తెరవండి',
    lcDetected: 'గుర్తించబడింది',
    lcIssued: 'జారీ చేయబడింది',
    lcLive: 'ప్రత్యక్షం',
    lcResolved: 'పరిష్కరించబడింది',
    emgCmdLabel: 'అత్యవసర ప్రసారం',

    sevRed: 'ప్రమాదం',
    sevOrange: 'అప్రమత్తంగా ఉండండి',
    sevYellow: 'జాగ్రత్త',
    sevGreen: 'అంతా సురక్షితం',
    sevUnknown: 'తెలియదు',
    verdictExpired: 'గడువు ముగిసింది',

    alertsNoneTitle: 'ఇక్కడ అంతా సురక్షితం',
    alertsNoneBody: 'మేము తనిఖీ చేశాం. మీ జిల్లాకు ఇప్పుడు హెచ్చరిక లేదు.',

    detailsNoneTitle: 'ఎలాంటి హెచ్చరిక ఎంపిక కాలేదు',
    detailsNoneBody: 'ఇంకా ఏ హెచ్చరిక ఎంపిక కాలేదు. హెచ్చరికల పేజీని తెరిచి, ఒక హెచ్చరికను ఎంచుకోండి — దాని పూర్తి వివరాలు ఇక్కడ కనిపిస్తాయి.',

    alertsCannotTitle: 'ఇప్పుడు తనిఖీ చేయలేము',
    alertsCannotBody: 'హెచ్చరిక సేవ సమాధానం ఇవ్వలేదు. ఇది సురక్షితం అని చెప్పలేము.',

    alertsNearbyTitle: 'సమీపంలో హెచ్చరికలు',
    alertsNearbyBody: 'మీ రాష్ట్రంలో {n} అధికారిక హెచ్చరికలు ఉన్నాయి. అవి మీ జిల్లాకు కావు.',
    alertsNearbySub: 'వేరే జిల్లాల హెచ్చరికలు. మీ జిల్లాకు కావు.',
    alertsNearbyBadge: 'సమీపంలో',

    commTitle: 'ప్రజల నివేదికలు',
    commSub: 'ప్రజల నుండి. అధికారికం కాదు.',
    commEmpty: 'ఇంకా నివేదికలు లేవు.',
    commWhatPh: 'మీకు ఏమి కనిపిస్తోంది?',
    commSend: 'పంపండి',
    commRejected: 'నివేదిక ఆమోదించబడలేదు.',
    commOffline: 'సర్వర్ అందుబాటులో లేదు — నివేదిక పంపలేదు.',
    rtFlooding: 'వరద',
    rtRoadBlocked: 'దారి మూసివేత',
    rtFallenTree: 'పడిన చెట్టు',
    rtDamage: 'నష్టం',
    rtWaterlogging: 'నీరు నిలవడం',

    emgTitle: 'SOS పంపండి',
    emgSub: 'నెట్‌వర్క్ లేకున్నా పనిచేస్తుంది. నెట్‌వర్క్ వచ్చాక పంపుతాం.',
    emgPick: 'మీకు ఏమి కావాలి?',
    emgSos: 'సహాయం పంపండి',
    emgSend: 'పంపండి',
    emgSync: 'సింక్',
    emgQrRelay: 'QR ద్వారా పంపండి',
    emgSimulate: 'డెమో రిలే',
    emgSimHint: 'డెమో మాత్రమే. నకిలీది.',
    emgMedical: 'వైద్య సహాయం కావాలి',
    emgPeople: 'మంది',
    emgLess: 'తక్కువ',
    emgMore: 'ఎక్కువ',
    emgNotePh: 'మీకు ఏమి కనిపిస్తోంది?',
    emgQueued: 'క్యూలో {id} · {tr}.',
    emgNotSent: 'పంపలేదు. సర్వర్ అందుబాటులో లేదు.',
    emgSynced: '{n} పంపబడ్డాయి. {p} మిగిలాయి.',
    emgSyncFailed: 'సింక్ కాలేదు. ఇంకా ఆఫ్‌లైన్.',
    emgSimNote: 'డెమో రిలే {id}. నకిలీది.',
    emgSimFailed: 'డెమో కాలేదు. సర్వర్ అందుబాటులో లేదు.',
    emgInboxTitle: 'సందేశాలు',
    emgInboxEmpty: 'ఇంకా సందేశాలు లేవు.',
    emgNearby: 'సమీపంలో',
    emgNoPeers: 'ఇంకా ఎవరూ లేరు',
    emgChipLocal: 'ఇక్కడే',
    emgChipSynced: 'పంపబడింది',
    emgHops: 'దశలు {n}',

    mtHelp: 'సహాయం',
    mtHere: 'నేను ఇక్కడ ఉన్నాను',
    mtDoctor: 'డాక్టర్',
    mtWater: 'నీరు',
    mtFood: 'ఆహారం',
    mtDanger: 'ప్రమాదం',
    mtTrapped: 'చిక్కుకున్నారు',
    mtRoad: 'దారి మూసివేత',
    mtSafe: 'నేను సురక్షితం',

    // --- P2P hop diagram -----------------------------------------------
    p2pTitle: 'మీ సందేశం ఎలా వెళ్తుంది',
    p2pSimulated: 'SIMULATED — FOR DEMO ONLY',
    p2pYou: 'మీరు',
    p2pRelayA: 'రిలే A',
    p2pRelayB: 'రిలే B',
    p2pRelayC: 'రిలే C',
    p2pOut: 'బయటకు',
    p2pSealed: 'ముద్రించబడింది',
    p2pTamper: 'మార్చడం కుదరదు',
    p2pQueued: 'క్యూలో',
    p2pHops: 'దశలు',

    // --- lifecycle states -----------------------------------------------
    stUpcoming: 'రాబోయేది',
    stPreAlert: 'ముందస్తు హెచ్చరిక',
    stActive: 'కొనసాగుతోంది',
    stUpdated: 'మార్చబడింది',
    stExtended: 'పొడిగించబడింది',
    stEnded: 'ముగిసింది',
    stCancelled: 'రద్దు చేయబడింది',
  },
};
