// Alerts view.
export default {
  en: {
    alertsTitle: 'Alerts',
    alertsSub: 'Official CAP warnings — active and expired, each with its full lifecycle.',
    active: 'Active now',
    expired: 'Expired',
    none: 'All clear here',
    noneSub: 'We checked. No warning for your district now.',
    proof: 'Last checked {t} · SACHET CAP',
    issued: 'Issued',
    expires: 'Expires',
    ended: 'Ended',
    instruction: 'What to do',
    issuedBy: 'Issued by',
    area: 'Area',
    severity: 'Severity',
    sevExtreme: 'Extreme',
    sevSevere: 'Severe',
    sevModerate: 'Moderate',
    sevMinor: 'Minor',
    sevUnknown: 'Unknown',
    tapRead: 'Read the full warning',
    official: 'Official',
    nearby: 'Nearby',
    untitled: 'Official warning',
  },
  hi: {
    alertsTitle: 'अलर्ट',
    alertsSub: 'आधिकारिक CAP चेतावनियाँ — सक्रिय और समाप्त, प्रत्येक का पूरा जीवनचक्र।',
    active: 'अभी सक्रिय',
    expired: 'समाप्त',
    none: 'यहाँ सब साफ़ है',
    noneSub: 'हमने जाँचा। आपके ज़िले के लिए अभी कोई चेतावनी नहीं।',
    proof: '{t} अंतिम जाँच · SACHET CAP',
    issued: 'जारी',
    expires: 'समाप्ति',
    ended: 'समाप्त हुआ',
    instruction: 'क्या करें',
    issuedBy: 'जारीकर्ता',
    area: 'क्षेत्र',
    severity: 'गंभीरता',
    sevExtreme: 'अत्यंत गंभीर',
    sevSevere: 'गंभीर',
    sevModerate: 'मध्यम',
    sevMinor: 'हल्का',
    sevUnknown: 'अज्ञात',
    tapRead: 'पूरी चेतावनी पढ़ें',
    official: 'आधिकारिक',
    nearby: 'आस-पास',
    untitled: 'आधिकारिक चेतावनी',
  },
  te: {
    alertsTitle: 'హెచ్చరికలు',
    alertsSub: 'అధికారిక CAP హెచ్చరికలు — క్రియాశీలమైనవి, ముగిసినవి, ప్రతిదాని పూర్తి జీవితచక్రంతో.',
    active: 'ప్రస్తుతం క్రియాశీలం',
    expired: 'ముగిసినవి',
    none: 'ఇక్కడ అంతా స్పష్టం',
    noneSub: 'మేము తనిఖీ చేసాము. మీ జిల్లాకు ప్రస్తుతం హెచ్చరిక లేదు.',
    proof: '{t} చివరి తనిఖీ · SACHET CAP',
    issued: 'జారీ',
    expires: 'ముగింపు',
    ended: 'ముగిసింది',
    instruction: 'ఏమి చేయాలి',
    issuedBy: 'జారీ చేసినవారు',
    area: 'ప్రాంతం',
    severity: 'తీవ్రత',
    sevExtreme: 'అత్యంత తీవ్రం',
    sevSevere: 'తీవ్రం',
    sevModerate: 'మధ్యస్థం',
    sevMinor: 'స్వల్పం',
    sevUnknown: 'తెలియదు',
    tapRead: 'పూర్తి హెచ్చరిక చదవండి',
    official: 'అధికారిక',
    nearby: 'సమీపంలో',
    untitled: 'అధికారిక హెచ్చరిక',
  },
};
