// Ask / chat-board strings: provenance, verdict and evidence vocabulary.
//
// Short and plain on purpose — the answer's trustworthiness must land in 2-3
// seconds for a user with limited literacy, so these are labels, not sentences.
// Provenance codes (LIVE/CACHED/DEMO/COMMUNITY/UNAVAILABLE/UNCONFIGURED) are
// machine-readable and are NEVER listed here: they are rendered verbatim.
export default {
  en: {
    factsTitle: 'Where each fact came from',
    evCurrent: 'Current weather',
    evForecast: 'Forecast',
    evWarning: 'Official warning',
    evAlert: 'Alert',
    evOther: 'Data',
    evIssued: 'Issued',
    evValidTo: 'Valid till',
    verdictTitle: 'Warning check',
    verdictBasis: 'Checked via',
    verdictOfficial: 'Official severity',
    warnNone: 'No warning for this district.',
    warnConfirmed: 'Official warning active.',
    warnUnconfirmed: 'Warning not confirmed - do not assume it is safe.',
    warnUnreachable: 'Warning service not reachable - cannot confirm any warning.',
    nearby: 'Other alerts in your state',
    freshness: 'Data freshness',
    aiRole: 'AI role',
    aiRoleValue: 'Explains only - never changes official severity',
    riskNote: 'WeatherGPT view - not an IMD rating',
    sourcesTitle: 'Live sources',
    srcProbing: 'Checking sources…',
    srcKeyGated: 'No key - not configured',
    srcNone: 'No sources reported.',
    srcFailed: 'Source check failed - cannot confirm which are live.',
    srcUpdated: 'Updated',
    srcErrorHint: 'check the feed URL / network connection, or switch the app to demo mode',
    micHint: 'Speak your question',
  },
  hi: {
    factsTitle: 'हर तथ्य कहाँ से आया',
    evCurrent: 'अभी का मौसम',
    evForecast: 'पूर्वानुमान',
    evWarning: 'आधिकारिक चेतावनी',
    evAlert: 'अलर्ट',
    evOther: 'डेटा',
    evIssued: 'जारी',
    evValidTo: 'तक मान्य',
    verdictTitle: 'चेतावनी जाँच',
    verdictBasis: 'कैसे जाँचा',
    verdictOfficial: 'आधिकारिक गंभीरता',
    warnNone: 'इस ज़िले के लिए कोई चेतावनी नहीं।',
    warnConfirmed: 'आधिकारिक चेतावनी सक्रिय है।',
    warnUnconfirmed: 'चेतावनी पुष्ट नहीं - इसे सुरक्षित न मानें।',
    warnUnreachable: 'चेतावनी सेवा नहीं पहुँची - कोई चेतावनी पुष्ट नहीं कर सकते।',
    nearby: 'आपके राज्य में अन्य अलर्ट',
    freshness: 'डेटा ताज़गी',
    aiRole: 'AI की भूमिका',
    aiRoleValue: 'सिर्फ़ समझाता है - आधिकारिक गंभीरता नहीं बदलता',
    riskNote: 'WeatherGPT का आकलन - IMD रेटिंग नहीं',
    sourcesTitle: 'सक्रिय स्रोत',
    srcProbing: 'स्रोत जाँच रहे हैं…',
    srcKeyGated: 'कुंजी नहीं - कॉन्फ़िगर नहीं',
    srcNone: 'कोई स्रोत नहीं मिला।',
    srcFailed: 'स्रोत जाँच विफल - कौन सक्रिय है, पुष्ट नहीं।',
    srcUpdated: 'अपडेट',
    srcErrorHint: 'फ़ीड URL / नेटवर्क कनेक्शन जांचें, या ऐप को डेमो मोड में बदलें',
    micHint: 'अपना सवाल बोलें',
  },
  te: {
    factsTitle: 'ఏ విషయం ఎక్కడి నుండి',
    evCurrent: 'ప్రస్తుత వాతావరణం',
    evForecast: 'అంచనా',
    evWarning: 'అధికారిక హెచ్చరిక',
    evAlert: 'హెచ్చరిక',
    evOther: 'డేటా',
    evIssued: 'జారీ',
    evValidTo: 'వరకు చెల్లుతుంది',
    verdictTitle: 'హెచ్చరిక తనిఖీ',
    verdictBasis: 'ఎలా తనిఖీ చేశాం',
    verdictOfficial: 'అధికారిక తీవ్రత',
    warnNone: 'ఈ జిల్లాకు హెచ్చరిక లేదు.',
    warnConfirmed: 'అధికారిక హెచ్చరిక క్రియాశీలంగా ఉంది.',
    warnUnconfirmed: 'హెచ్చరిక ధృవీకరించలేదు - సురక్షితం అని భావించకండి.',
    warnUnreachable: 'హెచ్చరిక సేవ అందలేదు - ఏ హెచ్చరికను ధృవీకరించలేము.',
    nearby: 'మీ రాష్ట్రంలో ఇతర హెచ్చరికలు',
    freshness: 'డేటా తాజాదనం',
    aiRole: 'AI పాత్ర',
    aiRoleValue: 'వివరణ మాత్రమే - అధికారిక తీవ్రతను మార్చదు',
    riskNote: 'WeatherGPT అంచనా - IMD రేటింగ్ కాదు',
    sourcesTitle: 'ప్రత్యక్ష మూలాలు',
    srcProbing: 'మూలాలు తనిఖీ అవుతున్నాయి…',
    srcKeyGated: 'కీ లేదు - కాన్ఫిగర్ కాలేదు',
    srcNone: 'మూలాలు ఏవీ నివేదించబడలేదు.',
    srcFailed: 'మూలాల తనిఖీ విఫలమైంది - ఏవి ప్రత్యక్షమో ధృవీకరించలేము.',
    srcUpdated: 'నవీకరించబడింది',
    srcErrorHint: 'ఫీడ్ URL / నెట్‌వర్క్ కనెక్షన్‌ను తనిఖీ చేయండి, లేదా యాప్‌ను డెమో మోడ్‌కు మార్చండి',
    micHint: 'మీ ప్రశ్న చెప్పండి',
  },
};
