// Aviation briefing strings (AviationBriefing.jsx, Details route).
// EN / HI / TE parity is a ship gate — every key below must exist in all three.
// No Tamil script content. Severity codes stay machine-readable upstream;
// the component translates only its own chrome and proxy/unavailable copy.
export default {
  en: {
    avTitle: 'Aviation briefing',
    avSub: 'Winds aloft, cloud and visibility proxies, and official alerts for your district. Planning aid only — never an official briefing.',
    avDisclaimer: 'Planning aid only — NOT an official METAR/TAF. Check IMD aviation bulletins before flight.',
    avLoading: 'Fetching the aviation briefing…',
    avOfflineTitle: "Couldn't load the briefing",
    avOfflineBody: "Couldn't reach the server. Briefing data is built from fresh feeds and cached values are never shown as current — retry when you're back online.",
    avRetry: 'Try again',
    avWinds: 'Winds aloft',
    avWindsSub: 'GFS model winds at 850 / 700 / 500 hPa. Model output, not IMD observations.',
    avNow: 'Now',
    avPlus6h: '+6h',
    avLevel: 'Level',
    avCloud: 'Cloud cover',
    avCloudProxy: 'Proxy — not a measured ceiling',
    avCloudSub: 'Cover percentage only. This is not a measured cloud-base height.',
    avVis: 'Visibility',
    avVisProxy: 'Forecast value — not measured RVR',
    avTurb: 'Turbulence and icing',
    avTurbSub: 'Coarse screening proxies from GFS shear and temperature — not official forecasts.',
    avShear: 'Wind shear 850→500 hPa',
    avTurbBand: 'Turbulence proxy',
    avBandLow: 'Low',
    avBandModerate: 'Moderate',
    avBandElevated: 'Elevated',
    avFreeze: 'Freezing level',
    avFreezeBetween: 'Between',
    avSun: 'Sunrise and sunset',
    avSunrise: 'Sunrise',
    avSunset: 'Sunset',
    avAlerts: 'Official alerts for your area',
    avAlertsSub: 'Same authoritative severity the alerts console shows — never re-graded here.',
    avNoActive: 'No active official warning for your district right now.',
    avFeedsUnanswered: 'Alert feeds could not be reached — no alert data shown.',
    avLow: 'Low cloud',
    avMid: 'Mid cloud',
    avHigh: 'High cloud',
    avUnavailable: 'Not available',
    avProxyTag: 'Proxy',
    avKt: 'kt',
    avWhyWhy: 'Why is this section unavailable?',
    avMode: 'Source mode',
    avSample: 'Sample data',
    avSampleNote: 'Sample values for demo — not real observations.',
  },
  hi: {
    avTitle: 'विमानन ब्रीफिंग',
    avSub: 'आपके ज़िले के लिए ऊपरी हवाएँ, मेघ और दृश्यता प्रॉक्सी, और सरकारी चेतावनियाँ। केवल योजना-सहायता — आधिकारिक ब्रीफिंग कभी नहीं।',
    avDisclaimer: 'केवल योजना-सहायता के लिए — यह कोई आधिकारिक METAR/TAF नहीं है। उड़ान से पहले IMD के विमानन बुलेटिन अवश्य देखें।',
    avLoading: 'विमानन ब्रीफिंग प्राप्त की जा रही है…',
    avOfflineTitle: 'ब्रीफिंग लोड नहीं हो सकी',
    avOfflineBody: 'सर्वर से संपर्क नहीं हो सका। ब्रीफिंग डेटा ताज़ा फ़ीड से बनता है और पुराना डेटा कभी वर्तमान बताकर नहीं दिखाया जाता — ऑनलाइन आने पर दोबारा कोशिश करें।',
    avRetry: 'दोबारा कोशिश करें',
    avWinds: 'ऊपरी हवाएँ',
    avWindsSub: '850 / 700 / 500 hPa पर GFS मॉडल हवाएँ। मॉडल आउटपुट है, IMD अवलोकन नहीं।',
    avNow: 'अभी',
    avPlus6h: '+6 घंटे',
    avLevel: 'स्तर',
    avCloud: 'मेघावरण',
    avCloudProxy: 'प्रॉक्सी — मापी गई छत नहीं',
    avCloudSub: 'केवल आवरण प्रतिशत। यह मापी गई मेघ-आधार ऊँचाई नहीं है।',
    avVis: 'दृश्यता',
    avVisProxy: 'पूर्वानुमान मान — मापा गया RVR नहीं',
    avTurb: 'टर्बुलेंस और बर्फ़ जमना',
    avTurbSub: 'GFS शीयर और तापमान से मोटा प्रॉक्सी — आधिकारिक पूर्वानुमान नहीं।',
    avShear: 'पवन शीयर 850→500 hPa',
    avTurbBand: 'टर्बुलेंस प्रॉक्सी',
    avBandLow: 'कम',
    avBandModerate: 'मध्यम',
    avBandElevated: 'बढ़ा हुआ',
    avFreeze: 'हिमांक स्तर',
    avFreezeBetween: 'के बीच',
    avSun: 'सूर्योदय और सूर्यास्त',
    avSunrise: 'सूर्योदय',
    avSunset: 'सूर्यास्त',
    avAlerts: 'आपके क्षेत्र के लिए सरकारी चेतावनियाँ',
    avAlertsSub: 'वही आधिकारिक गंभीरता जो चेतावनी कंसोल दिखाता है — यहाँ दोबारा ग्रेड नहीं किया जाता।',
    avNoActive: 'अभी आपके ज़िले के लिए कोई सक्रिय सरकारी चेतावनी नहीं है।',
    avFeedsUnanswered: 'चेतावनी फ़ीड से संपर्क नहीं हो सका — कोई चेतावनी डेटा नहीं दिखाया गया।',
    avLow: 'निचले मेघ',
    avMid: 'मध्य मेघ',
    avHigh: 'ऊपरी मेघ',
    avUnavailable: 'उपलब्ध नहीं',
    avProxyTag: 'प्रॉक्सी',
    avKt: 'नॉट',
    avWhyWhy: 'यह अनुभाग क्यों उपलब्ध नहीं है?',
    avMode: 'स्रोत मोड',
    avSample: 'नमूना डेटा',
    avSampleNote: 'डेमो के लिए नमूना मान — वास्तविक अवलोकन नहीं।',
  },
  te: {
    avTitle: 'విమానయాన బ్రీఫింగ్',
    avSub: 'మీ జిల్లా కోసం ఎగువ గాలులు, మేఘ మరియు దృశ్యమానత ప్రాక్సీలు, మరియు అధికారిక హెచ్చరికలు. ప్రణాళిక సహాయం మాత్రమే — అధికారిక బ్రీఫింగ్ ఎప్పుడూ కాదు.',
    avDisclaimer: 'ప్రణాళిక సహాయం మాత్రమే — ఇది అధికారిక METAR/TAF కాదు. విమానం ముందు IMD విమానయాన బులెటిన్లను తప్పనిసరిగా చూడండి.',
    avLoading: 'విమానయాన బ్రీఫింగ్ పొందుతోంది…',
    avOfflineTitle: 'బ్రీఫింగ్ లోడ్ కాలేదు',
    avOfflineBody: 'సర్వర్‌ను చేరుకోలేకపోయాం. బ్రీఫింగ్ డేటా తాజా ఫీడ్‌ల నుండే రూపొందుతుంది మరియు పాత డేటా ఎప్పుడూ ప్రస్తుతమైనట్లు చూపబడదు — ఆన్‌లైన్‌కు వచ్చాక మళ్లీ ప్రయత్నించండి.',
    avRetry: 'మళ్లీ ప్రయత్నించండి',
    avWinds: 'ఎగువ గాలులు',
    avWindsSub: '850 / 700 / 500 hPa వద్ద GFS మోడల్ గాలులు. మోడల్ అవుట్‌పుట్, IMD పరిశీలనలు కావు.',
    avNow: 'ఇప్పుడు',
    avPlus6h: '+6 గం',
    avLevel: 'స్థాయి',
    avCloud: 'మేఘావరణం',
    avCloudProxy: 'ప్రాక్సీ — కొలిచిన శిఖరం కాదు',
    avCloudSub: 'కవరేజ్ శాతం మాత్రమే. ఇది కొలిచిన మేఘ-అడుగు ఎత్తు కాదు.',
    avVis: 'దృశ్యమానత',
    avVisProxy: 'అంచనా విలువ — కొలిచిన RVR కాదు',
    avTurb: 'అల్లకల్లోలం మరియు మంచు',
    avTurbSub: 'GFS షియర్ మరియు ఉష్ణోగ్రత నుండి స్థూల ప్రాక్సీ — అధికారిక అంచనాలు కావు.',
    avShear: 'గాలి షియర్ 850→500 hPa',
    avTurbBand: 'అల్లకల్లోలం ప్రాక్సీ',
    avBandLow: 'తక్కువ',
    avBandModerate: 'మధ్యస్థ',
    avBandElevated: 'పెరిగిన',
    avFreeze: 'ఘనీభవన స్థాయి',
    avFreezeBetween: 'మధ్య',
    avSun: 'సూర్యోదయం మరియు సూర్యాస్తమయం',
    avSunrise: 'సూర్యోదయం',
    avSunset: 'సూర్యాస్తమయం',
    avAlerts: 'మీ ప్రాంతానికి అధికారిక హెచ్చరికలు',
    avAlertsSub: 'హెచ్చరిక కన్సోల్ చూపే అదే అధికారిక తీవ్రత — ఇక్కడ మళ్లీ గ్రేడ్ చేయబడదు.',
    avNoActive: 'ప్రస్తుతం మీ జిల్లాకు క్రియాశీల అధికారిక హెచ్చరిక ఏదీ లేదు.',
    avFeedsUnanswered: 'హెచ్చరిక ఫీడ్‌లను చేరుకోలేకపోయాం — హెచ్చరిక డేటా చూపబడలేదు.',
    avLow: 'తక్కువ మేఘాలు',
    avMid: 'మధ్య మేఘాలు',
    avHigh: 'ఎగువ మేఘాలు',
    avUnavailable: 'అందుబాటులో లేదు',
    avProxyTag: 'ప్రాక్సీ',
    avKt: 'kt',
    avWhyWhy: 'ఈ విభాగం ఎందుకు అందుబాటులో లేదు?',
    avMode: 'మూలం మోడ్',
    avSample: 'నమూనా డేటా',
    avSampleNote: 'డెమో కోసం నమూనా విలువలు — నిజమైన పరిశీలనలు కావు.',
  },
};
