// Chat view.
export default {
  en: {
    chatTitle: 'Ask SAARTHI',
    ph: 'Ask about rain, heat, warnings, travel…',
    chatSend: 'Send',
    thinking: 'Checking live data…',
    chatErr: "Couldn't reach the server. Try again.",
    noMic: "Voice input isn't available in this browser — type instead.",
    micStart: 'Start voice input',
    micStop: 'Stop voice input',
    voiceFallback: 'Voice answers use your browser for now.',
    greeting: 'Namaste! Ask me about rain, heat, warnings or travel — I answer from live official data.',
    newChat: 'New chat',
    heard: 'I heard',
    agentRole: 'Your weather companion',
    voiceSarvam: 'Voice: Sarvam',
    voiceBrowser: 'Voice: browser',
    briefNow: '{temp}°C and {cond} in {loc} right now.',
    briefNoData: "I couldn't reach live weather data just now.",
    briefWarnActive: 'Heads up — {sev} warning active: {hazard}.',
    briefWarnNearby: 'Heads up — {sev} warning nearby: {hazard}.',
    briefWarnClear: 'No active warnings for your district.',
    briefWarnUnknown: "I couldn't check warnings just now — please confirm with IMD or local authorities.",
    agentTagline: 'Talk to me — I answer from live weather and official warnings.',
    chip_general_1: 'Will it rain tomorrow?',
    chip_general_2: 'Any warnings for me?',
    chip_general_3: 'How\'s the wind today?',
    chip_farmer_1: 'Will it rain this week?',
    chip_farmer_2: 'Good day for spraying crops?',
    chip_farmer_3: 'Any storm or hail risk?',
    chip_driver_1: 'Will rain affect driving today?',
    chip_driver_2: 'How is road visibility?',
    chip_driver_3: 'Best time to travel tomorrow?',
    chip_fisherman_1: 'Is it safe to go to sea?',
    chip_fisherman_2: 'Sea wind speed today?',
    chip_fisherman_3: 'Any cyclone warning?',
    chip_aviation_1: 'Flying conditions today?',
    chip_aviation_2: 'Visibility for my flight?',
    chip_aviation_3: 'Any turbulence risk?',
    chip_commuter_1: 'Will I need an umbrella?',
    chip_commuter_2: 'Evening commute weather?',
    chip_commuter_3: 'Rain during rush hour?',
    chip_office_1: 'Do I need an umbrella today?',
    chip_office_2: 'Lunch-hour weather?',
    chip_office_3: 'Will it rain this evening?',
    recording: 'Recording… tap the mic to stop.',
    transcribing: 'Writing down what I heard…',
    stopListen: 'Stop',
  },
  hi: {
    chatTitle: 'SAARTHI से पूछें',
    ph: 'बारिश, गर्मी, चेतावनी, यात्रा के बारे में पूछें…',
    chatSend: 'भेजें',
    thinking: 'लाइव डेटा जाँचा जा रहा है…',
    chatErr: 'सर्वर से संपर्क नहीं हो सका। पुनः प्रयास करें।',
    noMic: 'इस ब्राउज़र में वॉइस इनपुट उपलब्ध नहीं — टाइप करें।',
    micStart: 'वॉइस इनपुट शुरू करें',
    micStop: 'वॉइस इनपुट रोकें',
    voiceFallback: 'वॉइस उत्तर अभी आपके ब्राउज़र से आते हैं।',
    greeting: 'नमस्ते! बारिश, गर्मी, चेतावनी या यात्रा के बारे में पूछें — मैं लाइव आधिकारिक डेटा से उत्तर देता हूँ।',
    newChat: 'नई चैट',
    heard: 'मैंने सुना',
    agentRole: 'आपका मौसम साथी',
    voiceSarvam: 'आवाज़: Sarvam',
    voiceBrowser: 'आवाज़: ब्राउज़र',
    briefNow: '{loc} में अभी {temp}°C और {cond}।',
    briefNoData: 'मैं अभी लाइव मौसम डेटा तक नहीं पहुँच सका।',
    briefWarnActive: 'ध्यान दें — {sev} चेतावनी सक्रिय है: {hazard}।',
    briefWarnNearby: 'ध्यान दें — आस-पास {sev} चेतावनी है: {hazard}।',
    briefWarnClear: 'आपके ज़िले के लिए कोई सक्रिय चेतावनी नहीं है।',
    briefWarnUnknown: 'मैं अभी चेतावनी जाँच नहीं सका — कृपया IMD या स्थानीय प्रशासन से पुष्टि करें।',
    agentTagline: 'मुझसे बात करें — मैं लाइव मौसम और आधिकारिक चेतावनियों से जवाब देता हूँ।',
    chip_general_1: 'क्या कल बारिश होगी?',
    chip_general_2: 'मेरे लिए कोई चेतावनी?',
    chip_general_3: 'आज हवा कैसी है?',
    chip_farmer_1: 'क्या इस हफ़्ते बारिश होगी?',
    chip_farmer_2: 'क्या आज फसल पर छिड़काव ठीक रहेगा?',
    chip_farmer_3: 'क्या आंधी या ओलों का खतरा है?',
    chip_driver_1: 'क्या आज बारिश से ड्राइविंग प्रभावित होगी?',
    chip_driver_2: 'सड़क पर दृश्यता कैसी है?',
    chip_driver_3: 'कल यात्रा का सबसे अच्छा समय?',
    chip_fisherman_1: 'क्या समुद्र में जाना सुरक्षित है?',
    chip_fisherman_2: 'आज समुद्री हवा की गति?',
    chip_fisherman_3: 'क्या कोई चक्रवात चेतावनी है?',
    chip_aviation_1: 'आज उड़ान की स्थिति कैसी है?',
    chip_aviation_2: 'मेरी उड़ान के लिए दृश्यता?',
    chip_aviation_3: 'क्या टर्बुलेंस का खतरा है?',
    chip_commuter_1: 'क्या मुझे छाता चाहिए होगा?',
    chip_commuter_2: 'शाम की यात्रा में मौसम?',
    chip_commuter_3: 'भीड़ के समय बारिश?',
    chip_office_1: 'क्या आज छाता ले जाऊँ?',
    chip_office_2: 'दोपहर के भोजन के समय मौसम?',
    chip_office_3: 'क्या आज शाम बारिश होगी?',
    recording: 'रिकॉर्ड हो रहा है… रोकने के लिए माइक दबाएँ।',
    transcribing: 'सुनी हुई बात लिख रहा हूँ…',
    stopListen: 'रोकें',
  },
  te: {
    chatTitle: 'SAARTHI ని అడగండి',
    ph: 'వర్షం, వేడి, హెచ్చరికలు, ప్రయాణం గురించి అడగండి…',
    chatSend: 'పంపండి',
    thinking: 'ప్రత్యక్ష డేటా తనిఖీ చేస్తోంది…',
    chatErr: 'సర్వర్‌ను చేరుకోలేకపోయాము. మళ్లీ ప్రయత్నించండి.',
    noMic: 'ఈ బ్రౌజర్‌లో వాయిస్ ఇన్‌పుట్ లేదు — టైప్ చేయండి.',
    micStart: 'వాయిస్ ఇన్‌పుట్ ప్రారంభించండి',
    micStop: 'వాయిస్ ఇన్‌పుట్ ఆపండి',
    voiceFallback: 'వాయిస్ సమాధానాలు ప్రస్తుతం మీ బ్రౌజర్ నుండే.',
    greeting: 'నమస్తే! వర్షం, వేడి, హెచ్చరికలు లేదా ప్రయాణం గురించి అడగండి — నేను ప్రత్యక్ష అధికారిక డేటా నుండి సమాధానం ఇస్తాను.',
    newChat: 'కొత్త చాట్',
    heard: 'నేను విన్నది',
    agentRole: 'మీ వాతావరణ సహచరుడు',
    voiceSarvam: 'వాయిస్: Sarvam',
    voiceBrowser: 'వాయిస్: బ్రౌజర్',
    briefNow: '{loc}లో ప్రస్తుతం {temp}°C మరియు {cond}.',
    briefNoData: 'ప్రత్యక్ష వాతావరణ డేటాను ఇప్పుడు చేరుకోలేకపోయాను.',
    briefWarnActive: 'గమనిక — {sev} హెచ్చరిక క్రియాశీలంగా ఉంది: {hazard}.',
    briefWarnNearby: 'గమనిక — సమీపంలో {sev} హెచ్చరిక ఉంది: {hazard}.',
    briefWarnClear: 'మీ జిల్లాకు ఎలాంటి క్రియాశీల హెచ్చరికలు లేవు.',
    briefWarnUnknown: 'హెచ్చరికలను ఇప్పుడు తనిఖీ చేయలేకపోయాను — దయచేసి IMD లేదా స్థానిక అధికారులతో నిర్ధారించండి.',
    agentTagline: 'నాతో మాట్లాడండి — ప్రత్యక్ష వాతావరణం, అధికారిక హెచ్చరికలతో జవాబిస్తాను.',
    chip_general_1: 'రేపు వర్షం పడుతుందా?',
    chip_general_2: 'నాకు ఏవైనా హెచ్చరికలు ఉన్నాయా?',
    chip_general_3: 'ఈరోజు గాలి ఎలా ఉంది?',
    chip_farmer_1: 'ఈ వారం వర్షం పడుతుందా?',
    chip_farmer_2: 'ఈరోజు పంటలకు మందు చల్లడం మంచిదా?',
    chip_farmer_3: 'తుఫాను లేదా వడగళ్ల ముప్పు ఉందా?',
    chip_driver_1: 'ఈరోజు వర్షం డ్రైవింగ్‌ను ప్రభావితం చేస్తుందా?',
    chip_driver_2: 'రోడ్డుపై దృశ్యమానత ఎలా ఉంది?',
    chip_driver_3: 'రేపు ప్రయాణానికి ఉత్తమ సమయం?',
    chip_fisherman_1: 'సముద్రంలోకి వెళ్లడం సురక్షితమేనా?',
    chip_fisherman_2: 'ఈరోజు సముద్రపు గాలి వేగం?',
    chip_fisherman_3: 'తుఫాను హెచ్చరిక ఏదైనా ఉందా?',
    chip_aviation_1: 'ఈరోజు విమాన పరిస్థితులు?',
    chip_aviation_2: 'నా విమానానికి దృశ్యమానత?',
    chip_aviation_3: 'టర్బులెన్స్ ముప్పు ఉందా?',
    chip_commuter_1: 'నాకు గొడుగు అవసరమా?',
    chip_commuter_2: 'సాయంత్రం ప్రయాణంలో వాతావరణం?',
    chip_commuter_3: 'రద్దీ సమయంలో వర్షం?',
    chip_office_1: 'ఈరోజు గొడుగు తీసుకెళ్లాలా?',
    chip_office_2: 'మధ్యాహ్న భోజన సమయంలో వాతావరణం?',
    chip_office_3: 'ఈ సాయంత్రం వర్షం పడుతుందా?',
    recording: 'రికార్డ్ అవుతోంది… ఆపడానికి మైక్ నొక్కండి.',
    transcribing: 'విన్నది రాస్తున్నాను…',
    stopListen: 'ఆపండి',
  },
};
