// Chat view.
export default {
  en: {
    chatTitle: 'Ask SAARTHI',
    ph: 'Ask about rain, heat, warnings, travel…',
    chatSend: 'Send',
    thinking: 'Checking live data…',
    chatErr: "Couldn't reach the server. Try again.",
    noMic: "Voice input isn't available in this browser — type instead.",
    micStart: 'Start voice input',
    micStop: 'Stop voice input',
    voiceFallback: 'Voice answers use your browser for now.',
    greeting: 'Namaste! Ask me about rain, heat, warnings or travel — I answer from live official data.',
    newChat: 'New chat',
    heard: 'I heard',
  },
  hi: {
    chatTitle: 'SAARTHI से पूछें',
    ph: 'बारिश, गर्मी, चेतावनी, यात्रा के बारे में पूछें…',
    chatSend: 'भेजें',
    thinking: 'लाइव डेटा जाँचा जा रहा है…',
    chatErr: 'सर्वर से संपर्क नहीं हो सका। पुनः प्रयास करें।',
    noMic: 'इस ब्राउज़र में वॉइस इनपुट उपलब्ध नहीं — टाइप करें।',
    micStart: 'वॉइस इनपुट शुरू करें',
    micStop: 'वॉइस इनपुट रोकें',
    voiceFallback: 'वॉइस उत्तर अभी आपके ब्राउज़र से आते हैं।',
    greeting: 'नमस्ते! बारिश, गर्मी, चेतावनी या यात्रा के बारे में पूछें — मैं लाइव आधिकारिक डेटा से उत्तर देता हूँ।',
    newChat: 'नई चैट',
    heard: 'मैंने सुना',
  },
  te: {
    chatTitle: 'SAARTHI ని అడగండి',
    ph: 'వర్షం, వేడి, హెచ్చరికలు, ప్రయాణం గురించి అడగండి…',
    chatSend: 'పంపండి',
    thinking: 'ప్రత్యక్ష డేటా తనిఖీ చేస్తోంది…',
    chatErr: 'సర్వర్‌ను చేరుకోలేకపోయాము. మళ్లీ ప్రయత్నించండి.',
    noMic: 'ఈ బ్రౌజర్‌లో వాయిస్ ఇన్‌పుట్ లేదు — టైప్ చేయండి.',
    micStart: 'వాయిస్ ఇన్‌పుట్ ప్రారంభించండి',
    micStop: 'వాయిస్ ఇన్‌పుట్ ఆపండి',
    voiceFallback: 'వాయిస్ సమాధానాలు ప్రస్తుతం మీ బ్రౌజర్ నుండే.',
    greeting: 'నమస్తే! వర్షం, వేడి, హెచ్చరికలు లేదా ప్రయాణం గురించి అడగండి — నేను ప్రత్యక్ష అధికారిక డేటా నుండి సమాధానం ఇస్తాను.',
    newChat: 'కొత్త చాట్',
    heard: 'నేను విన్నది',
  },
};
