// App-chrome strings: the shell (sidebar/top bar/status banners), the crash
// boundary and the shared region labels.
//
// These were the last hardcoded English strings in the citizen-facing chrome.
// A fisherman who reads Telugu was still getting "Colour theme", "Conversation"
// and the DISASTER MODE banner in English — and that banner appears precisely
// when a confirmed severe warning is active, which is the worst moment to hand
// someone a language they may not read.
//
// Machine-readable codes (LIVE/CACHED/DEMO, RED/ORANGE, mode ids) are NOT here:
// they are rendered verbatim by design.
export default {
  en: {
    navSections: 'Sections',
    locAuto: 'Detected automatically',
    chatRegion: 'Conversation',
    disasterBanner: 'DISASTER MODE — verified severe warning active. Safety first, then communication.',
    boundaryTitle: 'This view failed to render',
    boundaryBody: 'The rest of the console keeps working. Nothing was invented to fill the gap.',
    srcStatusTitle: 'Data sources',
    srcStatusSub: 'Every source reports its own status. Nothing is labelled LIVE unless it is.',
    ntfUnread: 'Unread',
    alertsGroup: 'Alerts',
    p2pSimTitle: 'Simulated mesh — not a real radio path',
    p2pOutbox: 'Store-and-forward outbox',
    // --- settings: profile + permissions control center (Crew G) ---
    setProfile: 'Your profile',
    setRoleNote: 'Pick your role once — Home, chat and advice all follow it.',
    setRoleGo: 'Choose your role in Advisory',
    setPlaceNote: 'Type your district on the Home hero, or use GPS here.',
    setPermTitle: 'Permissions',
    setPermSub: 'What SAARTHI may use. Change any of these any time — nothing here locks you out.',
    permLocT: 'Location',
    permLocD: 'Finds your district for local warnings.',
    permMicT: 'Microphone',
    permMicD: 'Lets you ask questions by voice.',
    permSndT: 'Sound',
    permSndD: 'Spoken answers and alert sounds inside the app.',
    permNtfT: 'Notifications',
    permNtfD: 'Warns you even with the app closed.',
    permGranted: 'Allowed',
    permDenied: 'Blocked',
    permPrompt: 'Not asked yet',
    permUnknown: 'Could not check',
    permUnavailable: 'Not available on this device',
    permOn: 'On',
    permOff: 'Off',
    permWorking: 'Checking…',
    permAllow: 'Allow',
    permRetry: 'Try again',
    permHow: 'How to allow',
    permHide: 'Hide steps',
    setSoundNote: 'Off here mutes SAARTHI\u2019s spoken answers. Your device volume is separate.',
    locOpenSettings: 'Open settings',
    locGuideIos1: 'Open iPhone Settings, find this browser (or SAARTHI), and set Location to \u201cWhile Using\u201d.',
    locGuideIos2: 'Come back here and tap \u201cTry again\u201d.',
    locGuideAndroid1: 'Tap the lock (or tune) icon in the address bar \u2192 Permissions \u2192 Location \u2192 Allow.',
    locGuideAndroid2: 'Reload the page, then tap \u201cTry again\u201d here.',
    locGuideDesktop1: 'Click the lock (or tune) icon left of the address bar \u2192 Site settings \u2192 Location \u2192 Allow.',
    locGuideDesktop2: 'Reload the page, then tap \u201cTry again\u201d here.',
    micGuideIos1: 'Open iPhone Settings \u2192 find this browser \u2192 turn Microphone on.',
    micGuideIos2: 'Come back here and tap \u201cTry again\u201d.',
    micGuideAndroid1: 'Tap the lock (or tune) icon in the address bar \u2192 Permissions \u2192 Microphone \u2192 Allow.',
    micGuideAndroid2: 'Reload the page, then tap \u201cTry again\u201d here.',
    micGuideDesktop1: 'Click the lock (or tune) icon left of the address bar \u2192 Site settings \u2192 Microphone \u2192 Allow.',
    micGuideDesktop2: 'Reload the page, then tap \u201cTry again\u201d here.',
    ntfGuideIos1: 'Open iPhone Settings \u2192 Notifications \u2192 find this browser \u2192 Allow Notifications.',
    ntfGuideIos2: 'Note: background alerts need the app added to your Home Screen first.',
    ntfGuideAndroid1: 'Tap the lock (or tune) icon in the address bar \u2192 Permissions \u2192 Notifications \u2192 Allow.',
    ntfGuideAndroid2: 'On some phones also check Android Settings \u2192 Apps \u2192 this browser \u2192 Notifications.',
    ntfGuideDesktop1: 'Click the lock (or tune) icon left of the address bar \u2192 Site settings \u2192 Notifications \u2192 Allow.',
    ntfGuideDesktop2: 'Reload the page, then tap \u201cAllow\u201d here.',
    sndGuide1: 'Turn your device volume up and take it off silent / Do Not Disturb.',
    sndGuide2: 'In the browser, make sure this tab is not muted (right-click the tab).',
    sndGuide3: 'Use the switch above for SAARTHI\u2019s own sounds.',
  },
  hi: {
    navSections: 'अनुभाग',
    locAuto: 'स्वतः पहचाना गया',
    chatRegion: 'बातचीत',
    disasterBanner: 'आपदा मोड — सत्यापित गंभीर चेतावनी सक्रिय। पहले सुरक्षा, फिर संचार।',
    boundaryTitle: 'यह स्क्रीन नहीं दिख सकी',
    boundaryBody: 'बाकी ऐप चलता रहेगा। जगह भरने के लिए कुछ गढ़ा नहीं गया।',
    srcStatusTitle: 'डेटा स्रोत',
    srcStatusSub: 'हर स्रोत अपनी स्थिति बताता है। जो लाइव नहीं है उसे LIVE नहीं कहा जाता।',
    ntfUnread: 'अपठित',
    alertsGroup: 'अलर्ट',
    p2pSimTitle: 'नकली मेश — असली रेडियो पथ नहीं',
    p2pOutbox: 'भेजने के लिए रखे संदेश',
    // --- settings: profile + permissions control center (Crew G) ---
    setProfile: 'आपकी प्रोफ़ाइल',
    setRoleNote: 'अपनी भूमिका एक बार चुनें — होम, चैट और सलाह सब उसी के अनुसार बदलेंगे।',
    setRoleGo: 'Advisory में भूमिका चुनें',
    setPlaceNote: 'होम हीरो पर अपना जिला लिखें, या यहाँ GPS इस्तेमाल करें।',
    setPermTitle: 'अनुमतियाँ',
    setPermSub: 'SAARTHI क्या-क्या इस्तेमाल कर सकता है। कभी भी बदलें — यहाँ कुछ भी स्थायी नहीं है।',
    permLocT: 'स्थान',
    permLocD: 'स्थानीय चेतावनियों के लिए आपका जिला पहचानता है।',
    permMicT: 'माइक्रोफ़ोन',
    permMicD: 'आपको आवाज़ से सवाल पूछने देता है।',
    permSndT: 'आवाज़',
    permSndD: 'ऐप में बोले गए उत्तर और अलर्ट की आवाज़।',
    permNtfT: 'सूचनाएँ',
    permNtfD: 'ऐप बंद होने पर भी चेतावनी देता है।',
    permGranted: 'अनुमति है',
    permDenied: 'अवरुद्ध',
    permPrompt: 'अभी नहीं पूछा',
    permUnknown: 'जाँच नहीं हो सकी',
    permUnavailable: 'इस डिवाइस पर उपलब्ध नहीं',
    permOn: 'चालू',
    permOff: 'बंद',
    permWorking: 'जाँच रहे हैं…',
    permAllow: 'अनुमति दें',
    permRetry: 'फिर कोशिश करें',
    permHow: 'अनुमति कैसे दें',
    permHide: 'छिपाएँ',
    setSoundNote: 'यहाँ बंद करने से SAARTHI के बोले गए उत्तर बंद होंगे। डिवाइस की आवाज़ अलग है।',
    locOpenSettings: 'सेटिंग खोलें',
    locGuideIos1: 'iPhone की सेटिंग खोलें, यह ब्राउज़र (या SAARTHI) खोजें, और स्थान को \u201cइस्तेमाल के दौरान\u201d पर सेट करें।',
    locGuideIos2: 'वापस आकर \u201cफिर कोशिश करें\u201d दबाएँ।',
    locGuideAndroid1: 'एड्रेस बार में ताले (या ट्यून) के निशान पर टैप करें \u2192 अनुमतियाँ \u2192 स्थान \u2192 अनुमति दें।',
    locGuideAndroid2: 'पेज दोबारा लोड करें, फिर यहाँ \u201cफिर कोशिश करें\u201d दबाएँ।',
    locGuideDesktop1: 'एड्रेस बार के बाईं ओर ताले (या ट्यून) के निशान पर क्लिक करें \u2192 साइट सेटिंग \u2192 स्थान \u2192 अनुमति दें।',
    locGuideDesktop2: 'पेज दोबारा लोड करें, फिर यहाँ \u201cफिर कोशिश करें\u201d दबाएँ।',
    micGuideIos1: 'iPhone की सेटिंग \u2192 यह ब्राउज़र खोजें \u2192 माइक्रोफ़ोन चालू करें।',
    micGuideIos2: 'वापस आकर \u201cफिर कोशिश करें\u201d दबाएँ।',
    micGuideAndroid1: 'एड्रेस बार में ताले (या ट्यून) के निशान पर टैप करें \u2192 अनुमतियाँ \u2192 माइक्रोफ़ोन \u2192 अनुमति दें।',
    micGuideAndroid2: 'पेज दोबारा लोड करें, फिर यहाँ \u201cफिर कोशिश करें\u201d दबाएँ।',
    micGuideDesktop1: 'एड्रेस बार के बाईं ओर ताले (या ट्यून) के निशान पर क्लिक करें \u2192 साइट सेटिंग \u2192 माइक्रोफ़ोन \u2192 अनुमति दें।',
    micGuideDesktop2: 'पेज दोबारा लोड करें, फिर यहाँ \u201cफिर कोशिश करें\u201d दबाएँ।',
    ntfGuideIos1: 'iPhone की सेटिंग \u2192 सूचनाएँ \u2192 यह ब्राउज़र खोजें \u2192 सूचनाओं की अनुमति दें।',
    ntfGuideIos2: 'ध्यान दें: बैकग्राउंड अलर्ट के लिए ऐप को पहले होम स्क्रीन पर जोड़ना ज़रूरी है।',
    ntfGuideAndroid1: 'एड्रेस बार में ताले (या ट्यून) के निशान पर टैप करें \u2192 अनुमतियाँ \u2192 सूचनाएँ \u2192 अनुमति दें।',
    ntfGuideAndroid2: 'कुछ फ़ोन में Android सेटिंग \u2192 ऐप्स \u2192 यह ब्राउज़र \u2192 सूचनाएँ भी जाँचें।',
    ntfGuideDesktop1: 'एड्रेस बार के बाईं ओर ताले (या ट्यून) के निशान पर क्लिक करें \u2192 साइट सेटिंग \u2192 सूचनाएँ \u2192 अनुमति दें।',
    ntfGuideDesktop2: 'पेज दोबारा लोड करें, फिर यहाँ \u201cअनुमति दें\u201d दबाएँ।',
    sndGuide1: 'डिवाइस की आवाज़ बढ़ाएँ और साइलेंट / डू नॉट डिस्टर्ब हटाएँ।',
    sndGuide2: 'ब्राउज़र में यह टैब म्यूट तो नहीं है — टैब पर राइट-क्लिक करके देखें।',
    sndGuide3: 'SAARTHI की अपनी आवाज़ के लिए ऊपर वाला स्विच इस्तेमाल करें।',
  },
  te: {
    navSections: 'విభాగాలు',
    locAuto: 'స్వయంగా గుర్తించబడింది',
    chatRegion: 'సంభాషణ',
    disasterBanner: 'విపత్తు మోడ్ — ధృవీకరించిన తీవ్ర హెచ్చరిక క్రియాశీలం. ముందు భద్రత, తర్వాత సంభాషణ.',
    boundaryTitle: 'ఈ తెర చూపించలేకపోయాం',
    boundaryBody: 'మిగిలిన యాప్ పనిచేస్తూనే ఉంటుంది. ఖాళీ నింపడానికి ఏదీ కల్పించలేదు.',
    srcStatusTitle: 'డేటా మూలాలు',
    srcStatusSub: 'ప్రతి మూలం తన స్థితిని తెలియజేస్తుంది. లైవ్ కానిది LIVE అని చూపము.',
    ntfUnread: 'చదవని',
    alertsGroup: 'అలర్ట్‌లు',
    p2pSimTitle: 'అనుకరణ మెష్ — నిజమైన రేడియో మార్గం కాదు',
    p2pOutbox: 'పంపడానికి ఉన్న సందేశాలు',
    // --- settings: profile + permissions control center (Crew G) ---
    setProfile: 'మీ ప్రొఫైల్',
    setRoleNote: 'మీ పాత్రను ఒకసారి ఎంచుకోండి — హోమ్, చాట్, సలహా అన్నీ దాని ప్రకారం మారతాయి.',
    setRoleGo: 'Advisoryలో పాత్రను ఎంచుకోండి',
    setPlaceNote: 'హోమ్ హీరోపై మీ జిల్లాను టైప్ చేయండి, లేదా ఇక్కడ GPS వాడండి.',
    setPermTitle: 'అనుమతులు',
    setPermSub: 'SAARTHI ఏమి వాడవచ్చు. ఎప్పుడైనా మార్చండి — ఇక్కడ ఏదీ శాశ్వతం కాదు.',
    permLocT: 'స్థానం',
    permLocD: 'స్థానిక హెచ్చరికల కోసం మీ జిల్లాను గుర్తిస్తుంది.',
    permMicT: 'మైక్రోఫోన్',
    permMicD: 'మీరు వాయిస్‌తో ప్రశ్నలు అడగడానికి వీలు కల్పిస్తుంది.',
    permSndT: 'శబ్దం',
    permSndD: 'యాప్‌లో మాట్లాడే సమాధానాలు, హెచ్చరిక శబ్దాలు.',
    permNtfT: 'నోటిఫికేషన్లు',
    permNtfD: 'యాప్ మూసినా హెచ్చరిస్తుంది.',
    permGranted: 'అనుమతించబడింది',
    permDenied: 'నిరోధించబడింది',
    permPrompt: 'ఇంకా అడగలేదు',
    permUnknown: 'తనిఖీ చేయలేకపోయాం',
    permUnavailable: 'ఈ పరికరంలో అందుబాటులో లేదు',
    permOn: 'ఆన్',
    permOff: 'ఆఫ్',
    permWorking: 'తనిఖీ చేస్తున్నాం…',
    permAllow: 'అనుమతించండి',
    permRetry: 'మళ్లీ ప్రయత్నించండి',
    permHow: 'ఎలా అనుమతించాలి',
    permHide: 'దాచండి',
    setSoundNote: 'ఇక్కడ ఆఫ్ చేస్తే SAARTHI మాట్లాడే సమాధానాలు ఆగుతాయి. పరికర వాల్యూమ్ వేరు.',
    locOpenSettings: 'సెట్టింగ్‌లు తెరవండి',
    locGuideIos1: 'iPhone సెట్టింగ్‌లు తెరిచి, ఈ బ్రౌజర్ (లేదా SAARTHI) కనుగొని, స్థానాన్ని \u201cవాడుతున్నప్పుడు\u201d గా సెట్ చేయండి.',
    locGuideIos2: 'తిరిగి వచ్చి \u201cమళ్లీ ప్రయత్నించండి\u201d నొక్కండి.',
    locGuideAndroid1: 'అడ్రస్ బార్‌లో తాళం (లేదా ట్యూన్) గుర్తును నొక్కండి \u2192 అనుమతులు \u2192 స్థానం \u2192 అనుమతించండి.',
    locGuideAndroid2: 'పేజీని మళ్లీ లోడ్ చేసి, ఇక్కడ \u201cమళ్లీ ప్రయత్నించండి\u201d నొక్కండి.',
    locGuideDesktop1: 'అడ్రస్ బార్ ఎడమవైపు తాళం (లేదా ట్యూన్) గుర్తును క్లిక్ చేయండి \u2192 సైట్ సెట్టింగ్‌లు \u2192 స్థానం \u2192 అనుమతించండి.',
    locGuideDesktop2: 'పేజీని మళ్లీ లోడ్ చేసి, ఇక్కడ \u201cమళ్లీ ప్రయత్నించండి\u201d నొక్కండి.',
    micGuideIos1: 'iPhone సెట్టింగ్‌లు \u2192 ఈ బ్రౌజర్‌ను కనుగొనండి \u2192 మైక్రోఫోన్ ఆన్ చేయండి.',
    micGuideIos2: 'తిరిగి వచ్చి \u201cమళ్లీ ప్రయత్నించండి\u201d నొక్కండి.',
    micGuideAndroid1: 'అడ్రస్ బార్‌లో తాళం (లేదా ట్యూన్) గుర్తును నొక్కండి \u2192 అనుమతులు \u2192 మైక్రోఫోన్ \u2192 అనుమతించండి.',
    micGuideAndroid2: 'పేజీని మళ్లీ లోడ్ చేసి, ఇక్కడ \u201cమళ్లీ ప్రయత్నించండి\u201d నొక్కండి.',
    micGuideDesktop1: 'అడ్రస్ బార్ ఎడమవైపు తాళం (లేదా ట్యూన్) గుర్తును క్లిక్ చేయండి \u2192 సైట్ సెట్టింగ్‌లు \u2192 మైక్రోఫోన్ \u2192 అనుమతించండి.',
    micGuideDesktop2: 'పేజీని మళ్లీ లోడ్ చేసి, ఇక్కడ \u201cమళ్లీ ప్రయత్నించండి\u201d నొక్కండి.',
    ntfGuideIos1: 'iPhone సెట్టింగ్‌లు \u2192 నోటిఫికేషన్లు \u2192 ఈ బ్రౌజర్‌ను కనుగొనండి \u2192 నోటిఫికేషన్లను అనుమతించండి.',
    ntfGuideIos2: 'గమనిక: బ్యాక్‌గ్రౌండ్ హెచ్చరికలకు ముందు యాప్‌ను హోమ్ స్క్రీన్‌కు జోడించాలి.',
    ntfGuideAndroid1: 'అడ్రస్ బార్‌లో తాళం (లేదా ట్యూన్) గుర్తును నొక్కండి \u2192 అనుమతులు \u2192 నోటిఫికేషన్లు \u2192 అనుమతించండి.',
    ntfGuideAndroid2: 'కొన్ని ఫోన్లలో Android సెట్టింగ్‌లు \u2192 యాప్‌లు \u2192 ఈ బ్రౌజర్ \u2192 నోటిఫికేషన్లు కూడా చూడండి.',
    ntfGuideDesktop1: 'అడ్రస్ బార్ ఎడమవైపు తాళం (లేదా ట్యూన్) గుర్తును క్లిక్ చేయండి \u2192 సైట్ సెట్టింగ్‌లు \u2192 నోటిఫికేషన్లు \u2192 అనుమతించండి.',
    ntfGuideDesktop2: 'పేజీని మళ్లీ లోడ్ చేసి, ఇక్కడ \u201cఅనుమతించండి\u201d నొక్కండి.',
    sndGuide1: 'పరికర వాల్యూమ్ పెంచండి, సైలెంట్ / డూ నాట్ డిస్టర్బ్ తీసివేయండి.',
    sndGuide2: 'బ్రౌజర్‌లో ఈ ట్యాబ్ మ్యూట్ కాలేదని చూడండి — ట్యాబ్‌పై రైట్ క్లిక్ చేయండి.',
    sndGuide3: 'SAARTHI సొంత శబ్దాల కోసం పైన ఉన్న స్విచ్ వాడండి.',
  },
};
