// City operations panel (Trust route) — district heat / rain / official alerts.
// EN / HI / TE parity is a ship gate — every key below must exist in all three.
// This panel is FACTS ONLY: measured numbers and official alert counts, never
// advice, never invented severities. AQI has no adapter behind it, so no AQI
// key exists here at all — it is omitted, never faked.
export default {
  en: {
    cityOpsTitle: 'City operations',
    cityOpsSub: 'Measured heat, rain and official alerts for this district. Facts only — no advice here.',
    cityHeat: 'Heat',
    cityHeatNow: 'Temperature now',
    cityHeatMax: "Today's high",
    cityRain: 'Rain',
    cityRainObs: 'Rainfall, last check',
    cityRainFcst: 'Forecast rain today',
    cityAlerts: 'Official alerts',
    cityAlertsNone: 'No active official alerts for this district.',
    cityAlertsActive: '{n} active for {district}',
    cityAlertsSevNote: 'Severity is shown exactly as the official feed sent it.',
    cityUnavailable: 'Not available',
    cityLoading: 'Checking conditions…',
    cityFailed: "Couldn't reach the server. Retry when you're back online.",
    cityRetry: 'Try again',
  },
  hi: {
    cityOpsTitle: 'शहर की स्थिति',
    cityOpsSub: 'इस जिले के लिए मापा गया तापमान, बारिश और सरकारी चेतावनियाँ। सिर्फ तथ्य — यहाँ कोई सलाह नहीं।',
    cityHeat: 'गर्मी',
    cityHeatNow: 'अभी का तापमान',
    cityHeatMax: 'आज का अधिकतम तापमान',
    cityRain: 'बारिश',
    cityRainObs: 'बारिश, पिछली जाँच',
    cityRainFcst: 'आज की अनुमानित बारिश',
    cityAlerts: 'सरकारी चेतावनियाँ',
    cityAlertsNone: 'इस जिले के लिए अभी कोई सक्रिय सरकारी चेतावनी नहीं है।',
    cityAlertsActive: '{district} में {n} सक्रिय',
    cityAlertsSevNote: 'गंभीरता बिल्कुल वैसी ही दिखाई गई है जैसी सरकारी फ़ीड ने भेजी है।',
    cityUnavailable: 'अभी उपलब्ध नहीं',
    cityLoading: 'स्थिति जाँची जा रही है…',
    cityFailed: 'सर्वर से संपर्क नहीं हो सका। ऑनलाइन आने पर दोबारा कोशिश करें।',
    cityRetry: 'दोबारा कोशिश करें',
  },
  te: {
    cityOpsTitle: 'నగర పరిస్థితి',
    cityOpsSub: 'ఈ జిల్లా కోసం కొలిచిన ఉష్ణోగ్రత, వర్షం మరియు అధికారిక హెచ్చరికలు. కేవలం వాస్తవాలు మాత్రమే — ఇక్కడ సలహాలు లేవు.',
    cityHeat: 'వేడి',
    cityHeatNow: 'ప్రస్తుత ఉష్ణోగ్రత',
    cityHeatMax: 'నేటి గరిష్ఠ ఉష్ణోగ్రత',
    cityRain: 'వర్షం',
    cityRainObs: 'వర్షపాతం, చివరి తనిఖీ',
    cityRainFcst: 'నేటి అంచనా వర్షపాతం',
    cityAlerts: 'అధికారిక హెచ్చరికలు',
    cityAlertsNone: 'ఈ జిల్లా కోసం ప్రస్తుతం క్రియాశీల అధికారిక హెచ్చరికలు లేవు.',
    cityAlertsActive: '{district} లో {n} క్రియాశీలం',
    cityAlertsSevNote: 'తీవ్రత అధికారిక ఫీడ్ పంపిన విధంగానే చూపబడుతుంది.',
    cityUnavailable: 'ప్రస్తుతం అందుబాటులో లేదు',
    cityLoading: 'పరిస్థితులు తనిఖీ చేయబడుతున్నాయి…',
    cityFailed: 'సర్వర్‌ను చేరుకోలేకపోయాం. ఆన్‌లైన్‌కు వచ్చాక మళ్లీ ప్రయత్నించండి.',
    cityRetry: 'మళ్లీ ప్రయత్నించండి',
  },
};
