// Shared chrome strings.
export default {
  en: {
    appName: 'SAARTHI',
    tagline: 'Know your sky. Stay safe.',
    navHome: 'Home',
    navAlerts: 'Alerts',
    navAdvice: 'My advice',
    navMore: 'More',
    retry: 'Try again',
    close: 'Close',
    cancel: 'Cancel',
    loading: 'Loading…',
    loadError: "Couldn't load this. Check your connection and try again.",
    updatedAgo: 'Updated {t} ago',
    updatedJustNow: 'Updated just now',
    justNow: 'just now',
    minAgo: '{n} min',
    hrAgo: '{n} hr',
    basedOn: 'Based on {s}',
    imdFirst: 'IMD first · backfills on',
    stLive: 'Live',
    stCached: 'Cached',
    stUnconfigured: 'Not set up',
    stOffline: 'Offline',
    stError: 'Error',
    stReady: 'Ready',
    listen: 'Listen',
    stopListen: 'Stop',
    sos: 'SOS',
    ok: 'OK',
  },
  hi: {
    appName: 'SAARTHI',
    tagline: 'अपना आसमान जानें। सुरक्षित रहें।',
    navHome: 'होम',
    navAlerts: 'अलर्ट',
    navAdvice: 'मेरी सलाह',
    navMore: 'अधिक',
    retry: 'पुनः प्रयास करें',
    close: 'बंद करें',
    cancel: 'रद्द करें',
    loading: 'लोड हो रहा है…',
    loadError: 'लोड नहीं हो सका। कनेक्शन जाँचें और पुनः प्रयास करें।',
    updatedAgo: '{t} पहले अपडेट हुआ',
    updatedJustNow: 'अभी अपडेट हुआ',
    justNow: 'अभी',
    minAgo: '{n} मिनट',
    hrAgo: '{n} घंटे',
    basedOn: '{s} पर आधारित',
    imdFirst: 'IMD पहले · बैकफ़िल चालू',
    stLive: 'लाइव',
    stCached: 'कैश्ड',
    stUnconfigured: 'सेट नहीं है',
    stOffline: 'ऑफ़लाइन',
    stError: 'त्रुटि',
    stReady: 'तैयार',
    listen: 'सुनें',
    stopListen: 'रोकें',
    sos: 'SOS',
    ok: 'ठीक है',
  },
  te: {
    appName: 'SAARTHI',
    tagline: 'మీ ఆకాశాన్ని తెలుసుకోండి. సురక్షితంగా ఉండండి.',
    navHome: 'హోమ్',
    navAlerts: 'హెచ్చరికలు',
    navAdvice: 'నా సలహా',
    navMore: 'మరిన్ని',
    retry: 'మళ్లీ ప్రయత్నించండి',
    close: 'మూసివేయండి',
    cancel: 'రద్దు చేయండి',
    loading: 'లోడ్ అవుతోంది…',
    loadError: 'లోడ్ కాలేదు. కనెక్షన్ చూసి మళ్లీ ప్రయత్నించండి.',
    updatedAgo: '{t} క్రితం నవీకరించబడింది',
    updatedJustNow: 'ఇప్పుడే నవీకరించబడింది',
    justNow: 'ఇప్పుడే',
    minAgo: '{n} నిమిషాలు',
    hrAgo: '{n} గంటలు',
    basedOn: '{s} ఆధారంగా',
    imdFirst: 'IMD మొదట · బ్యాక్‌ఫిల్ ఆన్',
    stLive: 'లైవ్',
    stCached: 'క్యాష్',
    stUnconfigured: 'సెటప్ చేయలేదు',
    stOffline: 'ఆఫ్‌లైన్',
    stError: 'లోపం',
    stReady: 'సిద్ధం',
    listen: 'వినండి',
    stopListen: 'ఆపండి',
    sos: 'SOS',
    ok: 'సరే',
  },
};
