// Harbour Signal redesign strings: new keys for the v3 rebuild.
// EN / HI / TE parity is a ship gate — every key below must exist in all three.
export default {
  en: {
    // Role honesty (M1): never silently default a safety-relevant persona.
    roleNotSet: 'Not set — pick your role',
    rolePickCta: 'Pick your role',
    // SOS console (B5, minors).
    sendSosTitle: 'Send SOS',
    sosArmedFire: 'Tap again to send',
    sosSending: 'Sending…',
    emgPeopleWithYou: 'People with you',
    emgMedicalNeed: 'Medical help needed',
    emgSessionScope: 'Showing messages sent from this phone, this demo.',
    emgClearSession: 'Clear messages (this demo)',
    // Notifications offline honesty (B3).
    ntfOfflineTitle: "Couldn't reach the server",
    ntfOfflineBody: "Showing what's saved on this phone.",
    ntfSavedTag: 'Saved on this phone',
    ntfRetry: 'Retry',
    ntfSimulatedTag: 'SIMULATED — FOR DEMO ONLY',
    // P2P relay states.
    p2pIdleHint: 'Send a message above, then tap Demo relay to watch it hop phone to phone.',
    p2pSending: 'Relaying…',
    p2pRelayed: 'Relayed (simulated) — see Notifications',
    p2pFailed: "Couldn't relay — try again",
    p2pRelayAlert: 'Relay via P2P',
    p2pRelayedAlert: 'Relayed (simulated)',
    // Trust / Sources two-tier copy (M5).
    srcWhy: 'Why?',
    srcLineLive: '{name} — sending live data',
    srcLineDemo: '{name} — demo data for the pitch',
    srcLineUnconfigured: '{name} — not connected yet',
    srcLineOffline: '{name} — unreachable right now',
    srcLineCached: '{name} — showing saved data',
    srcLineReady: '{name} — ready',
    viewSourcesSub: 'Where every fact on this board comes from, and whether the line is live.',
    // Home district honesty (M3).
    noDistrict: 'No district set',
    noDistrictHint: 'Pick your district below so we can check for warnings.',
    // Ask offline queue (B4): the waiting state, in plain words.
    queuedWaiting: 'Waiting for network — will answer when you are back online.',
    offlineNewWarning: 'New warnings cannot be checked while offline. CANNOT CHECK NOW — we cannot say it is safe.',
    offlineCachedTag: 'Saved guidance',
    offlineNoAnswer: 'Offline: I can answer from saved emergency guidance (flood, thunderstorm, heatwave, cyclone). CANNOT CHECK NOW — we cannot say it is safe.',
    trustTechWhy: 'Technical detail',
    offlineVerdictDetail: 'Offline — warning status cannot be checked. CANNOT CHECK NOW — we cannot say it is safe.',
    // Advisory offline honesty.
    adviceOfflineTitle: "Couldn't load guidance",
    adviceOfflineBody: 'The server is unreachable. Your role and district are saved — retry when you are back online, or ask a question (it will queue).',
    adviceRetry: 'Try again',
  },
  hi: {
    roleNotSet: 'तय नहीं — अपनी भूमिका चुनें',
    rolePickCta: 'भूमिका चुनें',
    sendSosTitle: 'SOS भेजें',
    sosArmedFire: 'भेजने के लिए फिर दबाएँ',
    sosSending: 'भेजा जा रहा…',
    emgPeopleWithYou: 'आपके साथ लोग',
    emgMedicalNeed: 'चिकित्सा सहायता चाहिए',
    emgSessionScope: 'इस फ़ोन से, इस डेमो में भेजे गए संदेश दिख रहे हैं।',
    emgClearSession: 'संदेश साफ़ करें (यह डेमो)',
    ntfOfflineTitle: 'सर्वर से संपर्क नहीं हुआ',
    ntfOfflineBody: 'इस फ़ोन में सहेजी हुई सूची दिख रही है।',
    ntfSavedTag: 'फ़ोन में सहेजा',
    ntfRetry: 'फिर कोशिश करें',
    ntfSimulatedTag: 'SIMULATED — FOR DEMO ONLY',
    p2pIdleHint: 'ऊपर संदेश भेजें, फिर डेमो रिले दबाकर देखें कि वह फ़ोन से फ़ोन तक कैसे जाता है।',
    p2pSending: 'रिले हो रहा…',
    p2pRelayed: 'रिले हुआ (नकली) — सूचनाएँ देखें',
    p2pFailed: 'रिले नहीं हुआ — फिर कोशिश करें',
    p2pRelayAlert: 'P2P से भेजें',
    p2pRelayedAlert: 'रिले हुआ (नकली)',
    srcWhy: 'क्यों?',
    srcLineLive: '{name} — लाइव डेटा भेज रहा है',
    srcLineDemo: '{name} — डेमो के लिए नमूना डेटा',
    srcLineUnconfigured: '{name} — अभी जुड़ा नहीं है',
    srcLineOffline: '{name} — अभी पहुँच से बाहर है',
    srcLineCached: '{name} — सहेजा डेटा दिख रहा है',
    srcLineReady: '{name} — तैयार',
    viewSourcesSub: 'इस बोर्ड का हर तथ्य कहाँ से आता है, और लाइन चालू है या नहीं।',
    noDistrict: 'जिला तय नहीं',
    noDistrictHint: 'चेतावनी जाँचने के लिए नीचे अपना जिला चुनें।',
    queuedWaiting: 'नेटवर्क का इंतज़ार — ऑनलाइन आते ही जवाब मिलेगा।',
    offlineNewWarning: 'ऑफ़लाइन में नई चेतावनी जाँची नहीं जा सकती। अभी जाँच नहीं हो सकती — हम यह नहीं कह सकते कि सुरक्षित है।',
    offlineCachedTag: 'सहेजी हुई सलाह',
    offlineNoAnswer: 'ऑफ़लाइन: सहेजी आपात सलाह (बाढ़, आँधी, लू, चक्रवात) से उत्तर दे सकता हूँ। अभी जाँच नहीं हो सकती — हम यह नहीं कह सकते कि सुरक्षित है।',
    trustTechWhy: 'तकनीकी विवरण',
    offlineVerdictDetail: 'ऑफ़लाइन — चेतावनी की स्थिति जाँची नहीं जा सकती। अभी जाँच नहीं हो सकती — हम यह नहीं कह सकते कि सुरक्षित है।',
    adviceOfflineTitle: 'सलाह नहीं मिल सकी',
    adviceOfflineBody: 'सर्वर से संपर्क नहीं हुआ। आपकी भूमिका और जिला सहेजे हैं — ऑनलाइन आकर फिर कोशिश करें, या सवाल पूछें (वह कतार में रहेगा)।',
    adviceRetry: 'फिर कोशिश करें',
  },
  te: {
    roleNotSet: 'ఎంచుకోలేదు — మీ పాత్రను ఎంచుకోండి',
    rolePickCta: 'పాత్రను ఎంచుకోండి',
    sendSosTitle: 'SOS పంపండి',
    sosArmedFire: 'పంపడానికి మళ్లీ నొక్కండి',
    sosSending: 'పంపబడుతోంది…',
    emgPeopleWithYou: 'మీతో ఉన్నవారు',
    emgMedicalNeed: 'వైద్య సహాయం కావాలి',
    emgSessionScope: 'ఈ ఫోన్ నుండి, ఈ డెమోలో పంపిన సందేశాలు చూపుతున్నాం.',
    emgClearSession: 'సందేశాలను తొలగించండి (ఈ డెమో)',
    ntfOfflineTitle: 'సర్వర్‌ను చేరుకోలేకపోయాం',
    ntfOfflineBody: 'ఈ ఫోన్‌లో భద్రపరిచిన జాబితా చూపుతున్నాం.',
    ntfSavedTag: 'ఫోన్‌లో భద్రం',
    ntfRetry: 'మళ్లీ ప్రయత్నించండి',
    ntfSimulatedTag: 'SIMULATED — FOR DEMO ONLY',
    p2pIdleHint: 'పైన సందేశం పంపి, డెమో రిలే నొక్కి అది ఫోన్ నుండి ఫోన్‌కు ఎలా వెళ్తుందో చూడండి.',
    p2pSending: 'రిలే అవుతోంది…',
    p2pRelayed: 'రిలే అయింది (నకిలీ) — నోటిఫికేషన్లు చూడండి',
    p2pFailed: 'రిలే కాలేదు — మళ్లీ ప్రయత్నించండి',
    p2pRelayAlert: 'P2P ద్వారా పంపండి',
    p2pRelayedAlert: 'రిలే అయింది (నకిలీ)',
    srcWhy: 'ఎందుకు?',
    srcLineLive: '{name} — ప్రత్యక్ష డేటా పంపుతోంది',
    srcLineDemo: '{name} — డెమో కోసం నమూనా డేటా',
    srcLineUnconfigured: '{name} — ఇంకా కనెక్ట్ కాలేదు',
    srcLineOffline: '{name} — ప్రస్తుతం అందుబాటులో లేదు',
    srcLineCached: '{name} — భద్రపరిచిన డేటా చూపుతోంది',
    srcLineReady: '{name} — సిద్ధం',
    viewSourcesSub: 'ఈ బోర్డులోని ప్రతి వాస్తవం ఎక్కడి నుండి వస్తుందో, లైన్ పనిచేస్తోందో లేదో.',
    noDistrict: 'జిల్లా ఎంచుకోలేదు',
    noDistrictHint: 'హెచ్చరికలను తనిఖీ చేయడానికి కింద మీ జిల్లాను ఎంచుకోండి.',
    queuedWaiting: 'నెట్‌వర్క్ కోసం వేచి ఉంది — మీరు ఆన్‌లైన్‌కు వచ్చాక సమాధానం ఇస్తుంది.',
    offlineNewWarning: 'ఆఫ్‌లైన్‌లో కొత్త హెచ్చరికలను తనిఖీ చేయలేము. ఇప్పుడు తనిఖీ చేయలేము — సురక్షితం అని చెప్పలేము.',
    offlineCachedTag: 'భద్రపరిచిన సూచన',
    offlineNoAnswer: 'ఆఫ్‌లైన్: భద్రపరిచిన అత్యవసర సూచనల (వరద, ఉరుము, ఎండగాలులు, తుఫాను) నుండి సమాధానం ఇవ్వగలను. ఇప్పుడు తనిఖీ చేయలేము — సురక్షితం అని చెప్పలేము.',
    trustTechWhy: 'సాంకేతిక వివరాలు',
    offlineVerdictDetail: 'ఆఫ్‌లైన్ — హెచ్చరిక స్థితిని తనిఖీ చేయలేము. ఇప్పుడు తనిఖీ చేయలేము — సురక్షితం అని చెప్పలేము.',
    adviceOfflineTitle: 'సూచనలు రాలేదు',
    adviceOfflineBody: 'సర్వర్‌ను చేరుకోలేకపోయాం. మీ పాత్ర, జిల్లా భద్రంగా ఉన్నాయి — ఆన్‌లైన్‌కు వచ్చాక మళ్లీ ప్రయత్నించండి, లేదా ప్రశ్న అడగండి (అది క్యూలో ఉంటుంది).',
    adviceRetry: 'మళ్లీ ప్రయత్నించండి',
  },
};
