// HomeChat strings: the Home-screen chat board (Ask merged into Home).
//
// The chat answers from official warnings and live data AND gives advice for
// the user's role and profile (2026-10-10: facts-only left people without an
// answer to "can I spray / go to sea?"). The copy says plainly that advice is
// the app's guidance, never an official order. "Open My advice" still leads to
// the full checklist on Advisory.
export default {
  en: {
    hcRegion: 'Ask SAARTHI',
    hcFactsTitle: 'Answers and advice for you',
    hcFactsBody: 'Answers come from official warnings and live weather data, with advice for your role and profile. Advice is guidance from the app, not an official order — always follow IMD and local officials.',
    hcFactsEscape: 'Want the full checklist? Open My advice',
    hcFactsMore: 'About this chat',
    hcFactsClose: 'Close',
    hcAs: 'Answering as',
    hcComposerHint: 'Ask about weather, rain, warnings…',
    hcSend: 'Send',
    hcMicHint: 'Speak your question',
    hcQueuedChip: 'Queued',
    hcQueuedText: 'Waiting for network — will answer when you are back online',
    hcFallbackChip: 'Rule-based reply',
    hcFallbackText: 'Rule-based reply from the same verified data — the AI wording was not used as-is',
    hcListen: 'Listen',
    hcStopListen: 'Stop',
    hcSpeaking: 'Speaking…',
    hcBasedOn: 'Based on',
    hcBasedOnSaved: 'saved on this phone',
    hcAskAboutThis: 'Ask about this',
    hcOpenAdvisory: 'Open My advice',
    hcComposing: 'Generating...',
    hcSuggestionsHint: 'Try one',
    hcReadMore: 'Read more',
    hcReadLess: 'Show less',
    hcEmptyLine: 'Ask about your work or plans — you get the facts and what to do.',
    // --- Crew B (voice-first rebuild, 2026-09-21): voice-UX states ----------
    // Exact screen copy, per the voice-UX spec: the mic button tap lands on
    // "Listening...", a pause/finalize lands on "Understanding your text...",
    // and the send lands on "Generating...".
    hcListening: 'Listening...',
    hcUnderstanding: 'Understanding your text...',
    hcMicPermission: 'Waiting for mic permission…',
    hcMicStop: 'Stop listening',
    hcMicBlockedTitle: 'Mic is blocked',
    hcMicBlockedBody: 'The browser blocked the microphone, so I cannot hear you. Allow the mic to speak your question — or type it instead.',
    hcMicBlockedOpen: 'Open Settings',
    // --- Worker 3 (home-ask-focus, 2026-09-21): Ask is the hero of Home -----
    askHeroTitle: 'Ask about your weather',
    askHeroSub: 'Answers and advice for you — type or speak.',
  },
  hi: {
    hcRegion: 'SAARTHI से पूछें',
    hcFactsTitle: 'आपके लिए उत्तर और सलाह',
    hcFactsBody: 'उत्तर आधिकारिक बुलेटिनों से आते हैं। मैं अंदाज़ा नहीं लगाता, और यहाँ सलाह नहीं देता।',
    hcFactsEscape: 'पूरी सूची चाहिए? मेरी सलाह खोलें',
    hcFactsMore: 'इस चैट के बारे में',
    hcFactsClose: 'बंद करें',
    hcAs: 'उत्तर दे रहा है',
    hcComposerHint: 'मौसम, बारिश, चेतावनी पूछें…',
    hcSend: 'भेजें',
    hcMicHint: 'अपना सवाल बोलें',
    hcQueuedChip: 'कतारबद्ध',
    hcQueuedText: 'नेटवर्क का इंतज़ार — लौटते ही जवाब दूँगा',
    hcFallbackChip: 'नियम-आधारित उत्तर',
    hcFallbackText: 'उसी सत्यापित डेटा से नियमों द्वारा बना उत्तर — AI का लिखा उत्तर जैसा का तैसा नहीं लिया गया',
    hcListen: 'सुनें',
    hcStopListen: 'रोकें',
    hcSpeaking: 'बोल रहा है…',
    hcBasedOn: 'आधार',
    hcBasedOnSaved: 'इस फ़ोन में सहेजा',
    hcAskAboutThis: 'इसके बारे में पूछें',
    hcOpenAdvisory: 'मेरी सलाह खोलें',
    hcComposing: 'तैयार हो रहा है…',
    hcSuggestionsHint: 'एक आज़माएँ',
    hcReadMore: 'और पढ़ें',
    hcReadLess: 'छिपाएँ',
    hcEmptyLine: 'अपने काम या योजना के बारे में पूछें — तथ्य और क्या करना है, दोनों मिलेंगे।',
    // --- Crew B (voice-first rebuild, 2026-09-21): voice-UX states ----------
    hcListening: 'सुन रहा हूँ…',
    hcUnderstanding: 'आपका टेक्स्ट समझ रहा हूँ…',
    hcMicPermission: 'माइक अनुमति का इंतज़ार…',
    hcMicStop: 'सुनना बंद करें',
    hcMicBlockedTitle: 'माइक ब्लॉक है',
    hcMicBlockedBody: 'ब्राउज़र ने माइक्रोफ़ोन अवरुद्ध कर दिया है, इसलिए मैं आपको सुन नहीं सकता। सवाल बोलने के लिए माइक की अनुमति दें — या सवाल टाइप करें।',
    hcMicBlockedOpen: 'सेटिंग्स खोलें',
    // --- Worker 3 (home-ask-focus, 2026-09-21): Ask is the hero of Home -----
    askHeroTitle: 'अपने मौसम के बारे में पूछें',
    askHeroSub: 'आपके लिए उत्तर और सलाह — टाइप करें या बोलें।',
  },
  te: {
    hcRegion: 'SAARTHIని అడగండి',
    hcFactsTitle: 'మీ కోసం సమాధానాలు, సలహా',
    hcFactsBody: 'సమాధానాలు అధికారిక బులెటిన్ల నుండే వస్తాయి. నేను ఊహించను, ఇక్కడ సలహా ఇవ్వను.',
    hcFactsEscape: 'పూర్తి జాబితా కావాలా? నా సలహా తెరవండి',
    hcFactsMore: 'ఈ చాట్ గురించి',
    hcFactsClose: 'మూసివేయండి',
    hcAs: 'సమాధానం ఇస్తోంది',
    hcComposerHint: 'వాతావరణం, వర్షం, హెచ్చరికలు అడగండి…',
    hcSend: 'పంపండి',
    hcMicHint: 'మీ ప్రశ్న చెప్పండి',
    hcQueuedChip: 'క్యూలో ఉంది',
    hcQueuedText: 'నెట్‌వర్క్ కోసం వేచి — తిరిగి రాగానే సమాధానం ఇస్తాను',
    hcFallbackChip: 'నియమాల ఆధారిత జవాబు',
    hcFallbackText: 'అదే ధృవీకరించిన డేటా నుండి నియమాలతో రూపొందిన జవాబు — AI రాసిన జవాబును యథాతథంగా వాడలేదు',
    hcListen: 'వినండి',
    hcStopListen: 'ఆపండి',
    hcSpeaking: 'మాట్లాడుతోంది…',
    hcBasedOn: 'ఆధారం',
    hcBasedOnSaved: 'ఈ ఫోన్‌లో నిల్వ',
    hcAskAboutThis: 'దీని గురించి అడగండి',
    hcOpenAdvisory: 'నా సలహా తెరవండి',
    hcComposing: 'తయారవుతోంది…',
    hcSuggestionsHint: 'ఒకటి ప్రయత్నించండి',
    hcReadMore: 'మరింత చదవండి',
    hcReadLess: 'దాచండి',
    hcEmptyLine: 'మీ పని లేదా ప్రణాళిక గురించి అడగండి — వాస్తవాలు, ఏం చేయాలో రెండూ వస్తాయి.',
    // --- Crew B (voice-first rebuild, 2026-09-21): voice-UX states ----------
    hcListening: 'వింటున్నాను…',
    hcUnderstanding: 'మీ టెక్స్ట్ అర్థం చేసుకుంటున్నాను…',
    hcMicPermission: 'మైక్ అనుమతి కోసం వేచి…',
    hcMicStop: 'వినడం ఆపండి',
    hcMicBlockedTitle: 'మైక్ నిరోధించబడింది',
    hcMicBlockedBody: 'బ్రౌజర్ మైక్రోఫోన్‌ను నిరోధించింది, కాబట్టి మిమ్మల్ని వినలేను. ప్రశ్న చెప్పడానికి మైక్‌ను అనుమతించండి — లేదా టైప్ చేయండి.',
    hcMicBlockedOpen: 'సెట్టింగ్‌లు తెరవండి',
    // --- Worker 3 (home-ask-focus, 2026-09-21): Ask is the hero of Home -----
    askHeroTitle: 'మీ వాతావరణం గురించి అడగండి',
    askHeroSub: 'మీ కోసం సమాధానాలు, సలహా — టైప్ చేయండి లేదా మాట్లాడండి.',
  },
};
