// HomeChat strings: the Home-screen chat board (Ask merged into Home).
//
// Facts-only vocabulary: this chat answers from official bulletins and NEVER
// gives guidance. Every string here is a label, not advice — the one escape
// to guidance is the "Open My advice" pill, which navigates to Advisory.
export default {
  en: {
    hcRegion: 'Ask SAARTHI',
    hcFactsTitle: 'Facts only',
    hcFactsBody: 'Answers come from official bulletins. I never guess, and I never give advice here.',
    hcFactsEscape: 'Need guidance instead? Open My advice',
    hcFactsMore: 'About this chat',
    hcFactsClose: 'Close',
    hcAs: 'Answering as',
    hcComposerHint: 'Ask about weather, rain, warnings…',
    hcSend: 'Send',
    hcMicHint: 'Speak your question',
    hcQueuedChip: 'Queued',
    hcQueuedText: 'Waiting for network — will answer when you are back online',
    hcFallbackChip: 'Grounded fallback',
    hcFallbackText: 'Built from saved data — the live check did not finish',
    hcListen: 'Listen',
    hcStopListen: 'Stop',
    hcSpeaking: 'Speaking…',
    hcBasedOn: 'Based on',
    hcBasedOnSaved: 'saved on this phone',
    hcAskAboutThis: 'Ask about this',
    hcOpenAdvisory: 'Open My advice',
    hcComposing: 'Generating...',
    hcSuggestionsHint: 'Try one',
    hcReadMore: 'Read more',
    hcReadLess: 'Show less',
    hcEmptyLine: 'Ask about your work or plans — answers stay in facts mode.',
    // --- Crew B (voice-first rebuild, 2026-09-21): voice-UX states ----------
    // Exact screen copy, per the voice-UX spec: the mic button tap lands on
    // "Listening...", a pause/finalize lands on "Understanding your text...",
    // and the send lands on "Generating...".
    hcListening: 'Listening...',
    hcUnderstanding: 'Understanding your text...',
    hcMicPermission: 'Waiting for mic permission…',
    hcMicStop: 'Stop listening',
    hcMicBlockedTitle: 'Mic is blocked',
    hcMicBlockedBody: 'The browser blocked the microphone, so I cannot hear you. Allow the mic to speak your question — or type it instead.',
    hcMicBlockedOpen: 'Open Settings',
    // --- Worker 3 (home-ask-focus, 2026-09-21): Ask is the hero of Home -----
    askHeroTitle: 'Ask about your weather',
    askHeroSub: 'Answers from official data — type or speak.',
  },
  hi: {
    hcRegion: 'SAARTHI से पूछें',
    hcFactsTitle: 'केवल तथ्य',
    hcFactsBody: 'उत्तर आधिकारिक बुलेटिनों से आते हैं। मैं अंदाज़ा नहीं लगाता, और यहाँ सलाह नहीं देता।',
    hcFactsEscape: 'मार्गदर्शन चाहिए? मेरी सलाह खोलें',
    hcFactsMore: 'इस चैट के बारे में',
    hcFactsClose: 'बंद करें',
    hcAs: 'उत्तर दे रहा है',
    hcComposerHint: 'मौसम, बारिश, चेतावनी पूछें…',
    hcSend: 'भेजें',
    hcMicHint: 'अपना सवाल बोलें',
    hcQueuedChip: 'कतारबद्ध',
    hcQueuedText: 'नेटवर्क का इंतज़ार — लौटते ही जवाब दूँगा',
    hcFallbackChip: 'सुरक्षित विकल्प',
    hcFallbackText: 'सहेजे डेटा से बना — लाइव जाँच पूरी नहीं हुई',
    hcListen: 'सुनें',
    hcStopListen: 'रोकें',
    hcSpeaking: 'बोल रहा है…',
    hcBasedOn: 'आधार',
    hcBasedOnSaved: 'इस फ़ोन में सहेजा',
    hcAskAboutThis: 'इसके बारे में पूछें',
    hcOpenAdvisory: 'मेरी सलाह खोलें',
    hcComposing: 'तैयार हो रहा है…',
    hcSuggestionsHint: 'एक आज़माएँ',
    hcReadMore: 'और पढ़ें',
    hcReadLess: 'छिपाएँ',
    hcEmptyLine: 'अपने काम या योजना के बारे में पूछें — उत्तर तथ्य मोड में ही रहेंगे।',
    // --- Crew B (voice-first rebuild, 2026-09-21): voice-UX states ----------
    hcListening: 'सुन रहा हूँ…',
    hcUnderstanding: 'आपका टेक्स्ट समझ रहा हूँ…',
    hcMicPermission: 'माइक अनुमति का इंतज़ार…',
    hcMicStop: 'सुनना बंद करें',
    hcMicBlockedTitle: 'माइक ब्लॉक है',
    hcMicBlockedBody: 'ब्राउज़र ने माइक्रोफ़ोन अवरुद्ध कर दिया है, इसलिए मैं आपको सुन नहीं सकता। सवाल बोलने के लिए माइक की अनुमति दें — या सवाल टाइप करें।',
    hcMicBlockedOpen: 'सेटिंग्स खोलें',
    // --- Worker 3 (home-ask-focus, 2026-09-21): Ask is the hero of Home -----
    askHeroTitle: 'अपने मौसम के बारे में पूछें',
    askHeroSub: 'आधिकारिक आंकड़ों पर आधारित उत्तर — टाइप करें या बोलें।',
  },
  te: {
    hcRegion: 'SAARTHIని అడగండి',
    hcFactsTitle: 'వాస్తవాలు మాత్రమే',
    hcFactsBody: 'సమాధానాలు అధికారిక బులెటిన్ల నుండే వస్తాయి. నేను ఊహించను, ఇక్కడ సలహా ఇవ్వను.',
    hcFactsEscape: 'మార్గదర్శనం కావాలా? నా సలహా తెరవండి',
    hcFactsMore: 'ఈ చాట్ గురించి',
    hcFactsClose: 'మూసివేయండి',
    hcAs: 'సమాధానం ఇస్తోంది',
    hcComposerHint: 'వాతావరణం, వర్షం, హెచ్చరికలు అడగండి…',
    hcSend: 'పంపండి',
    hcMicHint: 'మీ ప్రశ్న చెప్పండి',
    hcQueuedChip: 'క్యూలో ఉంది',
    hcQueuedText: 'నెట్‌వర్క్ కోసం వేచి — తిరిగి రాగానే సమాధానం ఇస్తాను',
    hcFallbackChip: 'భద్రతా జవాబు',
    hcFallbackText: 'సేవ్ చేసిన డేటా నుండి — లైవ్ తనిఖీ పూర్తి కాలేదు',
    hcListen: 'వినండి',
    hcStopListen: 'ఆపండి',
    hcSpeaking: 'మాట్లాడుతోంది…',
    hcBasedOn: 'ఆధారం',
    hcBasedOnSaved: 'ఈ ఫోన్‌లో నిల్వ',
    hcAskAboutThis: 'దీని గురించి అడగండి',
    hcOpenAdvisory: 'నా సలహా తెరవండి',
    hcComposing: 'తయారవుతోంది…',
    hcSuggestionsHint: 'ఒకటి ప్రయత్నించండి',
    hcReadMore: 'మరింత చదవండి',
    hcReadLess: 'దాచండి',
    hcEmptyLine: 'మీ పని లేదా ప్రణాళిక గురించి అడగండి — సమాధానాలు వాస్తవ మోడ్‌లోనే ఉంటాయి.',
    // --- Crew B (voice-first rebuild, 2026-09-21): voice-UX states ----------
    hcListening: 'వింటున్నాను…',
    hcUnderstanding: 'మీ టెక్స్ట్ అర్థం చేసుకుంటున్నాను…',
    hcMicPermission: 'మైక్ అనుమతి కోసం వేచి…',
    hcMicStop: 'వినడం ఆపండి',
    hcMicBlockedTitle: 'మైక్ నిరోధించబడింది',
    hcMicBlockedBody: 'బ్రౌజర్ మైక్రోఫోన్‌ను నిరోధించింది, కాబట్టి మిమ్మల్ని వినలేను. ప్రశ్న చెప్పడానికి మైక్‌ను అనుమతించండి — లేదా టైప్ చేయండి.',
    hcMicBlockedOpen: 'సెట్టింగ్‌లు తెరవండి',
    // --- Worker 3 (home-ask-focus, 2026-09-21): Ask is the hero of Home -----
    askHeroTitle: 'మీ వాతావరణం గురించి అడగండి',
    askHeroSub: 'అధికారిక డేటా నుండి సమాధానాలు — టైప్ చేయండి లేదా మాట్లాడండి.',
  },
};
