// HomeChat strings: the Home-screen chat board (Ask merged into Home).
//
// Facts-only vocabulary: this chat answers from official bulletins and NEVER
// gives guidance. Every string here is a label, not advice — the one escape
// to guidance is the "Open My advice" pill, which navigates to Advisory.
export default {
  en: {
    hcRegion: 'Ask SAARTHI',
    hcFactsTitle: 'Facts only',
    hcFactsBody: 'Answers come from official bulletins. I never guess, and I never give advice here.',
    hcFactsEscape: 'Need guidance instead? Open My advice',
    hcFactsMore: 'About this chat',
    hcFactsClose: 'Close',
    hcAs: 'Answering as',
    hcComposerHint: 'Ask about weather, rain, warnings…',
    hcSend: 'Send',
    hcMicHint: 'Speak your question',
    hcQueuedChip: 'Queued',
    hcQueuedText: 'Waiting for network — will answer when you are back online',
    hcListen: 'Listen',
    hcStopListen: 'Stop',
    hcSpeaking: 'Speaking…',
    hcBasedOn: 'Based on',
    hcBasedOnSaved: 'saved on this phone',
    hcAskAboutThis: 'Ask about this',
    hcOpenAdvisory: 'Open My advice',
    hcComposing: 'Working…',
    hcSuggestionsHint: 'Try one',
    hcReadMore: 'Read more',
    hcReadLess: 'Show less',
    hcEmptyLine: 'Ask about your work or plans — answers stay in facts mode.',
  },
  hi: {
    hcRegion: 'SAARTHI से पूछें',
    hcFactsTitle: 'केवल तथ्य',
    hcFactsBody: 'उत्तर आधिकारिक बुलेटिनों से आते हैं। मैं अंदाज़ा नहीं लगाता, और यहाँ सलाह नहीं देता।',
    hcFactsEscape: 'मार्गदर्शन चाहिए? मेरी सलाह खोलें',
    hcFactsMore: 'इस चैट के बारे में',
    hcFactsClose: 'बंद करें',
    hcAs: 'उत्तर दे रहा है',
    hcComposerHint: 'मौसम, बारिश, चेतावनी पूछें…',
    hcSend: 'भेजें',
    hcMicHint: 'अपना सवाल बोलें',
    hcQueuedChip: 'कतारबद्ध',
    hcQueuedText: 'नेटवर्क का इंतज़ार — लौटते ही जवाब दूँगा',
    hcListen: 'सुनें',
    hcStopListen: 'रोकें',
    hcSpeaking: 'बोल रहा है…',
    hcBasedOn: 'आधार',
    hcBasedOnSaved: 'इस फ़ोन में सहेजा',
    hcAskAboutThis: 'इसके बारे में पूछें',
    hcOpenAdvisory: 'मेरी सलाह खोलें',
    hcComposing: 'काम हो रहा है…',
    hcSuggestionsHint: 'एक आज़माएँ',
    hcReadMore: 'और पढ़ें',
    hcReadLess: 'छिपाएँ',
    hcEmptyLine: 'अपने काम या योजना के बारे में पूछें — उत्तर तथ्य मोड में ही रहेंगे।',
  },
  te: {
    hcRegion: 'SAARTHIని అడగండి',
    hcFactsTitle: 'వాస్తవాలు మాత్రమే',
    hcFactsBody: 'సమాధానాలు అధికారిక బులెటిన్ల నుండే వస్తాయి. నేను ఊహించను, ఇక్కడ సలహా ఇవ్వను.',
    hcFactsEscape: 'మార్గదర్శనం కావాలా? నా సలహా తెరవండి',
    hcFactsMore: 'ఈ చాట్ గురించి',
    hcFactsClose: 'మూసివేయండి',
    hcAs: 'సమాధానం ఇస్తోంది',
    hcComposerHint: 'వాతావరణం, వర్షం, హెచ్చరికలు అడగండి…',
    hcSend: 'పంపండి',
    hcMicHint: 'మీ ప్రశ్న చెప్పండి',
    hcQueuedChip: 'క్యూలో ఉంది',
    hcQueuedText: 'నెట్‌వర్క్ కోసం వేచి — తిరిగి రాగానే సమాధానం ఇస్తాను',
    hcListen: 'వినండి',
    hcStopListen: 'ఆపండి',
    hcSpeaking: 'మాట్లాడుతోంది…',
    hcBasedOn: 'ఆధారం',
    hcBasedOnSaved: 'ఈ ఫోన్‌లో నిల్వ',
    hcAskAboutThis: 'దీని గురించి అడగండి',
    hcOpenAdvisory: 'నా సలహా తెరవండి',
    hcComposing: 'పని జరుగుతోంది…',
    hcSuggestionsHint: 'ఒకటి ప్రయత్నించండి',
    hcReadMore: 'మరింత చదవండి',
    hcReadLess: 'దాచండి',
    hcEmptyLine: 'మీ పని లేదా ప్రణాళిక గురించి అడగండి — సమాధానాలు వాస్తవ మోడ్‌లోనే ఉంటాయి.',
  },
};
