// Home view.
export default {
  en: {
    rightNow: 'Right now',
    wind: 'Wind',
    humidity: 'Humidity',
    rainfall: 'Rain',
    windUnit: 'km/h',
    rainUnit: 'mm',
    alertCheck: 'Alert check',
    allClear: 'All clear',
    allClearSub: 'No official warning for your district.',
    proofChecked: 'Checked {t} · SACHET CAP',
    cannotCheck: "Can't verify right now",
    cannotCheckSub: "Warning service unreachable — we can't say it's safe.",
    activeOne: '1 active warning',
    activeMany: '{n} active warnings',
    viewAlerts: 'View alerts',
    askTitle: 'Ask SAARTHI',
    askSub: 'Rain, heat, warnings, travel — answers from live official data only.',
    askCta: 'Start asking',
    forecast: 'Coming days',
    rainChance: '{n}% rain',
    sources: 'Sources',
    sourcesLive: '{n} live · {m} sources',
    sourcesOpen: 'Source details',
    forYou: 'For you',
    openAdvice: 'Get my advice',
  },
  hi: {
    rightNow: 'अभी',
    wind: 'हवा',
    humidity: 'नमी',
    rainfall: 'बारिश',
    windUnit: 'किमी/घं',
    rainUnit: 'मिमी',
    alertCheck: 'अलर्ट जाँच',
    allClear: 'सब साफ़ है',
    allClearSub: 'आपके ज़िले के लिए कोई आधिकारिक चेतावनी नहीं।',
    proofChecked: '{t} जाँचा · SACHET CAP',
    cannotCheck: 'अभी सत्यापित नहीं हो सकता',
    cannotCheckSub: 'चेतावनी सेवा पहुँच से बाहर — सुरक्षित कहना संभव नहीं।',
    activeOne: '1 सक्रिय चेतावनी',
    activeMany: '{n} सक्रिय चेतावनियाँ',
    viewAlerts: 'अलर्ट देखें',
    askTitle: 'SAARTHI से पूछें',
    askSub: 'बारिश, गर्मी, चेतावनी, यात्रा — उत्तर केवल लाइव आधिकारिक डेटा से।',
    askCta: 'पूछना शुरू करें',
    forecast: 'आने वाले दिन',
    rainChance: '{n}% बारिश',
    sources: 'स्रोत',
    sourcesLive: '{n} लाइव · {m} स्रोत',
    sourcesOpen: 'स्रोत विवरण',
    forYou: 'आपके लिए',
    openAdvice: 'मेरी सलाह लें',
  },
  te: {
    rightNow: 'ప్రస్తుతం',
    wind: 'గాలి',
    humidity: 'తేమ',
    rainfall: 'వర్షం',
    windUnit: 'కిమీ/గం',
    rainUnit: 'మిమీ',
    alertCheck: 'హెచ్చరిక తనిఖీ',
    allClear: 'అంతా స్పష్టం',
    allClearSub: 'మీ జిల్లాకు అధికారిక హెచ్చరిక ఏదీ లేదు.',
    proofChecked: '{t} తనిఖీ · SACHET CAP',
    cannotCheck: 'ప్రస్తుతం ధృవీకరించలేము',
    cannotCheckSub: 'హెచ్చరిక సేవ అందుబాటులో లేదు — సురక్షితమని చెప్పలేము.',
    activeOne: '1 క్రియాశీల హెచ్చరిక',
    activeMany: '{n} క్రియాశీల హెచ్చరికలు',
    viewAlerts: 'హెచ్చరికలు చూడండి',
    askTitle: 'SAARTHI ని అడగండి',
    askSub: 'వర్షం, వేడి, హెచ్చరికలు, ప్రయాణం — సమాధానాలు ప్రత్యక్ష అధికారిక డేటా నుండే.',
    askCta: 'అడగడం ప్రారంభించండి',
    forecast: 'రాబోయే రోజులు',
    rainChance: '{n}% వర్షం',
    sources: 'మూలాలు',
    sourcesLive: '{n} లైవ్ · {m} మూలాలు',
    sourcesOpen: 'మూలాల వివరాలు',
    forYou: 'మీ కోసం',
    openAdvice: 'నా సలహా తీసుకోండి',
  },
};
