// Home screen, Round 2 strings: status strip, weather-now, alert banner,
// action tiles, notification preview. EN/HI/TE. Severity words stay in i18n.js
// so Home and Alerts can never disagree on them.
export default {
  en: {
    hConnLive: 'Live', hConnCached: 'Cached', hConnOffline: 'Offline', hConnReconnecting: 'Reconnecting…',
    hSyncNow: 'updated just now', hSyncAgo: 'updated {m}m ago', hSyncNever: 'not synced yet',
    hNowTitle: 'Weather now',
    hAlertsTitle: 'Active alerts', hAlertsGo: 'Open alerts',
    hUpcoming: 'Scheduled',
    hTilesTitle: 'What do you need?',
    hTileAsk: 'Ask SAARTHI', hTileAlerts: 'Alerts', hTileNotif: 'Notifications', hTileAdvisor: 'By role',
    hNotifTitle: 'Latest notifications', hNotifAll: 'View all',
    hNotifEmpty: 'Nothing yet — alert updates will appear here the moment they are sent.',
    // Sky hero (Crew A, 2026-09-21): the creative weather band. Lens words are
    // plain weather descriptions (hot, breezy, heavy rain) — never safety
    // severities; the backend verdict stays the one severity. Provenance codes
    // (LIVE/CACHED/DEMO) are machine-readable and stay untranslated.
    lensTitle: 'What the conditions mean',
    lensHeat: 'Heat', lensRain: 'Rain', lensWind: 'Wind',
    lensNA: 'Not available yet',
    heatVeryHot: 'Very hot', heatHot: 'Hot', heatWarm: 'Warm', heatMild: 'Mild', heatCool: 'Cool',
    rainDry: 'Dry', rainLight: 'Light rain', rainSteady: 'Steady rain', rainHeavy: 'Heavy rain',
    windCalm: 'Calm', windBreezy: 'Breezy', windWindy: 'Windy', windGusty: 'Strong gusts',
    cityTitle: 'No location? Type your city',
    cityPh: 'City or district', cityApply: 'Use this place',
    cityNoMatch: 'No match — try another spelling',
    cityFailed: 'Search failed — check your connection',
    wxUnavailable: 'Weather data is not available yet',
  },
  hi: {
    hConnLive: 'लाइव', hConnCached: 'कैश्ड', hConnOffline: 'ऑफ़लाइन', hConnReconnecting: 'फिर जुड़ रहे हैं…',
    hSyncNow: 'अभी अपडेट हुआ', hSyncAgo: '{m} मिनट पहले अपडेट', hSyncNever: 'अभी सिंक नहीं हुआ',
    hNowTitle: 'अभी मौसम',
    hAlertsTitle: 'सक्रिय चेतावनियाँ', hAlertsGo: 'चेतावनियाँ खोलें',
    hUpcoming: 'निर्धारित',
    hTilesTitle: 'आपको क्या चाहिए?',
    hTileAsk: 'SAARTHI से पूछें', hTileAlerts: 'चेतावनियाँ', hTileNotif: 'सूचनाएँ', hTileAdvisor: 'भूमिका चुनें',
    hNotifTitle: 'हाल की सूचनाएँ', hNotifAll: 'सभी देखें',
    hNotifEmpty: 'अभी कुछ नहीं — अलर्ट अपडेट भेजते ही यहाँ दिखेंगे।',
    lensTitle: 'मौसम का मतलब क्या है',
    lensHeat: 'गर्मी', lensRain: 'बारिश', lensWind: 'हवा',
    lensNA: 'अभी उपलब्ध नहीं है',
    heatVeryHot: 'बहुत ज़्यादा गर्म', heatHot: 'गर्म', heatWarm: 'हल्की गर्मी', heatMild: 'सुहावना', heatCool: 'ठंडा',
    rainDry: 'सूखा', rainLight: 'हल्की बारिश', rainSteady: 'लगातार बारिश', rainHeavy: 'भारी बारिश',
    windCalm: 'शांत', windBreezy: 'हल्की हवा', windWindy: 'तेज़ हवा', windGusty: 'तेज़ झोंके',
    cityTitle: 'स्थान नहीं मिला? अपना शहर लिखें',
    cityPh: 'शहर या जिला', cityApply: 'यह जगह चुनें',
    cityNoMatch: 'नहीं मिला — कोई और नाम लिखें',
    cityFailed: 'खोज नहीं हो सकी — कनेक्शन जाँचें',
    wxUnavailable: 'मौसम की जानकारी अभी उपलब्ध नहीं है',
  },
  te: {
    hConnLive: 'లైవ్', hConnCached: 'క్యాష్', hConnOffline: 'ఆఫ్‌లైన్', hConnReconnecting: 'మళ్లీ కనెక్ట్ అవుతోంది…',
    hSyncNow: 'ఇప్పుడే అప్‌డేట్', hSyncAgo: '{m} నిమిషాల క్రితం అప్‌డేట్', hSyncNever: 'ఇంకా సింక్ కాలేదు',
    hNowTitle: 'ఇప్పుడు వాతావరణం',
    hAlertsTitle: 'యాక్టివ్ అలర్ట్‌లు', hAlertsGo: 'అలర్ట్‌లు తెరవండి',
    hUpcoming: 'షెడ్యూల్',
    hTilesTitle: 'మీకు ఏమి కావాలి?',
    hTileAsk: 'SAARTHIని అడగండి', hTileAlerts: 'అలర్ట్‌లు', hTileNotif: 'నోటిఫికేషన్లు', hTileAdvisor: 'పాత్ర ఎంచుకోండి',
    hNotifTitle: 'తాజా నోటిఫికేషన్లు', hNotifAll: 'అన్నీ చూడండి',
    hNotifEmpty: 'ఇంకా లేదు — అలర్ట్ అప్‌డేట్‌లు పంపిన వెంటనే ఇక్కడ కనిపిస్తాయి.',
    lensTitle: 'వాతావరణ అర్థం ఏమిటి',
    lensHeat: 'వేడి', lensRain: 'వర్షం', lensWind: 'గాలి',
    lensNA: 'ఇంకా అందుబాటులో లేదు',
    heatVeryHot: 'చాలా వేడిగా', heatHot: 'వేడిగా', heatWarm: 'వెచ్చగా', heatMild: 'ఆహ్లాదంగా', heatCool: 'చల్లగా',
    rainDry: 'పొడిగా', rainLight: 'తేలికపాటి వర్షం', rainSteady: 'నిరంతర వర్షం', rainHeavy: 'భారీ వర్షం',
    windCalm: 'ప్రశాంతంగా', windBreezy: 'తేలికపాటి గాలి', windWindy: 'బలమైన గాలి', windGusty: 'బలమైన గాలివాన',
    cityTitle: 'స్థానం లేదా? మీ నగరాన్ని రాయండి',
    cityPh: 'నగరం లేదా జిల్లా', cityApply: 'ఈ ప్రాంతాన్ని వాడండి',
    cityNoMatch: 'కనిపించలేదు — మరో పేరు రాయండి',
    cityFailed: 'వెతకలేకపోయాం — కనెక్షన్ చూడండి',
    wxUnavailable: 'వాతావరణ సమాచారం ఇంకా అందుబాటులో లేదు',
  },
};
