// Home screen, Round 3 strings: the compact about-you strip, the weather
// card, and the active-alerts section. EN/HI/TE — all three required.
// Severity words and provenance labels (LIVE / CACHED / DEMO / UNAVAILABLE)
// stay machine-readable and are never translated.
export default {
  en: {
    h3RoleTitle: 'Your role',
    h3RoleSet: 'Set your role',
    h3RoleChange: 'Change',
    h3WxTitle: 'Weather now',
    h3WxTemp: 'Temperature',
    h3WxWind: 'Wind',
    h3WxDir: 'direction',
    h3WxHum: 'Humidity',
    h3WxCond: 'Conditions',
    h3Unavailable: 'Not available',
    h3WxChecking: 'Checking current conditions…',
    h3AlertsTitle: 'Active alerts',
    h3AlertsNone: 'No active alerts for your district right now.',
    h3AlertsOpen: 'Open alerts',
    h3AlertsRetry: 'Try again',
  },
  hi: {
    h3RoleTitle: 'आपकी भूमिका',
    h3RoleSet: 'अपनी भूमिका चुनें',
    h3RoleChange: 'बदलें',
    h3WxTitle: 'अभी मौसम',
    h3WxTemp: 'तापमान',
    h3WxWind: 'हवा',
    h3WxDir: 'दिशा',
    h3WxHum: 'नमी',
    h3WxCond: 'स्थिति',
    h3Unavailable: 'उपलब्ध नहीं',
    h3WxChecking: 'मौसम की वर्तमान स्थिति जाँच रहे हैं…',
    h3AlertsTitle: 'सक्रिय चेतावनियाँ',
    h3AlertsNone: 'अभी आपके जिले के लिए कोई सक्रिय चेतावनी नहीं।',
    h3AlertsOpen: 'चेतावनियाँ खोलें',
    h3AlertsRetry: 'फिर कोशिश करें',
  },
  te: {
    h3RoleTitle: 'మీ పాత్ర',
    h3RoleSet: 'మీ పాత్రను ఎంచుకోండి',
    h3RoleChange: 'మార్చండి',
    h3WxTitle: 'ప్రస్తుత వాతావరణం',
    h3WxTemp: 'ఉష్ణోగ్రత',
    h3WxWind: 'గాలి',
    h3WxDir: 'దిశ',
    h3WxHum: 'తేమ',
    h3WxCond: 'స్థితి',
    h3Unavailable: 'అందుబాటులో లేదు',
    h3WxChecking: 'ప్రస్తుత వాతావరణాన్ని తనిఖీ చేస్తున్నాం…',
    h3AlertsTitle: 'సక్రియ హెచ్చరికలు',
    h3AlertsNone: 'మీ జిల్లాకు ప్రస్తుతం సక్రియ హెచ్చరికలు లేవు.',
    h3AlertsOpen: 'హెచ్చరికలు తెరవండి',
    h3AlertsRetry: 'మళ్లీ ప్రయత్నించండి',
  },
};
