// Strings for the grouped Notifications inbox and the inline Alerts list.
//
// The inbox groups every alert's lifecycle (issued -> active -> extended ->
// ended) into one expandable trail. Transition words are verbs a non-reader
// can pair with the icon: issued, active, updated, extended, ended.
export default {
  en: {
    // --- inbox: grouped alert timelines --------------------------------
    inboxGroupUpdates: '{n} updates',
    inboxTimeline: 'Timeline',
    inboxViewAlert: 'View alert',
    inboxHideAlert: 'Hide alert',
    inboxDemoTag: 'Demo',
    inboxOfficialTag: 'Official',
    inboxUnknownAlert: 'Warning',
    // --- transition labels (one verb per kind) --------------------------
    trPreAlert: 'Issued',
    trStart: 'Issued',
    trActive: 'Active',
    trUpdated: 'Updated',
    trExtended: 'Extended',
    trEnded: 'Ended',
    trClear: 'Ended',
    trCancelled: 'Cancelled',
    trEscalate: 'Upgraded',
    trTest: 'Test',
    trInfo: 'Info',
    trP2pRelay: 'Relayed',
    // --- alerts list: inline expansion (no separate details route) -----
    listExpand: 'Open details',
    listCollapse: 'Close details',
    listDemoTag: 'Demo',
    listOfficialTag: 'Official',
    listUnknownAlert: 'Warning',
  },
  hi: {
    inboxGroupUpdates: '{n} अपडेट',
    inboxTimeline: 'घटनाक्रम',
    inboxViewAlert: 'अलर्ट देखें',
    inboxHideAlert: 'अलर्ट छिपाएँ',
    inboxDemoTag: 'डेमो',
    inboxOfficialTag: 'आधिकारिक',
    inboxUnknownAlert: 'चेतावनी',
    trPreAlert: 'जारी',
    trStart: 'जारी',
    trActive: 'सक्रिय',
    trUpdated: 'अपडेट',
    trExtended: 'बढ़ाई गई',
    trEnded: 'समाप्त',
    trClear: 'समाप्त',
    trCancelled: 'रद्द',
    trEscalate: 'बढ़ी हुई',
    trTest: 'परीक्षण',
    trInfo: 'सूचना',
    trP2pRelay: 'भेजी गई',
    listExpand: 'विवरण खोलें',
    listCollapse: 'विवरण बंद करें',
    listDemoTag: 'डेमो',
    listOfficialTag: 'आधिकारिक',
    listUnknownAlert: 'चेतावनी',
  },
  te: {
    inboxGroupUpdates: '{n} అప్‌డేట్‌లు',
    inboxTimeline: 'ఘటనాక్రమం',
    inboxViewAlert: 'అలర్ట్ చూడండి',
    inboxHideAlert: 'అలర్ట్ దాచండి',
    inboxDemoTag: 'డెమో',
    inboxOfficialTag: 'అధికారిక',
    inboxUnknownAlert: 'హెచ్చరిక',
    trPreAlert: 'జారీ',
    trStart: 'జారీ',
    trActive: 'క్రియాశీలం',
    trUpdated: 'నవీకరణ',
    trExtended: 'పొడిగించబడింది',
    trEnded: 'ముగిసింది',
    trClear: 'ముగిసింది',
    trCancelled: 'రద్దు',
    trEscalate: 'పెంచబడింది',
    trTest: 'పరీక్ష',
    trInfo: 'సమాచారం',
    trP2pRelay: 'పంపబడింది',
    listExpand: 'వివరాలు తెరవండి',
    listCollapse: 'వివరాలు మూసివేయండి',
    listDemoTag: 'డెమో',
    listOfficialTag: 'అధికారిక',
    listUnknownAlert: 'హెచ్చరిక',
  },
};
