// Offline emergency info-card QR strings. EN/HI/TE.
//
// These words do double duty: they label the on-screen card AND they are
// baked into the QR's plain text, which a stranger's generic camera app
// reads. So the QR-text labels stay short, plain, and — like severity codes
// — the structure (ALERT/DO/AVOID lines) is identical across languages.
export default {
  en: {
    icShowBtn: 'Show my emergency info as QR',
    icShowSub: 'Anyone can scan it — no app needed',
    icCardTitle: 'Emergency info QR',
    icCardSub: 'Built only from this phone\u2019s saved data — no internet used. Any generic camera app can read it.',
    icTitle: 'SAARTHI EMERGENCY INFO',
    icAlert: 'ALERT',
    icDo: 'DO',
    icAvoid: 'AVOID',
    icWeatherNow: 'WEATHER NOW',
    icGenerated: 'Generated',
    icCachedNote: 'Cached data \u2014 may be outdated',
    icNoApp: 'No app needed to read this',
    icValidTill: 'Valid till',
    icNoData: 'No saved info yet. Open the app once while online so this phone has something to share.',
    icPageOf: '{i} of {n}',
    icPrev: 'Previous',
    icNext: 'Next',
    icScanHint: 'Point any phone camera at the code \u2014 it reads as plain text.',
  },
  hi: {
    icShowBtn: 'मेरी आपातकालीन जानकारी QR में दिखाएँ',
    icShowSub: 'कोई भी स्कैन कर सकता है — ऐप ज़रूरी नहीं',
    icCardTitle: 'आपातकालीन जानकारी QR',
    icCardSub: 'सिर्फ इस फ़ोन के सहेजे डेटा से बना — कोई इंटरनेट नहीं। कोई भी सामान्य कैमरा ऐप इसे पढ़ सकता है।',
    icTitle: 'SAARTHI आपातकालीन जानकारी',
    icAlert: 'अलर्ट',
    icDo: 'करें',
    icAvoid: 'न करें',
    icWeatherNow: 'अभी का मौसम',
    icGenerated: 'बनाया गया',
    icCachedNote: 'सहेजा गया डेटा — पुराना हो सकता है',
    icNoApp: 'इसे पढ़ने के लिए ऐप की ज़रूरत नहीं',
    icValidTill: 'तक वैध',
    icNoData: 'अभी कोई सहेजी जानकारी नहीं। ऑनलाइन रहते एक बार ऐप खोलें।',
    icPageOf: '{i} / {n}',
    icPrev: 'पिछला',
    icNext: 'अगला',
    icScanHint: 'किसी भी फ़ोन का कैमरा कोड पर रखें — यह सादे टेक्स्ट में दिखेगा।',
  },
  te: {
    icShowBtn: 'నా అత్యవసర సమాచారాన్ని QR గా చూపించు',
    icShowSub: 'ఎవరైనా స్కాన్ చేయవచ్చు — యాప్ అవసరం లేదు',
    icCardTitle: 'అత్యవసర సమాచార QR',
    icCardSub: 'ఈ ఫోన్ సేవ్ చేసిన డేటాతో మాత్రమే — ఇంటర్నెట్ లేదు. ఏ సాధారణ కెమెరా యాప్ అయినా చదవగలదు.',
    icTitle: 'SAARTHI అత్యవసర సమాచారం',
    icAlert: 'హెచ్చరిక',
    icDo: 'చేయండి',
    icAvoid: 'చేయవద్దు',
    icWeatherNow: 'ప్రస్తుత వాతావరణం',
    icGenerated: 'సృష్టించబడింది',
    icCachedNote: 'సేవ్ చేసిన డేటా — పాతది కావచ్చు',
    icNoApp: 'దీన్ని చదవడానికి యాప్ అవసరం లేదు',
    icValidTill: 'వరకు చెల్లుబాటు',
    icNoData: 'సేవ్ చేసిన సమాచారం లేదు. ఆన్‌లైన్‌లో ఉన్నప్పుడు యాప్‌ను ఒకసారి తెరవండి.',
    icPageOf: '{i} / {n}',
    icPrev: 'వెనుకకు',
    icNext: 'తర్వాత',
    icScanHint: 'ఏ ఫోన్ కెమెరానైనా కోడ్ వైపు చూపించండి — ఇది సాదా టెక్స్ట్‌గా కనిపిస్తుంది.',
  },
};
