// More view: settings, notifications, about.
export default {
  en: {
    moreTitle: 'More',
    language: 'Language',
    langSub: 'Applies across the whole app',
    notifications: 'Notifications',
    notifSub: 'Official alerts as push messages, even with the app closed',
    enable: 'Enable',
    on: 'On',
    off: 'Off',
    pushUnsupported: "Push isn't supported in this browser.",
    pushDenied: 'Notifications are blocked — allow them in your browser settings.',
    trustOpen: 'Trust & sources',
    trustSub: 'Every source, with its live status',
    about: 'About SAARTHI',
    aboutBody: 'IMD first · backfills on. Official alerts arrive via SACHET CAP. Guidance is decision support — never an official order, and never a substitute for calling 112.',
    version: 'Prototype build',
    clearDone: 'Saved data cleared.',
    danger: 'Emergency',
    call112: 'Call 112',
  },
  hi: {
    moreTitle: 'अधिक',
    language: 'भाषा',
    langSub: 'पूरे ऐप पर लागू',
    notifications: 'सूचनाएँ',
    notifSub: 'ऐप बंद होने पर भी आधिकारिक अलर्ट पुश संदेश के रूप में',
    enable: 'चालू करें',
    on: 'चालू',
    off: 'बंद',
    pushUnsupported: 'इस ब्राउज़र में पुश समर्थित नहीं।',
    pushDenied: 'सूचनाएँ ब्लॉक हैं — ब्राउज़र सेटिंग में अनुमति दें।',
    trustOpen: 'भरोसा और स्रोत',
    trustSub: 'हर स्रोत, उसकी लाइव स्थिति के साथ',
    about: 'SAARTHI के बारे में',
    aboutBody: 'IMD पहले · बैकफ़िल चालू। आधिकारिक अलर्ट SACHET CAP से आते हैं। मार्गदर्शन निर्णय-सहायता है — कोई आधिकारिक आदेश नहीं, और 112 पर कॉल का विकल्प नहीं।',
    version: 'प्रोटोटाइप बिल्ड',
    clearDone: 'सहेजा डेटा साफ़ किया गया।',
    danger: 'आपातकाल',
    call112: '112 पर कॉल करें',
  },
  te: {
    moreTitle: 'మరిన్ని',
    language: 'భాష',
    langSub: 'మొత్తం యాప్‌కు వర్తిస్తుంది',
    notifications: 'నోటిఫికేషన్లు',
    notifSub: 'యాప్ మూసివేసినా అధికారిక హెచ్చరికలు పుష్ సందేశాలుగా',
    enable: 'ప్రారంభించండి',
    on: 'ఆన్',
    off: 'ఆఫ్',
    pushUnsupported: 'ఈ బ్రౌజర్‌లో పుష్ మద్దతు లేదు.',
    pushDenied: 'నోటిఫికేషన్లు బ్లాక్ చేయబడ్డాయి — బ్రౌజర్ సెట్టింగ్స్‌లో అనుమతించండి.',
    trustOpen: 'నమ్మకం & మూలాలు',
    trustSub: 'ప్రతి మూలం, దాని లైవ్ స్థితితో',
    about: 'SAARTHI గురించి',
    aboutBody: 'IMD మొదట · బ్యాక్‌ఫిల్ ఆన్. అధికారిక హెచ్చరికలు SACHET CAP ద్వారా. మార్గదర్శకం నిర్ణయ సహాయం — అధికారిక ఆదేశం కాదు, 112కు కాల్‌కు ప్రత్యామ్నాయం కాదు.',
    version: 'ప్రోటోటైప్ బిల్డ్',
    clearDone: 'సేవ్ చేసిన డేటా తొలగించబడింది.',
    danger: 'అత్యవసరం',
    call112: '112కు కాల్ చేయండి',
  },
};
