// Push-notification strings.
//
// Notification text has to survive being read on a lock screen at a glance, so
// every string is short, leads with the action, and never explains itself.
// `{severity}`, `{hazard}` and `{district}` are substituted at send time.
export default {
  en: {
    notifyOnBackground: "Alerts on — you will be notified even when the app is closed",
    notifyNoPush: "Alerts on in-app only. This browser cannot receive background push.",
    notifyPushFailed: "Could not register for background alerts. In-app alerts still work.",
    notifyTestSent: "Test push sent",
    // The button is a verb; the past tense belongs in the post-send toast.
    notifyTest: "Send test push",
    notifyTestNone: "No device is registered for this district yet",
    demoPushHint: "Sent by the server, so it arrives with the app closed",
    notifyOn: 'Alerts on',
    notifyOff: 'Alerts off',
    notifyBlocked: 'Notifications are blocked in your browser settings',
    notifyUnsupported: 'This browser cannot show notifications',
    notifyStartTitle: 'Weather alert',
    notifyStartBody: '{severity} {hazard} warning for {district}. Avoid going out unless you must.',
    notifyEscalateTitle: 'Warning upgraded',
    notifyEscalateBody: 'Now {severity} for {district} — {hazard}.',
    notifyClearTitle: 'Safe now',
    notifyClearBody: 'The {hazard} warning for {district} has ended.',
    notifyClearBodyPlain: 'The weather warning for {district} has ended.',
    demoAlert: 'Simulate alert',
    demoClear: 'Simulate all-clear',
    demoNotifyHint: 'Demo: fire a warning now, then the all-clear',
  },
  hi: {
    notifyOnBackground: "चेतावनी चालू — ऐप बंद होने पर भी सूचना मिलेगी",
    notifyNoPush: "चेतावनी केवल ऐप में। यह ब्राउज़र बैकग्राउंड सूचना नहीं ले सकता।",
    notifyPushFailed: "बैकग्राउंड चेतावनी पंजीकृत नहीं हो सकी। ऐप में चेतावनी चालू है।",
    notifyTestSent: "परीक्षण सूचना भेजी गई",
    notifyTest: "टेस्ट सूचना भेजें",
    notifyTestNone: "इस जिले के लिए कोई डिवाइस पंजीकृत नहीं है",
    demoPushHint: "सर्वर से भेजी गई — ऐप बंद होने पर भी पहुँचेगी",
    notifyOn: 'चेतावनी चालू',
    notifyOff: 'चेतावनी बंद',
    notifyBlocked: 'ब्राउज़र सेटिंग में सूचनाएँ बंद हैं',
    notifyUnsupported: 'यह ब्राउज़र सूचनाएँ नहीं दिखा सकता',
    notifyStartTitle: 'मौसम चेतावनी',
    notifyStartBody: '{district} के लिए {severity} {hazard} चेतावनी। ज़रूरी न हो तो बाहर न जाएँ।',
    notifyEscalateTitle: 'चेतावनी बढ़ी',
    notifyEscalateBody: '{district} में अब {severity} — {hazard}।',
    notifyClearTitle: 'अब सुरक्षित',
    notifyClearBody: '{district} की {hazard} चेतावनी समाप्त हो गई।',
    notifyClearBodyPlain: '{district} की मौसम चेतावनी समाप्त हो गई।',
    demoAlert: 'चेतावनी दिखाएँ',
    demoClear: 'सुरक्षित दिखाएँ',
    demoNotifyHint: 'डेमो: पहले चेतावनी, फिर सुरक्षित संदेश',
  },
  te: {
    notifyOnBackground: "హెచ్చరికలు ఆన్ — యాప్ మూసి ఉన్నా నోటిఫికేషన్ వస్తుంది",
    notifyNoPush: "హెచ్చరికలు యాప్‌లో మాత్రమే. ఈ బ్రౌజర్ బ్యాక్‌గ్రౌండ్ నోటిఫికేషన్ తీసుకోలేదు.",
    notifyPushFailed: "బ్యాక్‌గ్రౌండ్ హెచ్చరికలు నమోదు కాలేదు. యాప్‌లో హెచ్చరికలు పనిచేస్తాయి.",
    notifyTestSent: "పరీక్ష నోటిఫికేషన్ పంపబడింది",
    notifyTest: "టెస్ట్ నోటిఫికేషన్ పంపండి",
    notifyTestNone: "ఈ జిల్లాకు ఇంకా ఏ పరికరం నమోదు కాలేదు",
    demoPushHint: "సర్వర్ నుండి పంపబడింది — యాప్ మూసి ఉన్నా చేరుతుంది",
    notifyOn: 'హెచ్చరికలు ఆన్',
    notifyOff: 'హెచ్చరికలు ఆఫ్',
    notifyBlocked: 'బ్రౌజర్ సెట్టింగ్‌లలో నోటిఫికేషన్‌లు నిలిపివేయబడ్డాయి',
    notifyUnsupported: 'ఈ బ్రౌజర్ నోటిఫికేషన్‌లు చూపలేదు',
    notifyStartTitle: 'వాతావరణ హెచ్చరిక',
    notifyStartBody: '{district} కోసం {severity} {hazard} హెచ్చరిక. అవసరం లేకపోతే బయటకు వెళ్లవద్దు.',
    notifyEscalateTitle: 'హెచ్చరిక పెరిగింది',
    notifyEscalateBody: '{district} లో ఇప్పుడు {severity} — {hazard}.',
    notifyClearTitle: 'ఇప్పుడు సురక్షితం',
    notifyClearBody: '{district} కోసం {hazard} హెచ్చరిక ముగిసింది.',
    notifyClearBodyPlain: '{district} కోసం వాతావరణ హెచ్చరిక ముగిసింది.',
    demoAlert: 'హెచ్చరిక చూపించు',
    demoClear: 'సురక్షితం చూపించు',
    demoNotifyHint: 'డెమో: ముందు హెచ్చరిక, తర్వాత సురక్షితం',
  },
};
