// Offline & P2P strings (Agent 2). EN/HI/TE. Machine codes (SIMULATED label,
// severities, state ids) stay untranslated. Copy stays short — icon-first.
export default {
  en: {
    op2pTitle: 'Offline & nearby',
    op2pSub: 'What this phone knows without internet — and how alerts hop phone-to-phone.',
    op2pConnOnline: 'Online', op2pConnOffline: 'Offline',
    op2pCheckedWeather: 'Weather', op2pCheckedAlerts: 'Alerts',
    op2pCheckedAdvice: 'Advice', op2pCheckedNotifications: 'Notifications',
    op2pNoCache: 'Nothing saved yet',
    agoNow: 'Checked just now', agoMin: 'Checked {n} min ago',
    agoHour: 'Checked {n} h ago', agoDay: 'Checked {n} d ago',
    op2pQueueTitle: 'Waiting questions', op2pQueueEmpty: 'No waiting questions.',
    op2pQueueReplay: 'Send now', op2pQueueReplaying: 'Sending…',
    op2pQueueDone: 'Sent {n}', op2pQueueOfflineNote: 'Still offline — they will send on reconnect.',
    op2pQueuedChip: 'Queued',
    op2pTransTitle: 'Alert changes, from saved data',
    op2pTransEmpty: 'No changes since the last check.',
    op2pTransCachedNote: 'From saved data — could not re-check.',
    op2pTrPreAlert: 'Pre-alert started', op2pTrActive: 'Alert active', op2pTrEnded: 'Alert ended',
    op2pP2pTitle: 'Phone-to-phone alert relay',
    op2pRelayBtn: 'Relay alert', op2pRelaySending: 'Relaying…',
    op2pRelayed: 'Relayed', op2pRelayFailed: 'Failed',
    op2pNoAlerts: 'No alerts to relay yet.',
    op2pTwoPhone: 'Two-phone story', op2pTwoPhoneHint: 'One phone offline — the alert still arrives.',
    op2pFailHop: 'Simulate a failed hop',
    op2pLogTitle: 'Relay log',
    op2pDemoOnlyNote: 'Demo mode only',
    op2pThisPhone: 'This phone', op2pNearbyPhone: 'Nearby phone',
    op2pNotDemo: 'Switch to demo mode to run the relay.',
    op2pMeshNote: 'Demo mesh — no real phone radio yet.',
    op2pRetry: 'Try again',
    // --- Worker 5 (offline + P2P testability) ---------------------------------
    // Shell-readiness honesty + the built-in offline simulator + two-tab relay
    // arrival note. Machine codes (SIMULATED, severities) stay untranslated.
    op2pShellSaved: 'App shell saved for offline',
    op2pShellNotSaved: 'Shell not saved yet — open the app once while online',
    op2pShellChecking: 'Checking app shell…',
    op2pSimulateOffline: 'Simulate offline',
    op2pSimulateOfflineNote: 'Cuts the network path in-app, so offline states can be tested without touching the phone.',
    op2pRelayArrived: 'Relay arrived from another tab.',
  },
  hi: {
    op2pTitle: 'ऑफ़लाइन व नज़दीकी',
    op2pSub: 'बिना इंटरनेट यह फ़ोन क्या जानता है — और अलर्ट फ़ोन-से-फ़ोन कैसे पहुँचता है।',
    op2pConnOnline: 'ऑनलाइन', op2pConnOffline: 'ऑफ़लाइन',
    op2pCheckedWeather: 'मौसम', op2pCheckedAlerts: 'अलर्ट',
    op2pCheckedAdvice: 'सलाह', op2pCheckedNotifications: 'सूचनाएँ',
    op2pNoCache: 'अभी कुछ सहेजा नहीं',
    agoNow: 'अभी जाँचा', agoMin: '{n} मि. पहले जाँचा',
    agoHour: '{n} घं. पहले जाँचा', agoDay: '{n} दिन पहले जाँचा',
    op2pQueueTitle: 'प्रतीक्षारत प्रश्न', op2pQueueEmpty: 'कोई प्रतीक्षारत प्रश्न नहीं।',
    op2pQueueReplay: 'अभी भेजें', op2pQueueReplaying: 'भेज रहे हैं…',
    op2pQueueDone: '{n} भेजे', op2pQueueOfflineNote: 'अभी ऑफ़लाइन — कनेक्ट होते ही भेजे जाएँगे।',
    op2pQueuedChip: 'कतार में',
    op2pTransTitle: 'सहेजे डेटा से अलर्ट बदलाव',
    op2pTransEmpty: 'पिछली जाँच के बाद कोई बदलाव नहीं।',
    op2pTransCachedNote: 'सहेजे डेटा से — दोबारा जाँच नहीं हो सकी।',
    op2pTrPreAlert: 'पूर्व-चेतावनी शुरू', op2pTrActive: 'अलर्ट सक्रिय', op2pTrEnded: 'अलर्ट समाप्त',
    op2pP2pTitle: 'फ़ोन-से-फ़ोन अलर्ट रिले',
    op2pRelayBtn: 'अलर्ट रिले करें', op2pRelaySending: 'रिले हो रहा…',
    op2pRelayed: 'रिले हुआ', op2pRelayFailed: 'विफल',
    op2pNoAlerts: 'रिले के लिए अभी कोई अलर्ट नहीं।',
    op2pTwoPhone: 'दो-फ़ोन कहानी', op2pTwoPhoneHint: 'एक फ़ोन ऑफ़लाइन — अलर्ट फिर भी पहुँचता है।',
    op2pFailHop: 'विफल हॉप दिखाएँ',
    op2pLogTitle: 'रिले लॉग',
    op2pDemoOnlyNote: 'केवल डेमो मोड',
    op2pThisPhone: 'यह फ़ोन', op2pNearbyPhone: 'नज़दीकी फ़ोन',
    op2pNotDemo: 'रिले चलाने के लिए डेमो मोड पर जाएँ।',
    op2pMeshNote: 'डेमो जाल — असली फ़ोन रेडियो अभी नहीं।',
    op2pRetry: 'फिर कोशिश करें',
    // --- Worker 5 (offline + P2P testability) ---------------------------------
    op2pShellSaved: 'ऐप शेल ऑफ़लाइन के लिए सहेजा गया',
    op2pShellNotSaved: 'शेल अभी सहेजा नहीं — ऑनलाइन एक बार खोलें',
    op2pShellChecking: 'ऐप शेल जाँच रहे…',
    op2pSimulateOffline: 'ऑफ़लाइन दिखाएँ',
    op2pSimulateOfflineNote: 'फ़ोन छुए बिना ऑफ़लाइन स्थिति परखने के लिए ऐप में ही नेटवर्क काटता है।',
    op2pRelayArrived: 'दूसरे टैब से रिले आया।',
  },
  te: {
    op2pTitle: 'ఆఫ్‌లైన్ & సమీపం',
    op2pSub: 'ఇంటర్నెట్ లేకుండా ఈ ఫోన్‌కు తెలిసినది — అలర్ట్ ఫోన్-నుండి-ఫోన్‌కు ఎలా వెళ్తుందో.',
    op2pConnOnline: 'ఆన్‌లైన్', op2pConnOffline: 'ఆఫ్‌లైన్',
    op2pCheckedWeather: 'వాతావరణం', op2pCheckedAlerts: 'అలర్ట్‌లు',
    op2pCheckedAdvice: 'సలహా', op2pCheckedNotifications: 'నోటిఫికేషన్‌లు',
    op2pNoCache: 'ఇంకా ఏమీ భద్రపరచలేదు',
    agoNow: 'ఇప్పుడే తనిఖీ చేసాం', agoMin: '{n} నిమి. క్రితం తనిఖీ',
    agoHour: '{n} గం. క్రితం తనిఖీ', agoDay: '{n} రోజుల క్రితం తనిఖీ',
    op2pQueueTitle: 'వేచి ఉన్న ప్రశ్నలు', op2pQueueEmpty: 'వేచి ఉన్న ప్రశ్నలు లేవు.',
    op2pQueueReplay: 'ఇప్పుడు పంపు', op2pQueueReplaying: 'పంపుతోంది…',
    op2pQueueDone: '{n} పంపాం', op2pQueueOfflineNote: 'ఇంకా ఆఫ్‌లైన్ — కనెక్ట్ అయ్యాక పంపుతాం.',
    op2pQueuedChip: 'క్యూలో',
    op2pTransTitle: 'భద్రపరిచిన డేటా నుండి అలర్ట్ మార్పులు',
    op2pTransEmpty: 'గత తనిఖీ తర్వాత మార్పు లేదు.',
    op2pTransCachedNote: 'భద్రపరిచిన డేటా నుండి — మళ్లీ తనిఖీ చేయలేకపోయాం.',
    op2pTrPreAlert: 'ముందస్తు హెచ్చరిక మొదలైంది', op2pTrActive: 'అలర్ట్ యాక్టివ్', op2pTrEnded: 'అలర్ట్ ముగిసింది',
    op2pP2pTitle: 'ఫోన్-నుండి-ఫోన్ అలర్ట్ రిలే',
    op2pRelayBtn: 'అలర్ట్ రిలే చేయి', op2pRelaySending: 'రిలే అవుతోంది…',
    op2pRelayed: 'రిలే అయింది', op2pRelayFailed: 'విఫలమైంది',
    op2pNoAlerts: 'రిలే చేయడానికి అలర్ట్‌లు లేవు.',
    op2pTwoPhone: 'రెండు-ఫోన్ కథ', op2pTwoPhoneHint: 'ఒక ఫోన్ ఆఫ్‌లైన్ — అలర్ట్ అయినా చేరుతుంది.',
    op2pFailHop: 'విఫల హాప్ చూపించు',
    op2pLogTitle: 'రిలే లాగ్',
    op2pDemoOnlyNote: 'డెమో మోడ్ మాత్రమే',
    op2pThisPhone: 'ఈ ఫోన్', op2pNearbyPhone: 'సమీప ఫోన్',
    op2pNotDemo: 'రిలే నడపడానికి డెమో మోడ్‌కు మారండి.',
    op2pMeshNote: 'డెమో మెష్ — నిజమైన ఫోన్ రేడియో ఇంకా లేదు.',
    op2pRetry: 'మళ్లీ ప్రయత్నించు',
    // --- Worker 5 (offline + P2P testability) ---------------------------------
    op2pShellSaved: 'యాప్ షెల్ ఆఫ్‌లైన్ కోసం భద్రపరచబడింది',
    op2pShellNotSaved: 'షెల్ ఇంకా భద్రపరచలేదు — ఆన్‌లైన్‌లో ఒకసారి తెరవండి',
    op2pShellChecking: 'యాప్ షెల్ తనిఖీ చేస్తున్నాం…',
    op2pSimulateOffline: 'ఆఫ్‌లైన్ అనుకరించు',
    op2pSimulateOfflineNote: 'ఫోన్‌ను తాకకుండా ఆఫ్‌లైన్ స్థితులను పరీక్షించడానికి యాప్‌లోనే నెట్‌వర్క్‌ను నిలిపివేస్తుంది.',
    op2pRelayArrived: 'మరో ట్యాబ్ నుండి రిలే వచ్చింది.',
  },
};
