// QR P2P relay strings. EN/HI/TE. Machine codes (P2P, hop counts,
// checksums) stay untranslated. Copy stays short — icon-first.
export default {
  en: {
    qrTitle: 'QR relay — zero internet needed',
    qrSub: 'Show this phone\u2019s alert as QR codes. Any nearby phone scans them — no internet, no pairing.',
    qrScanTitle: 'Scan a relay QR',
    qrScanSub: 'Point the camera at the other phone\u2019s QR code. Frames assemble automatically.',
    qrShowTab: 'Show QR', qrScanTab: 'Scan QR',
    qrPickAlert: 'Alert to share',
    qrNoAlerts: 'No saved alert to share yet. Open the app once while online so this phone has an alert.',
    qrFrameOf: 'Frame {i} of {n}',
    qrKeepSteady: 'Keep the code steady — frames rotate automatically.',
    qrHopChip: 'Hop {hops} of {limit}',
    qrHopRefused: 'Hop limit reached ({limit}) — this phone will not relay further.',
    qrTooLarge: 'Alert too large to fit in QR codes.',
    qrStartCam: 'Start camera',
    qrStopCam: 'Stop camera',
    qrCamDenied: 'Camera blocked. Allow camera access in the browser, then try again.',
    qrCamNeedHttps: 'Camera needs a secure page (https) or localhost.',
    qrProgress: '{r} of {n} frames scanned',
    qrBadCode: 'That QR is not a SAARTHI relay code — ignored.',
    qrChecksumFail: 'Frames do not match (checksum failed). Ask the sender to show the code again.',
    qrReceived: 'Alert received via P2P relay',
    qrReceivedSub: 'Phone-to-phone — could not verify with the server. Check again when online.',
    qrViaP2p: 'Via P2P relay',
    qrAckQueued: 'Acknowledgement queued — it will send when this phone is back online.',
    qrAckSync: 'Send now',
    qrAckSynced: 'Acknowledgement sent.',
    qrAckPending: '{n} acknowledgement(s) waiting to send',
    qrOfficialKept: 'Official',
    qrCommunityKept: 'Community',
    qrRelayAgain: 'Relay this further',
    qrNewScan: 'Scan another',
    qrNoCamera: 'No camera found on this device.',
  },
  hi: {
    qrTitle: 'QR रिले — बिना इंटरनेट',
    qrSub: 'इस फ़ोन के अलर्ट को QR कोड में दिखाएँ। पास का कोई भी फ़ोन स्कैन करे — इंटरनेट या पेयरिंग नहीं चाहिए।',
    qrScanTitle: 'रिले QR स्कैन करें',
    qrScanSub: 'कैमरा दूसरे फ़ोन के QR कोड पर रखें। फ़्रेम अपने आप जुड़ जाएँगे।',
    qrShowTab: 'QR दिखाएँ', qrScanTab: 'QR स्कैन करें',
    qrPickAlert: 'साझा करने वाला अलर्ट',
    qrNoAlerts: 'साझा करने के लिए कोई सहेजा अलर्ट नहीं। ऑनलाइन रहते एक बार ऐप खोलें।',
    qrFrameOf: 'फ़्रेम {i} / {n}',
    qrKeepSteady: 'कोड स्थिर रखें — फ़्रेम अपने आप बदलते हैं।',
    qrHopChip: 'हॉप {hops} / {limit}',
    qrHopRefused: 'हॉप सीमा पूरी ({limit}) — यह फ़ोन आगे रिले नहीं करेगा।',
    qrTooLarge: 'अलर्ट QR कोड में नहीं समा रहा।',
    qrStartCam: 'कैमरा चालू करें',
    qrStopCam: 'कैमरा बंद करें',
    qrCamDenied: 'कैमरा अवरुद्ध है। ब्राउज़र में अनुमति दें, फिर दोबारा कोशिश करें।',
    qrCamNeedHttps: 'कैमरे के लिए सुरक्षित पेज (https) या localhost चाहिए।',
    qrProgress: '{r} / {n} फ़्रेम स्कैन हुए',
    qrBadCode: 'यह SAARTHI रिले कोड नहीं है — अनदेखा किया।',
    qrChecksumFail: 'फ़्रेम मेल नहीं खा रहे। भेजने वाले से कोड फिर दिखाने को कहें।',
    qrReceived: 'P2P रिले से अलर्ट मिला',
    qrReceivedSub: 'फ़ोन-से-फ़ोन — सर्वर से सत्यापित नहीं हो सका। ऑनलाइन आकर दोबारा जाँचें।',
    qrViaP2p: 'P2P रिले द्वारा',
    qrAckQueued: 'पावती कतार में — फ़ोन ऑनलाइन आते ही भेजी जाएगी।',
    qrAckSync: 'अभी भेजें',
    qrAckSynced: 'पावती भेजी गई।',
    qrAckPending: '{n} पावती भेजनी बाकी',
    qrOfficialKept: 'आधिकारिक',
    qrCommunityKept: 'सामुदायिक',
    qrRelayAgain: 'इसे आगे रिले करें',
    qrNewScan: 'और स्कैन करें',
    qrNoCamera: 'इस डिवाइस में कैमरा नहीं मिला।',
  },
  te: {
    qrTitle: 'QR రిలే — ఇంటర్నెట్ అవసరం లేదు',
    qrSub: 'ఈ ఫోన్ అలర్ట్‌ను QR కోడ్‌లుగా చూపండి. దగ్గర్లోని ఏ ఫోనైనా స్కాన్ చేయవచ్చు — ఇంటర్నెట్, పేయిరింగ్ అవసరం లేదు.',
    qrScanTitle: 'రిలే QR స్కాన్ చేయండి',
    qrScanSub: 'కెమెరాను మరో ఫోన్ QR కోడ్‌పై ఉంచండి. ఫ్రేమ్‌లు తమంతట తాము కలుస్తాయి.',
    qrShowTab: 'QR చూపు', qrScanTab: 'QR స్కాన్',
    qrPickAlert: 'షేర్ చేయాల్సిన అలర్ట్',
    qrNoAlerts: 'షేర్ చేయడానికి సేవ్ చేసిన అలర్ట్ లేదు. ఆన్‌లైన్‌లో ఒకసారి యాప్ తెరవండి.',
    qrFrameOf: 'ఫ్రేమ్ {i} / {n}',
    qrKeepSteady: 'కోడ్‌ను స్థిరంగా ఉంచండి — ఫ్రేమ్‌లు తమంతట తాము మారుతాయి.',
    qrHopChip: 'హాప్ {hops} / {limit}',
    qrHopRefused: 'హాప్ పరిమితి పూర్తి ({limit}) — ఈ ఫోన్ ఇక రిలే చేయదు.',
    qrTooLarge: 'అలర్ట్ QR కోడ్‌లలో పట్టడం లేదు.',
    qrStartCam: 'కెమెరా ఆన్ చేయండి',
    qrStopCam: 'కెమెరా ఆఫ్ చేయండి',
    qrCamDenied: 'కెమెరా బ్లాక్ చేయబడింది. బ్రౌజర్‌లో అనుమతి ఇచ్చి మళ్లీ ప్రయత్నించండి.',
    qrCamNeedHttps: 'కెమెరాకు సురక్షిత పేజీ (https) లేదా localhost కావాలి.',
    qrProgress: '{r} / {n} ఫ్రేమ్‌లు స్కాన్ అయ్యాయి',
    qrBadCode: 'ఇది SAARTHI రిలే కోడ్ కాదు — విస్మరించాం.',
    qrChecksumFail: 'ఫ్రేమ్‌లు సరిపోలడం లేదు. పంపినవారిని కోడ్ మళ్లీ చూపమనండి.',
    qrReceived: 'P2P రిలే ద్వారా అలర్ట్ వచ్చింది',
    qrReceivedSub: 'ఫోన్-నుండి-ఫోన్ — సర్వర్‌తో ధృవీకరించలేకపోయాం. ఆన్‌లైన్‌కు వచ్చాక మళ్లీ చూడండి.',
    qrViaP2p: 'P2P రిలే ద్వారా',
    qrAckQueued: 'అక్నాలెడ్జ్‌మెంట్ క్యూలో — ఫోన్ ఆన్‌లైన్‌కు రాగానే పంపుతాం.',
    qrAckSync: 'ఇప్పుడు పంపు',
    qrAckSynced: 'అక్నాలెడ్జ్‌మెంట్ పంపాం.',
    qrAckPending: '{n} అక్నాలెడ్జ్‌మెంట్‌లు పెండింగ్',
    qrOfficialKept: 'అధికారిక',
    qrCommunityKept: 'సామూహిక',
    qrRelayAgain: 'దీన్ని ముందుకు రిలే చేయండి',
    qrNewScan: 'మరొకటి స్కాన్ చేయండి',
    qrNoCamera: 'ఈ పరికరంలో కెమెరా లేదు.',
  },
};
