// Settings "About you" (ProfileDetails.jsx) and the advice-asking chat chips.
// Chip VALUES are stored in English for the backend; these are only labels.
export default {
  en: {
    pfNote: 'Optional. The chat uses these to give answers and advice that fit you. Saved only on this phone.',
    pfCrop: 'Your crop', pfCropPh: 'Other crop (type it)',
    pfPaddy: 'Paddy', pfCotton: 'Cotton', pfChilli: 'Chilli', pfMaize: 'Maize', pfGroundnut: 'Groundnut', pfVegetables: 'Vegetables',
    pfStage: 'Crop stage', pfSowing: 'Sowing', pfGrowing: 'Growing', pfFlowering: 'Flowering', pfHarvest: 'Harvest',
    pfLand: 'Your land', pfIrrigated: 'Irrigated', pfRainfed: 'Rain-fed',
    pfBoat: 'Your boat', pfCountryBoat: 'Country boat (no motor)', pfMotorBoat: 'Small motor boat', pfTrawler: 'Mechanised trawler',
    pfTrip: 'Usual trip', pfDayTrip: 'Day trip', pfOvernight: 'Overnight', pfManyDays: 'Many days at sea',
    pfVehicle: 'Your vehicle', pfTwoWheeler: 'Two-wheeler', pfCar: 'Car or auto', pfTruck: 'Truck', pfBus: 'Bus',
    pfRoute: 'Usual route', pfRoutePh: 'e.g. Hyderabad to Vijayawada highway',
    pfAircraft: 'What you fly', pfDrone: 'Drone', pfLight: 'Light aircraft', pfCommercial: 'Commercial flight',
    pfHours: 'When you are usually outside', pfMorning: 'Morning', pfAfternoon: 'Afternoon', pfEvening: 'Evening', pfNight: 'Night',
    pfHealth: 'Anyone who needs extra care', pfElderly: 'Elderly person at home', pfChildren: 'Small children',
    pfAsthma: 'Asthma or breathing trouble', pfHeart: 'Heart or BP condition', pfPregnant: 'Pregnant',
    pfNotes: 'Anything else the chat should know', pfNotesPh: 'e.g. I sell vegetables at the market at 6 am',
    qSpray: 'Can I spray pesticide today?',
    qSeaTomorrow: 'Can I go fishing tomorrow morning?',
    qUmbrella: 'Should I carry an umbrella today?',
    qCommute: 'Will rain affect my commute this evening?',
    qSchool: 'Is the weather okay for school travel tomorrow?',
    qOutdoor: 'What are the safest hours to work outside today?',
  },
  hi: {
    pfNote: 'वैकल्पिक। चैट इनसे आपके हिसाब से उत्तर और सलाह देती है। सिर्फ़ इसी फ़ोन में सेव होता है।',
    pfCrop: 'आपकी फ़सल', pfCropPh: 'दूसरी फ़सल (लिखें)',
    pfPaddy: 'धान', pfCotton: 'कपास', pfChilli: 'मिर्च', pfMaize: 'मक्का', pfGroundnut: 'मूंगफली', pfVegetables: 'सब्ज़ियाँ',
    pfStage: 'फ़सल की अवस्था', pfSowing: 'बुवाई', pfGrowing: 'बढ़वार', pfFlowering: 'फूल आना', pfHarvest: 'कटाई',
    pfLand: 'आपकी ज़मीन', pfIrrigated: 'सिंचित', pfRainfed: 'बारिश पर निर्भर',
    pfBoat: 'आपकी नाव', pfCountryBoat: 'देसी नाव (बिना मोटर)', pfMotorBoat: 'छोटी मोटर नाव', pfTrawler: 'मशीनी ट्रॉलर',
    pfTrip: 'आम यात्रा', pfDayTrip: 'दिन भर', pfOvernight: 'रात भर', pfManyDays: 'कई दिन समुद्र में',
    pfVehicle: 'आपका वाहन', pfTwoWheeler: 'दोपहिया', pfCar: 'कार या ऑटो', pfTruck: 'ट्रक', pfBus: 'बस',
    pfRoute: 'आम रास्ता', pfRoutePh: 'जैसे हैदराबाद से विजयवाड़ा हाईवे',
    pfAircraft: 'आप क्या उड़ाते हैं', pfDrone: 'ड्रोन', pfLight: 'हल्का विमान', pfCommercial: 'व्यावसायिक उड़ान',
    pfHours: 'आप आमतौर पर बाहर कब रहते हैं', pfMorning: 'सुबह', pfAfternoon: 'दोपहर', pfEvening: 'शाम', pfNight: 'रात',
    pfHealth: 'किसे ज़्यादा देखभाल चाहिए', pfElderly: 'घर में बुज़ुर्ग', pfChildren: 'छोटे बच्चे',
    pfAsthma: 'दमा या साँस की तकलीफ़', pfHeart: 'दिल या बीपी की बीमारी', pfPregnant: 'गर्भवती',
    pfNotes: 'चैट को और क्या पता होना चाहिए', pfNotesPh: 'जैसे मैं सुबह 6 बजे बाज़ार में सब्ज़ी बेचता हूँ',
    qSpray: 'क्या आज कीटनाशक छिड़क सकता हूँ?',
    qSeaTomorrow: 'क्या कल सुबह मछली पकड़ने जा सकता हूँ?',
    qUmbrella: 'क्या आज छाता ले जाना चाहिए?',
    qCommute: 'क्या आज शाम बारिश से आने-जाने में दिक्कत होगी?',
    qSchool: 'क्या कल स्कूल जाने के लिए मौसम ठीक है?',
    qOutdoor: 'आज बाहर काम करने के सबसे सुरक्षित घंटे कौन से हैं?',
  },
  te: {
    pfNote: 'ఐచ్ఛికం. వీటితో చాట్ మీకు తగిన సమాధానాలు, సలహా ఇస్తుంది. ఈ ఫోన్‌లో మాత్రమే సేవ్ అవుతుంది.',
    pfCrop: 'మీ పంట', pfCropPh: 'ఇతర పంట (టైప్ చేయండి)',
    pfPaddy: 'వరి', pfCotton: 'పత్తి', pfChilli: 'మిరప', pfMaize: 'మొక్కజొన్న', pfGroundnut: 'వేరుశనగ', pfVegetables: 'కూరగాయలు',
    pfStage: 'పంట దశ', pfSowing: 'విత్తనం', pfGrowing: 'పెరుగుదల', pfFlowering: 'పూత', pfHarvest: 'కోత',
    pfLand: 'మీ భూమి', pfIrrigated: 'నీటిపారుదల', pfRainfed: 'వర్షాధారం',
    pfBoat: 'మీ పడవ', pfCountryBoat: 'నాటు పడవ (మోటారు లేదు)', pfMotorBoat: 'చిన్న మోటారు పడవ', pfTrawler: 'యాంత్రిక ట్రాలర్',
    pfTrip: 'సాధారణ ప్రయాణం', pfDayTrip: 'ఒక రోజు', pfOvernight: 'రాత్రంతా', pfManyDays: 'చాలా రోజులు సముద్రంలో',
    pfVehicle: 'మీ వాహనం', pfTwoWheeler: 'ద్విచక్ర వాహనం', pfCar: 'కారు లేదా ఆటో', pfTruck: 'లారీ', pfBus: 'బస్సు',
    pfRoute: 'సాధారణ మార్గం', pfRoutePh: 'ఉదా. హైదరాబాద్ నుండి విజయవాడ హైవే',
    pfAircraft: 'మీరు ఏది నడుపుతారు', pfDrone: 'డ్రోన్', pfLight: 'చిన్న విమానం', pfCommercial: 'వాణిజ్య విమానం',
    pfHours: 'మీరు సాధారణంగా బయట ఎప్పుడు ఉంటారు', pfMorning: 'ఉదయం', pfAfternoon: 'మధ్యాహ్నం', pfEvening: 'సాయంత్రం', pfNight: 'రాత్రి',
    pfHealth: 'ఎవరికి అదనపు జాగ్రత్త కావాలి', pfElderly: 'ఇంట్లో వృద్ధులు', pfChildren: 'చిన్న పిల్లలు',
    pfAsthma: 'ఆస్తమా లేదా శ్వాస సమస్య', pfHeart: 'గుండె లేదా బీపీ సమస్య', pfPregnant: 'గర్భిణి',
    pfNotes: 'చాట్‌కు ఇంకా ఏం తెలియాలి', pfNotesPh: 'ఉదా. నేను ఉదయం 6 గంటలకు మార్కెట్‌లో కూరగాయలు అమ్ముతాను',
    qSpray: 'ఈ రోజు పురుగుమందు పిచికారీ చేయవచ్చా?',
    qSeaTomorrow: 'రేపు ఉదయం చేపల వేటకు వెళ్లవచ్చా?',
    qUmbrella: 'ఈ రోజు గొడుగు తీసుకెళ్లాలా?',
    qCommute: 'ఈ సాయంత్రం వర్షం నా ప్రయాణాన్ని ప్రభావితం చేస్తుందా?',
    qSchool: 'రేపు స్కూల్‌కు వెళ్లడానికి వాతావరణం బాగుందా?',
    qOutdoor: 'ఈ రోజు బయట పని చేయడానికి సురక్షితమైన సమయం ఏది?',
  },
};
