// Round2 strings: Notification Center, Advisor, Admin panel, Coverage.
// EN/HI/TE. Machine-readable codes (RED/ORANGE, state ids) are never translated.
export default {
  en: {
    navNotifications: 'Notifications', navAdvisor: 'Advisor', navAdmin: 'Authorities console',
    ntfTitle: 'Notifications', ntfSub: 'Everything SAARTHI sent you — alerts, updates and all-clears — even while the app was closed.',
    advEyebrow: 'Advisory',
    ntfEmpty: 'No notifications yet. When an alert is issued for your district, its whole lifecycle lands here.',
    ntfLoadFailed: 'Could not load notifications (offline?). Cached alerts are still on the Alerts page.',
    ntfMarkRead: 'Mark read', ntfReadAll: 'Mark all read',
    ntfAck: 'Acknowledge', ntfAcked: 'Acknowledged', ntfAckTitle: 'Confirm you received this alert',
    ntfViewAlerts: 'View alerts',
    ntfFilterAll: 'All', ntfFilterUnread: 'Unread', ntfFilterAlerts: 'Alerts',
    ntfToday: 'Today', ntfYesterday: 'Yesterday', ntfEarlier: 'Earlier',
    ntfDelivery: 'push delivered',
    advTitle: 'Advice for every role', advSub: 'The same weather, the advice that fits YOU. Pick who you are; the guidance changes with it.',
    advNote: 'Grounded in the official alert verdict — never an AI guess. Occupational advice is general guidance, not an official instruction.',
    advWxBasis: 'Based on', advWxTemp: '{v}°C', advWxHumidity: '{v}% humidity',
    advWxRain: '{v} mm rain', advWxWind: '{v} kph wind',
    advWxAlertOne: 'active alert', advWxAlertMany: 'active alerts',
    advWxUnavailable: 'Weather data unavailable — advice based on alerts only',
    advSwitchNote: 'Tapping a card sets your role for the whole app.',
    utYou: 'you', utGeneral: 'General citizen', utFarmer: 'Farmer', utDriver: 'Driver',
    utFisherman: 'Fisherman', utAviation: 'Aviation', utCommuter: 'Commuter', utEmployee: 'Office worker',
    utOutdoor: 'Outdoor worker', utStudent: 'Student', utResearch: 'Researcher', utDisaster: 'Emergency official',
    adminTitle: 'Authority console', adminSub: 'Data-source mode, and how far alerts travelled.',
    covDistrictTitle: 'Alert coverage — district view', covNote: 'How effectively the alert reached the affected population: delivery, opening, acknowledgement, offline and P2P counts. Communication visibility — not a safety count.',
    covEmpty: 'No delivery data yet. Push deliveries and acknowledgements appear here as devices report them.',
    covReached: 'Reached', covDelivered: 'Delivered',
    covOpened: 'Opened', covAck: 'Acknowledged', covP2P: 'P2P relayed',
    covPending: 'Pending', covOffline: 'Offline', covUnreach: 'Unreachable',
    covAllDistricts: 'All districts', covTotalSent: 'Total sent',
    covDeliveryRate: 'Delivery rate', covAckRate: 'Acknowledgement rate',
    covZoneBreakdown: 'Zone breakdown',
  },
  hi: {
    navNotifications: 'सूचनाएँ', navAdvisor: 'सलाहकार', navAdmin: 'प्रशासन कंसोल',
    ntfTitle: 'सूचनाएँ', ntfSub: 'SAARTHI ने आपको जो कुछ भेजा — अलर्ट, अपडेट और अलर्ट-समाप्ति — ऐप बंद होने पर भी।',
    advEyebrow: 'परामर्श',
    ntfEmpty: 'अभी कोई सूचना नहीं। आपके जिले का अलर्ट आते ही उसका पूरा चक्र यहाँ दिखेगा।',
    ntfLoadFailed: 'सूचनाएँ लोड नहीं हुईं (ऑफ़लाइन?)। पुराने अलर्ट Alerts पेज पर हैं।',
    ntfMarkRead: 'पढ़ा हुआ मार्क करें', ntfReadAll: 'सभी पढ़ा हुआ मार्क करें',
    ntfAck: 'प्राप्ति दर्ज करें', ntfAcked: 'प्राप्ति दर्ज', ntfAckTitle: 'पुष्टि करें कि अलर्ट मिला',
    ntfViewAlerts: 'अलर्ट देखें',
    ntfFilterAll: 'सभी', ntfFilterUnread: 'अपठित', ntfFilterAlerts: 'अलर्ट',
    ntfToday: 'आज', ntfYesterday: 'कल', ntfEarlier: 'पहले',
    ntfDelivery: 'पुश पहुँचे',
    advTitle: 'हर भूमिका के लिए सलाह', advSub: 'वही मौसम, आपके लिए सही सलाह। अपनी भूमिका चुनें; सलाह बदल जाएगी।',
    advNote: 'सरकारी अलर्ट निर्णय पर आधारित — AI अंदाज़ा नहीं। व्यावसायिक सलाह सामान्य मार्गदर्शन है, सरकारी आदेश नहीं।',
    advWxBasis: 'आधार', advWxTemp: '{v}°C', advWxHumidity: '{v}% आर्द्रता',
    advWxRain: '{v} मिमी वर्षा', advWxWind: '{v} किमी/घंटा हवा',
    advWxAlertOne: 'सक्रिय अलर्ट', advWxAlertMany: 'सक्रिय अलर्ट',
    advWxUnavailable: 'मौसम डेटा उपलब्ध नहीं — सलाह केवल अलर्ट पर आधारित',
    advSwitchNote: 'किसी कार्ड को दबाने से पूरे ऐप में आपकी भूमिका बदल जाती है।',
    utYou: 'आप', utGeneral: 'आम नागरिक', utFarmer: 'किसान', utDriver: 'ड्राइवर',
    utFisherman: 'मछुआरा', utAviation: 'विमानन', utCommuter: 'यात्री', utEmployee: 'कर्मचारी',
    utOutdoor: 'बाहरी काम करने वाले', utStudent: 'छात्र', utResearch: 'शोधकर्ता', utDisaster: 'आपदा अधिकारी',
    adminTitle: 'प्राधिकरण कंसोल', adminSub: 'डेटा-स्रोत मोड, और अलर्ट कितनी दूर पहुँचे।',
    covDistrictTitle: 'अलर्ट कवरेज — जिला दृश्य', covNote: 'चेतावनी प्रभावित जनसंख्या तक कितनी पहुँची: डिलीवरी, खोलना, प्राप्ति, ऑफ़लाइन और P2P संख्या। संचार दृश्यता — सुरक्षा गिनती नहीं।',
    covEmpty: 'अभी कोई डिलीवरी डेटा नहीं। डिवाइसों से रिपोर्ट आते ही पुश डिलीवरी और प्राप्ति यहाँ दिखेंगी।',
    covReached: 'पहुँचे', covDelivered: 'पहुँच गया',
    covOpened: 'खोला', covAck: 'प्राप्ति दर्ज', covP2P: 'P2P रिले',
    covPending: 'लंबित', covOffline: 'ऑफ़लाइन', covUnreach: 'अप्राप्य',
    covAllDistricts: 'सभी जिले', covTotalSent: 'कुल भेजे गए',
    covDeliveryRate: 'डिलीवरी दर', covAckRate: 'प्राप्ति दर्ज दर',
    covZoneBreakdown: 'क्षेत्रवार विवरण',
  },
  te: {
    navNotifications: 'నోటిఫికేషన్లు', navAdvisor: 'సలహాదారు', navAdmin: 'అధికార కన్సోల్',
    ntfTitle: 'నోటిఫికేషన్లు', ntfSub: 'SAARTHI పంపినవన్నీ — అలర్ట్‌లు, అప్‌డేట్‌లు, ముగింపు — యాప్ మూసివేసినప్పుడు కూడా.',
    advEyebrow: 'సలహా',
    ntfEmpty: 'ఇంకా నోటిఫికేషన్లు లేవు. మీ జిల్లా అలర్ట్ వస్తే దాని పూర్తి చక్రం ఇక్కడ కనిపిస్తుంది.',
    ntfLoadFailed: 'నోటిఫికేషన్లు లోడ్ కాలేదు (ఆఫ్‌లైన్?). పాత అలర్ట్‌లు Alerts పేజీలో ఉన్నాయి.',
    ntfMarkRead: 'చదివినట్టు గుర్తించు', ntfReadAll: 'అన్నీ చదివినట్టు గుర్తించు',
    ntfAck: 'స్వీకారం నమోదు', ntfAcked: 'స్వీకారం నమోదైంది', ntfAckTitle: 'అలర్ట్ అందిందని నిర్ధారించండి',
    ntfViewAlerts: 'అలర్ట్‌లు చూడండి',
    ntfFilterAll: 'అన్నీ', ntfFilterUnread: 'చదవనివి', ntfFilterAlerts: 'అలర్ట్‌లు',
    ntfToday: 'ఈరోజు', ntfYesterday: 'నిన్న', ntfEarlier: 'ఇంకా',
    ntfDelivery: 'పుష్ చేరింది',
    advTitle: 'ప్రతి పాత్రకు సలహా', advSub: 'ఒకే వాతావరణం, మీకు సరైన సలహా. మీ పాత్రను ఎంచుకోండి; సలహా మారుతుంది.',
    advNote: 'అధికారిక అలర్ట్ తీర్పు మీద ఆధారపడినది — AI ఊహ కాదు. వృత్తి సలహా సాధారణ మార్గదర్శకం, అధికారిక ఆదేశం కాదు.',
    advWxBasis: 'ఆధారం', advWxTemp: '{v}°C', advWxHumidity: '{v}% తేమ',
    advWxRain: '{v} మిమీ వర్షం', advWxWind: '{v} కిమీ/గం గాలి',
    advWxAlertOne: 'యాక్టివ్ అలర్ట్', advWxAlertMany: 'యాక్టివ్ అలర్ట్‌లు',
    advWxUnavailable: 'వాతావరణ డేటా అందుబాటులో లేదు — సలహా అలర్ట్‌లపైనే ఆధారపడింది',
    advSwitchNote: 'కార్డు నొక్కితే మొత్తం యాప్‌లో మీ పాత్ర మారుతుంది.',
    utYou: 'మీరు', utGeneral: 'సామాన్య పౌరుడు', utFarmer: 'రైతు', utDriver: 'డ్రైవర్',
    utFisherman: 'మత్స్యకారుడు', utAviation: 'విమానయానం', utCommuter: 'ప్రయాణికుడు', utEmployee: 'ఉద్యోగి',
    utOutdoor: 'బహిరంగ కార్మికుడు', utStudent: 'విద్యార్థి', utResearch: 'పరిశోధకుడు', utDisaster: 'విపత్తు అధికారి',
    adminTitle: 'అధికార కన్సోల్', adminSub: 'డేటా-మూల మోడ్, మరియు అలర్ట్‌లు ఎంత దూరం ప్రయాణించాయి.',
    covDistrictTitle: 'అలర్ట్ కవరేజ్ — జిల్లా దృశ్యం', covNote: 'హెచ్చరిక ప్రభావిత ప్రజలకు ఎంత చేరింది: డెలివరీ, తెరవడం, స్వీకారం, ఆఫ్‌లైన్, P2P సంఖ్యలు. కమ్యూనికేషన్ దృశ్యత — భద్రతా లెక్క కాదు.',
    covEmpty: 'ఇంకా డెలివరీ డేటా లేదు. పరికరాలు నివేదించగానే పుష్ డెలివరీలు, స్వీకారాలు ఇక్కడ కనిపిస్తాయి.',
    covReached: 'చేరారు', covDelivered: 'చేరింది',
    covOpened: 'తెరిచారు', covAck: 'స్వీకారం', covP2P: 'P2P రిలే',
    covPending: 'పెండింగ్', covOffline: 'ఆఫ్‌లైన్', covUnreach: 'చేరలేదు',
    covAllDistricts: 'అన్ని జిల్లాలు', covTotalSent: 'మొత్తం పంపినవి',
    covDeliveryRate: 'డెలివరీ రేటు', covAckRate: 'ధృవీకరణ రేటు',
    covZoneBreakdown: 'జోన్ వారీ వివరాలు',
  },
};
