// Round2 strings: Notification Center, Advisor, Admin/Demo panel, Coverage.
// EN/HI/TE. Machine-readable codes (RED/ORANGE, state ids) are never translated.
export default {
  en: {
    navNotifications: 'Notifications', navAdvisor: 'Advisor', navAdmin: 'Demo & Authority',
    ntfTitle: 'Notifications', ntfSub: 'Everything SAARTHI sent you — alerts, updates and all-clears — even while the app was closed.',
    ntfToday: 'Today',
    advEyebrow: 'Advisory',
    ntfEmpty: 'No notifications yet. When an alert is issued for your district, its whole lifecycle lands here.',
    ntfLoadFailed: 'Could not load notifications (offline?). Cached alerts are still on the Alerts page.',
    ntfMarkRead: 'Mark read', ntfReadAll: 'Mark all read',
    ntfAck: 'Acknowledge', ntfAcked: 'Acknowledged', ntfAckTitle: 'Confirm you received this alert',
    ntfViewAlerts: 'View alerts',
    advTitle: 'Advisor', advSub: 'The same weather, the advice that fits YOU. Pick who you are; the guidance changes with it.',
    advNote: 'Grounded in the official alert verdict — never an AI guess. Occupational advice is general guidance, not an official instruction.',
    utYou: 'you', utGeneral: 'General citizen', utFarmer: 'Farmer', utDriver: 'Driver',
    utFisherman: 'Fisherman', utCommuter: 'Commuter', utEmployee: 'Office worker',
    utOutdoor: 'Outdoor worker', utStudent: 'Student', utResearch: 'Researcher', utDisaster: 'Emergency official',
    demoTitle: 'Demo control panel', demoSub: 'Create alerts, run the full lifecycle on stage, and seed the authority dashboard. Every button drives the real pipeline.',
    demoNeedDemoMode: 'The demo panel injects simulated alerts, so it only runs in DEMO mode — this keeps simulated alerts out of the live data chain. Your server is currently running in live/hybrid mode.',
    demoSwitchBtn: 'Switch to DEMO mode',
    demoScenarios: 'One-tap scenarios (auto pre-alert → active → ended in ~3 minutes)',
    demoScenarioHint: 'Scenario alerts schedule themselves: the pre-alert notification fires in seconds, the alert activates ~40s later, and the ended notification closes the loop — hands free for the pitch.',
    demoScenarioLaunched: 'Scenario launched', demoActiveTitle: 'Alerts in play',
    demoActiveSub: 'Move any alert through its lifecycle — each action notifies subscribers immediately.',
    demoEmpty: 'No demo alerts yet. Launch a scenario or create one below.',
    demoCreated: 'Alert created — notification sent', demoResent: 'Notification sent',
    demoRelay: 'P2P relay', demoRelayed: 'P2P relay delivered', demoSeed: 'Seed audience',
    demoSeeded: 'Simulated audience seeded', demoReset: 'Reset demo', demoResetDone: 'Demo reset',
    demoNotifyHint: 'Re-send the push for this state', demoResend: 'Notify',
    demoCreateTitle: 'Create alert', demoCreateSub: 'Times are minutes from NOW, so you can stage the lifecycle while you talk.',
    demoCreateGo: 'Create + notify', demoFTitle: 'Title', demoFHazard: 'Hazard',
    demoFSeverity: 'Severity', demoFPre: 'Pre-alert in', demoFStart: 'Active in',
    demoFEnd: 'Ends in', demoMin: 'min', demoFInstruction: 'Official instruction',
    stUpcoming: 'UPCOMING', stPreAlert: 'PRE-ALERT', stActive: 'ACTIVE', stUpdated: 'UPDATED',
    stExtended: 'EXTENDED', stEnded: 'ENDED', stCancelled: 'CANCELLED',
    actPre: 'Pre-alert', actActivate: 'Activate', actUpdate: 'Update', actExtend: 'Extend',
    actEnd: 'End alert', actCancel: 'Cancel',
    covTitle: 'Alert coverage — authority view', covNote: 'How effectively the alert reached the affected population: delivery, opening, acknowledgement, offline and P2P counts. Communication visibility — not a safety count.',
    covPick: 'Alert', covEmpty: 'No delivery data yet. Run a scenario, then seed an audience (or watch the real device).',
    covNeedsDemo: 'Coverage tracking follows the demo alert pipeline, so the dashboard is available in DEMO mode. Switch modes at the top banner to see it.',
    covRealTitle: 'Real devices', covSimTitle: 'Simulated audience',
    covSimLabel: 'SIMULATED', covReached: 'Reached', covDelivered: 'Delivered',
    covOpened: 'Opened', covAck: 'Acknowledged', covP2P: 'P2P relayed',
    covPending: 'Pending', covOffline: 'Offline', covUnreach: 'Unreachable',
    back: 'Back', demoHistory: 'Demo history', demoHistoryToggle: 'History',
    covAllDistricts: 'All districts', covTotalSent: 'Total sent',
    covDeliveryRate: 'Delivery rate', covAckRate: 'Acknowledgement rate',
    covZoneBreakdown: 'Zone breakdown',
  },
  hi: {
    navNotifications: 'सूचनाएँ', navAdvisor: 'सलाहकार', navAdmin: 'डेमो व प्रशासन',
    ntfTitle: 'सूचनाएँ', ntfSub: 'SAARTHI ने आपको जो कुछ भेजा — अलर्ट, अपडेट और अलर्ट-समाप्ति — ऐप बंद होने पर भी।',
    ntfToday: 'आज',
    advEyebrow: 'परामर्श',
    ntfEmpty: 'अभी कोई सूचना नहीं। आपके जिले का अलर्ट आते ही उसका पूरा चक्र यहाँ दिखेगा।',
    ntfLoadFailed: 'सूचनाएँ लोड नहीं हुईं (ऑफ़लाइन?)। पुराने अलर्ट Alerts पेज पर हैं।',
    ntfMarkRead: 'पढ़ा हुआ मार्क करें', ntfReadAll: 'सभी पढ़ा हुआ मार्क करें',
    ntfAck: 'प्राप्ति दर्ज करें', ntfAcked: 'प्राप्ति दर्ज', ntfAckTitle: 'पुष्टि करें कि अलर्ट मिला',
    ntfViewAlerts: 'अलर्ट देखें',
    advTitle: 'सलाहकार', advSub: 'वही मौसम, आपके लिए सही सलाह। अपनी भूमिका चुनें; सलाह बदल जाएगी।',
    advNote: 'सरकारी अलर्ट निर्णय पर आधारित — AI अंदाज़ा नहीं। व्यावसायिक सलाह सामान्य मार्गदर्शन है, सरकारी आदेश नहीं।',
    utYou: 'आप', utGeneral: 'आम नागरिक', utFarmer: 'किसान', utDriver: 'ड्राइवर',
    utFisherman: 'मछुआरा', utCommuter: 'यात्री', utEmployee: 'कर्मचारी',
    utOutdoor: 'बाहरी काम करने वाले', utStudent: 'छात्र', utResearch: 'शोधकर्ता', utDisaster: 'आपदा अधिकारी',
    demoTitle: 'डेमो नियंत्रण पैनल', demoSub: 'अलर्ट बनाएँ, पूरा जीवनचक्र दिखाएँ, और प्रशासनिक डैशबोर्ड भरें। हर बटन असली पाइपलाइन चलाता है।',
    demoNeedDemoMode: 'डेमो पैनल सिम्युलेटेड अलर्ट बनाता है, इसलिए यह केवल DEMO मोड में चलता है — इससे नकली अलर्ट लाइव डेटा में नहीं घुलते। आपका सर्वर अभी लाइव/हाइब्रिड मोड में है।',
    demoSwitchBtn: 'DEMO मोड में जाएँ',
    demoScenarios: 'एक-टैप परिदृश्य (~3 मिनट में प्री-अलर्ट → सक्रिय → समाप्त)',
    demoScenarioHint: 'परिदृश्य अलर्ट खुद चलते हैं: प्री-अलर्ट सेकंडों में, सक्रिय ~40 सेकंड में, और समाप्ति सूचना चक्र पूरा करती है — प्रेजेंटेशन के दौरान हाथ खाली।',
    demoScenarioLaunched: 'परिदृश्य शुरू', demoActiveTitle: 'चालू अलर्ट',
    demoActiveSub: 'किसी भी अलर्ट को जीवनचक्र से गुज़ारें — हर क्रिया तुरंत सूचित करती है।',
    demoEmpty: 'अभी कोई डेमो अलर्ट नहीं। नीचे से परिदृश्य चुनें या बनाएँ।',
    demoCreated: 'अलर्ट बना — सूचना भेजी गई', demoResent: 'सूचना भेजी गई',
    demoRelay: 'P2P रिले', demoRelayed: 'P2P रिले पहुँचा', demoSeed: 'ऑडियंस भरें',
    demoSeeded: 'सिम्युलेटेड ऑडियंस भरी गई', demoReset: 'डेमो रीसेट', demoResetDone: 'डेमो रीसेट',
    demoNotifyHint: 'इस स्थिति की सूचना दोबारा भेजें', demoResend: 'सूचित करें',
    demoCreateTitle: 'अलर्ट बनाएँ', demoCreateSub: 'समय अभी से मिनटों में — प्रेजेंटेशन के दौरान जीवनचक्र दिखा सकते हैं।',
    demoCreateGo: 'बनाएँ + सूचित करें', demoFTitle: 'शीर्षक', demoFHazard: 'खतरा',
    demoFSeverity: 'गंभीरता', demoFPre: 'प्री-अलर्ट (मिनट)', demoFStart: 'सक्रिय (मिनट)',
    demoFEnd: 'समाप्त (मिनट)', demoMin: 'मिनट', demoFInstruction: 'आधिकारिक निर्देश',
    stUpcoming: 'आगामी', stPreAlert: 'प्री-अलर्ट', stActive: 'सक्रिय', stUpdated: 'अपडेटेड',
    stExtended: 'विस्तारित', stEnded: 'समाप्त', stCancelled: 'रद्द',
    actPre: 'प्री-अलर्ट', actActivate: 'सक्रिय करें', actUpdate: 'अपडेट', actExtend: 'बढ़ाएँ',
    actEnd: 'समाप्त करें', actCancel: 'रद्द करें',
    covTitle: 'अलर्ट कवरेज — प्रशासन दृष्टि', covNote: 'चेतावनी प्रभावित जनसंख्या तक कितनी पहुँची: डिलीवरी, खोलना, प्राप्ति, ऑफ़लाइन और P2P संख्या। संचार दृश्यता — सुरक्षा गिनती नहीं।',
    covPick: 'अलर्ट', covEmpty: 'अभी कोई डिलीवरी डेटा नहीं। पहले परिदृश्य चलाएँ, फिर ऑडियंस भरें।',
    covNeedsDemo: 'कवरेज ट्रैकिंग डेमो अलर्ट पाइपलाइन से चलती है, इसलिए डैशबोर्ड DEMO मोड में उपलब्ध है। देखने के लिए ऊपर बैनर से मोड बदलें।',
    covRealTitle: 'असली डिवाइस', covSimTitle: 'सिम्युलेटेड ऑडियंस',
    covSimLabel: 'अनुकरण', covReached: 'पहुँचे', covDelivered: 'पहुँच गया',
    covOpened: 'खोला', covAck: 'प्राप्ति दर्ज', covP2P: 'P2P रिले',
    covPending: 'लंबित', covOffline: 'ऑफ़लाइन', covUnreach: 'अप्राप्य',
    back: 'वापस', demoHistory: 'डेमो इतिहास', demoHistoryToggle: 'इतिहास',
    covAllDistricts: 'सभी जिले', covTotalSent: 'कुल भेजे गए',
    covDeliveryRate: 'डिलीवरी दर', covAckRate: 'प्राप्ति दर्ज दर',
    covZoneBreakdown: 'क्षेत्रवार विवरण',
  },
  te: {
    navNotifications: 'నోటిఫికేషన్లు', navAdvisor: 'సలహాదారు', navAdmin: 'డెమో & అధికారులు',
    ntfTitle: 'నోటిఫికేషన్లు', ntfSub: 'SAARTHI పంపినవన్నీ — అలర్ట్‌లు, అప్‌డేట్‌లు, ముగింపు — యాప్ మూసివేసినప్పుడు కూడా.',
    ntfToday: 'ఈరోజు',
    advEyebrow: 'సలహా',
    ntfEmpty: 'ఇంకా నోటిఫికేషన్లు లేవు. మీ జిల్లా అలర్ట్ వస్తే దాని పూర్తి చక్రం ఇక్కడ కనిపిస్తుంది.',
    ntfLoadFailed: 'నోటిఫికేషన్లు లోడ్ కాలేదు (ఆఫ్‌లైన్?). పాత అలర్ట్‌లు Alerts పేజీలో ఉన్నాయి.',
    ntfMarkRead: 'చదివినట్టు గుర్తించు', ntfReadAll: 'అన్నీ చదివినట్టు గుర్తించు',
    ntfAck: 'స్వీకారం నమోదు', ntfAcked: 'స్వీకారం నమోదైంది', ntfAckTitle: 'అలర్ట్ అందిందని నిర్ధారించండి',
    ntfViewAlerts: 'అలర్ట్‌లు చూడండి',
    advTitle: 'సలహాదారు', advSub: 'ఒకే వాతావరణం, మీకు సరైన సలహా. మీ పాత్రను ఎంచుకోండి; సలహా మారుతుంది.',
    advNote: 'అధికారిక అలర్ట్ తీర్పు మీద ఆధారపడినది — AI ఊహ కాదు. వృత్తి సలహా సాధారణ మార్గదర్శకం, అధికారిక ఆదేశం కాదు.',
    utYou: 'మీరు', utGeneral: 'సామాన్య పౌరుడు', utFarmer: 'రైతు', utDriver: 'డ్రైవర్',
    utFisherman: 'మత్స్యకారుడు', utCommuter: 'ప్రయాణికుడు', utEmployee: 'ఉద్యోగి',
    utOutdoor: 'బహిరంగ కార్మికుడు', utStudent: 'విద్యార్థి', utResearch: 'పరిశోధకుడు', utDisaster: 'విపత్తు అధికారి',
    demoTitle: 'డెమో నియంత్రణ ప్యానెల్', demoSub: 'అలర్ట్‌లు సృష్టించండి, పూర్తి జీవితచక్రం చూపించండి, అధికార డాష్‌బోర్డు నింపండి. ప్రతి బటన్ నిజమైన పైప్‌లైన్ నడుపుతుంది.',
    demoNeedDemoMode: 'డెమో ప్యానెల్ సిమ్యులేటెడ్ అలర్ట్‌లు కలిగిస్తుంది, కాబట్టి ఇది DEMO మోడ్‌లో మాత్రమే పనిచేస్తుంది — నకిలీ అలర్ట్‌లు లైవ్ డేటాలో కలవకుండా ఉంటాయి. మీ సర్వర్ ప్రస్తుతం లైవ్/హైబ్రిడ్ మోడ్‌లో ఉంది.',
    demoSwitchBtn: 'DEMO మోడ్‌కు మారండి',
    demoScenarios: 'వన్-ట్యాప్ దృశ్యాలు (~3 నిమిషాల్లో ప్రీ-అలర్ట్ → యాక్టివ్ → ముగింపు)',
    demoScenarioHint: 'దృశ్య అలర్ట్‌లు తామే నడుస్తాయి: ప్రీ-అలర్ట్ సెకన్లలో, యాక్టివ్ ~40 సెకన్లలో, ముగింపు నోటిఫికేషన్ చక్రాన్ని పూర్తి చేస్తుంది — ప్రెజెంటేషన్‌లో చేతులు ఖాళీ.',
    demoScenarioLaunched: 'దృశ్యం ప్రారంభం', demoActiveTitle: 'అమలులో ఉన్న అలర్ట్‌లు',
    demoActiveSub: 'ఏ అలర్ట్‌నైనా జీవితచక్రంలో నడిపించండి — ప్రతి చర్య వెంటనే తెలియజేస్తుంది.',
    demoEmpty: 'ఇంకా డెమో అలర్ట్‌లు లేవు. క్రింద దృశ్యం ఎంచుకోండి లేదా సృష్టించండి.',
    demoCreated: 'అలర్ట్ సృష్టించబడింది — నోటిఫికేషన్ పంపారు', demoResent: 'నోటిఫికేషన్ పంపారు',
    demoRelay: 'P2P రిలే', demoRelayed: 'P2P రిలే చేరింది', demoSeed: 'ప్రేక్షకులు నింపు',
    demoSeeded: 'సిమ్యులేటెడ్ ప్రేక్షకులు నింపారు', demoReset: 'డెమో రీసెట్', demoResetDone: 'డెమో రీసెట్',
    demoNotifyHint: 'ఈ స్థితికి నోటిఫికేషన్ మళ్లీ పంపండి', demoResend: 'తెలియజేయి',
    demoCreateTitle: 'అలర్ట్ సృష్టించండి', demoCreateSub: 'సమయం ఇప్పటి నుండి నిమిషాల్లో — ప్రెజెంటేషన్‌లో జీవితచక్రం చూపవచ్చు.',
    demoCreateGo: 'సృష్టించు + తెలియజేయి', demoFTitle: 'శీర్షిక', demoFHazard: 'ప్రమాదం',
    demoFSeverity: 'తీవ్రత', demoFPre: 'ప్రీ-అలర్ట్ (నిమి)', demoFStart: 'యాక్టివ్ (నిమి)',
    demoFEnd: 'ముగుస్తుంది (నిమి)', demoMin: 'నిమి', demoFInstruction: 'అధికారిక సూచన',
    stUpcoming: 'రాబోతున్న', stPreAlert: 'ప్రీ-అలర్ట్', stActive: 'యాక్టివ్', stUpdated: 'అప్‌డేట్',
    stExtended: 'పొడిగించారు', stEnded: 'ముగిసింది', stCancelled: 'రద్దు',
    actPre: 'ప్రీ-అలర్ట్', actActivate: 'యాక్టివ్', actUpdate: 'అప్‌డేట్', actExtend: 'పొడిగించు',
    actEnd: 'ముగించు', actCancel: 'రద్దు',
    covTitle: 'అలర్ట్ కవరేజ్ — అధికార దృష్టి', covNote: 'హెచ్చరిక ప్రభావిత ప్రజలకు ఎంత చేరింది: డెలివరీ, తెరవడం, స్వీకారం, ఆఫ్‌లైన్, P2P సంఖ్యలు. కమ్యూనికేషన్ దృశ్యత — భద్రతా లెక్క కాదు.',
    covPick: 'అలర్ట్', covEmpty: 'ఇంకా డెలివరీ డేటా లేదు. ముందుగా దృశ్యం నడపండి, తర్వాత ప్రేక్షకులు నింపండి.',
    covNeedsDemo: 'కవరేజ్ ట్రాకింగ్ డెమో అలర్ట్ పైప్‌లైన్ నుండి వస్తుంది, కాబట్టి డాష్‌బోర్డు DEMO మోడ్‌లో మాత్రమే. చూడటానికి పైన బ్యానర్‌లో మోడ్ మార్చండి.',
    covRealTitle: 'నిజమైన డివైస్‌లు', covSimTitle: 'సిమ్యులేటెడ్ ప్రేక్షకులు',
    covSimLabel: 'అనుకరణ', covReached: 'చేరారు', covDelivered: 'చేరింది',
    covOpened: 'తెరిచారు', covAck: 'స్వీకారం', covP2P: 'P2P రిలే',
    covPending: 'పెండింగ్', covOffline: 'ఆఫ్‌లైన్', covUnreach: 'చేరలేదు',
    back: 'వెనుకకు', demoHistory: 'డెమో చరిత్ర', demoHistoryToggle: 'చరిత్ర',
    covAllDistricts: 'అన్ని జిల్లాలు', covTotalSent: 'మొత్తం పంపినవి',
    covDeliveryRate: 'డెలివరీ రేటు', covAckRate: 'ధృవీకరణ రేటు',
    covZoneBreakdown: 'జోన్ వారీ వివరాలు',
  },
};
