// SIGNAL BOARD strings: the harbour-dispatch redesign's chrome and new
// compositions. EN/HI/TE with exact key parity. None of these keys exist in
// i18n.js — area files must not redefine base keys (see tests/modes.test.mjs).
export default {
  en: {
    // --- rail / mobile chrome ------------------------------------------------
    close: 'Close',
    navAdvisor: 'Who is asking',
    navAdmin: 'Demo control panel',
    navLabel: 'Sections',
    langLabel: 'Language',
    skipToContent: 'Skip to main content',
    navDetails: 'Alert details',
    navSources: 'Sources',
    sbSih: 'SIH 2026',
    sbTakeTour: 'Take the tour',
    sbStep: 'Step {n} of {m}',
    // --- status banners -------------------------------------------------------
    sbBannerDemo: 'Sample data — not a real warning',
    sbBannerOffline: 'Offline — messages will queue',
    // --- home ----------------------------------------------------------------
    sbDistrictKicker: 'Your district',
    sbListenVerdict: 'Listen',
    sbBulletins: "Today's bulletins",
    sbTileReports: 'Field reports',
    sbScnThunder: 'Thunderstorm',
    sbScnHeat: 'Heat wave',
    sbScnRain: 'Heavy rain',
    sbScnCyclone: 'Cyclone',
    sbBulletinListen: 'Listen to this bulletin',
    // --- ask -----------------------------------------------------------------
    sbFactsOnly: 'Facts only — I answer from official bulletins, never from memory.',
    sbAskStop: 'Stop',
    // --- notifications ---------------------------------------------------------
    sbTapToAck: 'Tap to acknowledge',
    sbStampNew: 'New',
    sbStampRead: 'Read',
    sbSending: 'Sending…',
    // --- advisory --------------------------------------------------------------
    sbListenAdvice: 'Listen to this advice',
    sbDecisionHead: 'Decision support — not an official instruction',
    sbDisclaimer: 'This guidance is general advice for your role. Always follow official IMD and government warnings — they override anything here.',
    // --- alerts / P2P -----------------------------------------------------------
    sbMaydayKicker: 'Emergency messages',
    sbSimStamp: 'Simulated — for demo only',
    sbP2pRelayIdle: 'P2P relay console (idle)',
    sbSosLabel: 'Emergency',
    emgSosArmed: 'Armed — tap again to send',
    emgArmHint: 'First tap arms, second tap fires. Nothing sends by accident.',
    // --- admin ------------------------------------------------------------------
    sbBackstage: 'Backstage — not a citizen setting.',
    sbModeIs: 'Current mode: {m}',
    sbFiring: 'Firing…',
    // --- trust / sources --------------------------------------------------------
    sbHonesty: 'Honest status — a mock is never labelled live.',
  },
  hi: {
    close: 'बंद करें',
    navAdvisor: 'कौन पूछ रहा है',
    navAdmin: 'डेमो कंट्रोल पैनल',
    navLabel: 'अनुभाग',
    langLabel: 'भाषा',
    skipToContent: 'मुख्य सामग्री पर जाएँ',
    navDetails: 'अलर्ट विवरण',
    navSources: 'स्रोत',
    sbSih: 'SIH 2026',
    sbTakeTour: 'टूर शुरू करें',
    sbStep: 'चरण {n} / {m}',
    sbBannerDemo: 'नमूना डेटा — असली चेतावनी नहीं',
    sbBannerOffline: 'ऑफ़लाइन — संदेश कतार में लगेंगे',
    sbDistrictKicker: 'आपका जिला',
    sbListenVerdict: 'सुनें',
    sbBulletins: 'आज के बुलेटिन',
    sbTileReports: 'क्षेत्रीय रिपोर्ट',
    sbScnThunder: 'गरज के साथ आँधी',
    sbScnHeat: 'लू',
    sbScnRain: 'भारी बारिश',
    sbScnCyclone: 'चक्रवात',
    sbBulletinListen: 'यह बुलेटिन सुनें',
    sbFactsOnly: 'केवल तथ्य — मैं सरकारी बुलेटिनों से जवाब देता हूँ, अपनी याद से नहीं।',
    sbAskStop: 'रोकें',
    sbTapToAck: 'प्राप्ति दर्ज करने के लिए दबाएँ',
    sbStampNew: 'नया',
    sbStampRead: 'पढ़ा हुआ',
    sbSending: 'भेजा जा रहा…',
    sbListenAdvice: 'यह सलाह सुनें',
    sbDecisionHead: 'निर्णय सहायता — सरकारी निर्देश नहीं',
    sbDisclaimer: 'यह सलाह आपकी भूमिका के लिए सामान्य मार्गदर्शन है। हमेशा आधिकारिक IMD और सरकारी चेतावनियों का पालन करें — वे इस सलाह से ऊपर हैं।',
    sbMaydayKicker: 'आपातकालीन संदेश',
    sbSimStamp: 'सिम्युलेटेड — केवल डेमो के लिए',
    sbP2pRelayIdle: 'P2P रिले कंसोल (निष्क्रिय)',
    sbSosLabel: 'आपातकाल',
    emgSosArmed: 'तैयार — भेजने के लिए फिर दबाएँ',
    emgArmHint: 'पहली बार दबाने से तैयार, दूसरी बार से भेजा जाता है। गलती से कुछ नहीं भेजा जाता।',
    sbBackstage: 'बैकस्टेज — नागरिकों की सेटिंग नहीं।',
    sbModeIs: 'वर्तमान मोड: {m}',
    sbFiring: 'चालू हो रहा…',
    sbHonesty: 'ईमानदार स्थिति — कोई मॉक कभी लाइव नहीं दिखाया जाता।',
  },
  te: {
    close: 'మూసివేయండి',
    navAdvisor: 'అడుగుతున్నది ఎవరు',
    navAdmin: 'డెమో నియంత్రణ ప్యానెల్',
    navLabel: 'విభాగాలు',
    langLabel: 'భాష',
    skipToContent: 'ప్రధాన కంటెంట్‌కు వెళ్లండి',
    navDetails: 'హెచ్చరిక వివరాలు',
    navSources: 'మూలాలు',
    sbSih: 'SIH 2026',
    sbTakeTour: 'టూర్ చూడండి',
    sbStep: 'దశ {n} / {m}',
    sbBannerDemo: 'నమూనా డేటా — నిజమైన హెచ్చరిక కాదు',
    sbBannerOffline: 'ఆఫ్‌లైన్ — సందేశాలు క్యూలో ఉంటాయి',
    sbDistrictKicker: 'మీ జిల్లా',
    sbListenVerdict: 'వినండి',
    sbBulletins: 'ఈరోజు బులెటిన్‌లు',
    sbTileReports: 'క్షేత్ర నివేదికలు',
    sbScnThunder: 'ఉరుములతో కూడిన తుఫాను',
    sbScnHeat: 'వేడి గాలులు',
    sbScnRain: 'భారీ వర్షం',
    sbScnCyclone: 'తుఫాను',
    sbBulletinListen: 'ఈ బులెటిన్ వినండి',
    sbFactsOnly: 'వాస్తవాలు మాత్రమే — నేను అధికారిక బులెటిన్‌ల నుండి మాత్రమే సమాధానం ఇస్తాను, జ్ఞాపకం నుండి కాదు.',
    sbAskStop: 'ఆపండి',
    sbTapToAck: 'స్వీకారం కోసం నొక్కండి',
    sbStampNew: 'కొత్త',
    sbStampRead: 'చదివిన',
    sbSending: 'పంపబడుతోంది…',
    sbListenAdvice: 'ఈ సలహా వినండి',
    sbDecisionHead: 'నిర్ణయ సహాయం — అధికారిక సూచన కాదు',
    sbDisclaimer: 'ఈ సలహా మీ పాత్ర కోసం సాధారణ మార్గదర్శనం. ఎల్లప్పుడూ అధికారిక IMD మరియు ప్రభుత్వ హెచ్చరికలను పాటించండి — అవి ఈ సలహా కంటే ముఖ్యమైనవి.',
    sbMaydayKicker: 'అత్యవసర సందేశాలు',
    sbSimStamp: 'సిమ్యులేటెడ్ — డెమో కోసం మాత్రమే',
    sbP2pRelayIdle: 'P2P రిలే కన్సోల్ (నిష్క్రియ)',
    sbSosLabel: 'అత్యవసర',
    emgSosArmed: 'సిద్ధం — పంపడానికి మళ్లీ నొక్కండి',
    emgArmHint: 'మొదటి నొక్కుడుతో సిద్ధం, రెండో నొక్కుడుతో పంపుతుంది. పొరపాటున ఏదీ పంపబడదు.',
    sbBackstage: 'బ్యాక్‌స్టేజ్ — పౌరుల సెట్టింగ్ కాదు.',
    sbModeIs: 'ప్రస్తుత మోడ్: {m}',
    sbFiring: 'మొదలవుతోంది…',
    sbHonesty: 'నిజాయితీగల స్థితి — ఏ మాక్‌ను లైవ్ అని చూపించము.',
  },
};
