// Top bar, location sheet, notifications panel.
export default {
  en: {
    changeLocation: 'Change location',
    searchPh: 'Search city or district…',
    useGps: 'Use my location',
    locating: 'Locating…',
    locError: "Couldn't get your location. Search instead.",
    noMatch: 'No match — try another spelling.',
    notifications: 'Notifications',
    noNotifications: 'Nothing yet. Official alerts will appear here.',
    markAllRead: 'Mark all read',
    openAlerts: 'Open alerts',
  },
  hi: {
    changeLocation: 'स्थान बदलें',
    searchPh: 'शहर या ज़िला खोजें…',
    useGps: 'मेरी लोकेशन इस्तेमाल करें',
    locating: 'लोकेशन मिल रही है…',
    locError: 'लोकेशन नहीं मिल सकी। खोजकर देखें।',
    noMatch: 'कोई मेल नहीं — दूसरी स्पेलिंग आज़माएँ।',
    notifications: 'सूचनाएँ',
    noNotifications: 'अभी कुछ नहीं। आधिकारिक अलर्ट यहाँ दिखेंगे।',
    markAllRead: 'सभी को पढ़ा मानें',
    openAlerts: 'अलर्ट खोलें',
  },
  te: {
    changeLocation: 'స్థానం మార్చండి',
    searchPh: 'నగరం లేదా జిల్లా వెతకండి…',
    useGps: 'నా స్థానాన్ని వాడండి',
    locating: 'స్థానం తెలుసుకుంటోంది…',
    locError: 'స్థానం తెలియలేదు. వెతికి చూడండి.',
    noMatch: 'సరిపోలలేదు — మరో స్పెల్లింగ్ ప్రయత్నించండి.',
    notifications: 'నోటిఫికేషన్లు',
    noNotifications: 'ఇంకా ఏమీ లేదు. అధికారిక హెచ్చరికలు ఇక్కడ కనిపిస్తాయి.',
    markAllRead: 'అన్నీ చదివినట్లు గుర్తించు',
    openAlerts: 'హెచ్చరికలు తెరవండి',
  },
};
