// Trust & sources view.
export default {
  en: {
    trustViewTitle: 'Trust & sources',
    trustViewSub: 'Every fact carries its source. SAARTHI refuses to guess when sources are unavailable.',
    recheck: 'Re-check',
    liveOf: '{n} live · {m} sources',
    gWeather: 'Weather',
    gAlerts: 'Alerts',
    gVoice: 'Voice',
    gMore: 'More',
    why: 'Why?',
    src_imd: 'IMD',
    src_open_meteo: 'Open-Meteo',
    src_owm: 'OpenWeatherMap',
    src_cap: 'SACHET CAP',
    src_govdata: 'data.gov.in',
    src_stt: 'Speech-to-text',
    src_tts: 'Text-to-speech',
    src_gis: 'Location',
    noDetail: 'No detail reported.',
  },
  hi: {
    trustViewTitle: 'भरोसा और स्रोत',
    trustViewSub: 'हर तथ्य के साथ उसका स्रोत। स्रोत उपलब्ध न हों तो SAARTHI अंदाज़ा नहीं लगाता।',
    recheck: 'फिर से जाँचें',
    liveOf: '{n} लाइव · {m} स्रोत',
    gWeather: 'मौसम',
    gAlerts: 'अलर्ट',
    gVoice: 'आवाज़',
    gMore: 'अधिक',
    why: 'क्यों?',
    src_imd: 'IMD',
    src_open_meteo: 'Open-Meteo',
    src_owm: 'OpenWeatherMap',
    src_cap: 'SACHET CAP',
    src_govdata: 'data.gov.in',
    src_stt: 'वाक्-पहचान',
    src_tts: 'वाक्-संश्लेषण',
    src_gis: 'लोकेशन',
    noDetail: 'कोई विवरण नहीं।',
  },
  te: {
    trustViewTitle: 'నమ్మకం & మూలాలు',
    trustViewSub: 'ప్రతి వాస్తవానికి దాని మూలం ఉంటుంది. మూలాలు అందుబాటులో లేనప్పుడు SAARTHI ఊహించదు.',
    recheck: 'మళ్లీ తనిఖీ చేయండి',
    liveOf: '{n} లైవ్ · {m} మూలాలు',
    gWeather: 'వాతావరణం',
    gAlerts: 'హెచ్చరికలు',
    gVoice: 'వాయిస్',
    gMore: 'మరిన్ని',
    why: 'ఎందుకు?',
    src_imd: 'IMD',
    src_open_meteo: 'Open-Meteo',
    src_owm: 'OpenWeatherMap',
    src_cap: 'SACHET CAP',
    src_govdata: 'data.gov.in',
    src_stt: 'వాక్ గుర్తింపు',
    src_tts: 'వాక్ సంశ్లేషణ',
    src_gis: 'స్థానం',
    noDetail: 'వివరాలు లేవు.',
  },
};
