// VoiceMode strings: the hands-free voice loop overlay (Workstream D, 2026-09-23).
//
// One overlay, three status words (Listening / Thinking / Speaking) plus the
// honest states: couldn't-hear (never auto-loops), offline (no fake answers),
// sound-off (answers as text, no auto-loop). Entry button label lives here
// too so HomeChat needs no chrome-string changes.
export default {
  en: {
    vmEntry: 'Voice mode',
    vmTitle: 'Hands-free voice',
    vmListening: 'Listening',
    vmThinking: 'Thinking',
    vmSpeaking: 'Speaking',
    vmTapToStart: 'Tap to start voice mode',
    vmTapToRetry: 'Tap to try again',
    vmContinue: 'Tap to continue',
    vmStop: 'Stop',
    vmClose: 'Close',
    vmNoHear: "I couldn't hear you. Tap to try again.",
    vmError: 'Something went wrong with voice. Tap to try again.',
    vmOffline: 'Voice mode needs the network to fetch answers. It can listen, but it cannot answer offline — nothing fake here.',
    vmSoundOff: 'Sound is off — the answer shows here as text. Turn sound on for the full hands-free loop.',
    vmHint: 'Ask in your own words. Tap Stop any time to end.',
    vmAnswerLabel: 'Answer',
  },
  hi: {
    vmEntry: 'वॉइस मोड',
    vmTitle: 'हैंड्स-फ़्री वॉइस',
    vmListening: 'सुन रहा है',
    vmThinking: 'सोच रहा है',
    vmSpeaking: 'बोल रहा है',
    vmTapToStart: 'वॉइस मोड शुरू करने के लिए टैप करें',
    vmTapToRetry: 'फिर कोशिश करने के लिए टैप करें',
    vmContinue: 'जारी रखने के लिए टैप करें',
    vmStop: 'रोकें',
    vmClose: 'बंद करें',
    vmNoHear: 'मैं आपको सुन नहीं पाया। फिर कोशिश करने के लिए टैप करें।',
    vmError: 'आवाज़ में कोई दिक्कत आई। फिर कोशिश करने के लिए टैप करें।',
    vmOffline: 'जवाब लाने के लिए वॉइस मोड को नेटवर्क चाहिए। सुन तो सकता है, पर ऑफ़लाइन जवाब नहीं दे सकता — यहाँ कुछ भी गढ़ा नहीं जाएगा।',
    vmSoundOff: 'ध्वनि बंद है — जवाब यहाँ टेक्स्ट में दिखेगा। पूरे हैंड्स-फ़्री के लिए ध्वनि चालू करें।',
    vmHint: 'अपने शब्दों में पूछें। रोकने के लिए कभी भी रोकें दबाएँ।',
    vmAnswerLabel: 'उत्तर',
  },
  te: {
    vmEntry: 'వాయిస్ మోడ్',
    vmTitle: 'హ్యాండ్స్-ఫ్రీ వాయిస్',
    vmListening: 'వింటున్నాను',
    vmThinking: 'ఆలోచిస్తున్నాను',
    vmSpeaking: 'మాట్లాడుతున్నాను',
    vmTapToStart: 'వాయిస్ మోడ్ ప్రారంభించడానికి నొక్కండి',
    vmTapToRetry: 'మళ్లీ ప్రయత్నించడానికి నొక్కండి',
    vmContinue: 'కొనసాగడానికి నొక్కండి',
    vmStop: 'ఆపండి',
    vmClose: 'మూసివేయండి',
    vmNoHear: 'మిమ్మల్ని వినలేకపోయాను. మళ్లీ ప్రయత్నించడానికి నొక్కండి.',
    vmError: 'వాయిస్‌లో ఏదో తప్పు జరిగింది. మళ్లీ ప్రయత్నించడానికి నొక్కండి.',
    vmOffline: 'సమాధానాలు తేవడానికి వాయిస్ మోడ్‌కు నెట్‌వర్క్ కావాలి. వినగలను, కానీ ఆఫ్‌లైన్‌లో సమాధానం ఇవ్వలేను — ఇక్కడ ఏదీ కల్పించను.',
    vmSoundOff: 'ధ్వని ఆఫ్ — సమాధానం ఇక్కడ టెక్స్ట్‌గా కనిపిస్తుంది. పూర్తి హ్యాండ్స్-ఫ్రీ కోసం ధ్వనిని ఆన్ చేయండి.',
    vmHint: 'మీ మాటల్లో అడగండి. ఎప్పుడైనా ఆపడానికి ఆపండి నొక్కండి.',
    vmAnswerLabel: 'సమాధానం',
  },
};
