"""District gazetteer for Telangana and Andhra Pradesh — names and coordinates.

Why this module exists. The SACHET/CAP feed almost never carries GIS geometry:
across 20 live alerts `polygon` was present zero times and `circle` zero times.
Its `areaDesc` is usually a weather code ("MOD TSRA"), an area code ("A1") or a
count ("23 districts of Telangana"), while `event` and `description` are empty.
The districts that actually matter are named in the free-text `headline`:

    "...thunderstorm over Kamareddy, Medak, Medchal Malkajgiri, Ranga Reddy,
     Sangareddy, Siddipet, Yadadri Bhuvanagiri..."

Matching only `areaDesc` therefore reported zero relevant alerts for a user in
Hyderabad even though an official alert named Hyderabad among its districts —
the alert existed, named the user's district, and was dropped. That is the bug
this data fixes.

Two facts have to agree, so both live here:
  1. what a district is called — the alias table ("Rangareddy" == "Ranga Reddy"), and
  2. which of those names appear in a block of text.
The location resolver, the alert matcher and the UI all read from this module, so
they cannot drift apart.

The data file is generated by `_gen_districts.py` at the repo root. Each row
records `coord_source`: "gadm" is a real area-weighted centroid of the district
polygon, "hq" is the headquarters town, used for the districts created after that
dataset's vintage (Telangana 2016, Andhra 2022) and which therefore have no
polygon in it. Alert matching is NAME based, so coordinate precision never
decides *whether* an alert is shown — only which district a bare GPS fix lands in.
"""
from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

_DATA_PATH = Path(__file__).resolve().parent.parent / "data" / "districts_telangana_andhra.json"

_ALPHANUM = re.compile(r"[^a-z0-9]+")


def norm_name(value: Any) -> str:
    """Lowercase and squash everything but a-z0-9, so 'Ranga Reddy' == 'ranga-reddy'.

    This is the one name normalizer for the whole system. The resolver and the
    alert matcher must agree on what counts as the same place, or a user in
    "Rangareddy" silently misses an alert addressed to "Ranga Reddy".
    """
    return _ALPHANUM.sub(" ", str(value or "").lower()).strip()


def _read() -> list[dict[str, Any]]:
    """Load the generated gazetteer. Never raises: alerting must survive a
    missing fixture, and 'no district knowledge' is a safe degradation."""
    try:
        raw = json.loads(_DATA_PATH.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return []
    if not isinstance(raw, list):
        return []
    return [r for r in raw if isinstance(r, dict) and r.get("district")]


DISTRICTS: list[dict[str, Any]] = _read()

_BY_NAME: dict[str, dict[str, Any]] = {d["district"]: d for d in DISTRICTS}

# normalized spelling -> canonical district name. Built with setdefault so that if
# two districts ever claim the same spelling the first one wins deterministically
# rather than depending on dict ordering at call time.
_ALIAS_INDEX: dict[str, str] = {}
_NAMES_BY_DISTRICT: dict[str, set[str]] = {}
for _d in DISTRICTS:
    for _alias in _d.get("aliases") or [_d["district"]]:
        _key = norm_name(_alias)
        if not _key:
            continue
        _ALIAS_INDEX.setdefault(_key, _d["district"])
        _NAMES_BY_DISTRICT.setdefault(norm_name(_d["district"]), set()).add(_key)
    # The canonical name always matches itself, even if the alias list omits it.
    _NAMES_BY_DISTRICT.setdefault(norm_name(_d["district"]), set()).add(norm_name(_d["district"]))


def get(district: str) -> dict[str, Any] | None:
    """The gazetteer row for a district, or None when it is outside our coverage."""
    return _BY_NAME.get(district) or _BY_NAME.get(str(district or "").strip())


def aliases_for(district: str) -> set[str]:
    """Every normalized spelling that means this district.

    Falls back to the district's own name, so a district we do not carry (anywhere
    else in India) still matches itself exactly — the behaviour before this module
    existed, kept so coverage gaps degrade instead of breaking.
    """
    key = norm_name(district)
    if not key:
        return set()
    return set(_NAMES_BY_DISTRICT.get(key) or {key})


def find_in_text(text: str) -> set[str]:
    """Canonical districts named in a block of text.

    Whole-phrase matching only: "Medak" matches, "Medakaranahalli" does not, and
    "East Godavari" does not accidentally match "Godavari". This is what makes it
    safe to read district names out of prose.
    """
    hay = f" {norm_name(text)} "
    if len(hay) <= 2:
        return set()
    return {district for alias, district in _ALIAS_INDEX.items() if f" {alias} " in hay}


def state_of(district: str) -> str:
    row = get(district)
    return str((row or {}).get("state") or "")


def is_coastal(district: str) -> bool | None:
    """True/False for a district we carry, None when we cannot say.

    None is not False: "I do not know" and "inland" are different statements, and
    the answer layer must not turn one into the other.
    """
    row = get(district)
    if row is None:
        return None
    return bool(row.get("coastal"))


def as_gazetteer_entries() -> list[dict[str, Any]]:
    """Rows in `location_service.GAZETTEER` shape, so the resolver can merge them.

    `city` is the district name: these are district centroids, not towns, and
    inventing a town for each would be a guess. `coord_source` rides along so a
    caller can tell surveyed geometry from a headquarters pin.
    """
    return [
        {
            "city": d["district"],
            "district": d["district"],
            "state": d["state"],
            "latitude": d["latitude"],
            "longitude": d["longitude"],
            "coastal": bool(d.get("coastal")),
            "aliases": list(d.get("aliases") or []),
            "coord_source": d.get("coord_source"),
        }
        for d in DISTRICTS
    ]
