apiVersion: v1
kind: Service
metadata:
  name: saarthi-backend
  namespace: saarthi
  labels:
    app.kubernetes.io/name: saarthi-backend
    app.kubernetes.io/part-of: saarthi
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: saarthi-backend
  ports:
    - name: http
      port: 8003
      targetPort: 8003
