// Phone-to-phone SOS over Bluetooth (the Nearby screen, the SOS popup, the
// relay controls in Settings). Plain words: most people will read these in a
// hurry, many of them on a phone with no network.
export default {
  en: {
    navNearby: 'Nearby SOS',
    viewNearbySub: 'Help calls from phones around you. They hop phone to phone by Bluetooth — no internet needed.',
    meshRelayOn: 'Bluetooth relay on',
    meshRelayOff: 'Bluetooth relay off',
    meshPeersNone: 'No phones linked yet. Messages are kept and passed on when someone comes near.',
    meshPeersOne: 'Linked to 1 phone nearby',
    meshPeersMany: 'Linked to {n} phones nearby',
    meshCarried: 'Carrying {n} messages',
    meshTurnOn: 'Turn on relay',
    meshTurnOff: 'Turn off',
    meshBtOff: 'Bluetooth is off',
    meshBtTurnOn: 'Turn on Bluetooth',
    meshNeedPerm: 'Allow Bluetooth so an SOS can travel phone to phone.',
    meshAllow: 'Allow',
    meshSim: 'Browser demo: other open tabs of this site act as nearby phones. The Android app uses real Bluetooth.',
    meshSimTag: 'Demo',
    meshActiveTitle: 'People who need help',
    meshNoSos: 'No SOS near you right now.',
    meshClosedTitle: 'Closed',
    meshSafeTitle: 'Marked safe',
    meshImSafe: "I'm safe",
    meshSafeSent: 'Your "I\'m safe" is on its way to phones nearby.',
    meshYourName: 'Your name (optional)',
    meshGoing: "I'm going",
    meshGoingDone: "You're going",
    meshRescued: 'Rescued',
    meshCancel: 'Cancel my SOS',
    meshDirections: 'Directions',
    meshMine: 'Your SOS',
    meshYou: 'You',
    meshDirect: 'Reached you directly',
    meshVia: 'Via {n} phones',
    meshResponders: '{n} going',
    meshPeople: '{n} people',
    meshStRescued: 'Rescued',
    meshStCancelled: 'Cancelled',
    meshNoPlace: 'No location shared',
    meshNeed_medical: 'Needs medical help',
    meshNeed_trapped: 'Trapped',
    meshNeed_water: 'Needs water or food',
    meshNeed_fire: 'Fire',
    meshNeed_flood: 'Flooding',
    meshNeed_other: 'Needs help',
    meshIncomingTitle: 'SOS nearby',
    meshView: 'See where',
    meshDismiss: 'Later',
    meshSentBt: 'Sent to phones nearby by Bluetooth.',
    meshSentKept: 'No phone in range yet. Your SOS is kept and goes out as soon as one comes near.',
    meshSosCount: '{n} SOS nearby',
    meshSosNone: 'No SOS nearby',
    meshOpenNearby: 'Open',
    meshAlertsTitle: 'Official alerts passed phone to phone',
    meshSettingsTitle: 'Phone-to-phone SOS (Bluetooth)',
    meshSettingsBody: 'Passes SOS messages to and from phones nearby, even with no network.',
    meshServerTitle: 'Server address',
    meshServerBody: 'Where the app gets weather and alerts, e.g. 192.168.1.20:8000. Empty = built-in address.',
    meshServerSave: 'Save',
    meshServerSaved: 'Saved',
    meshLocating: 'Finding your location…',
    meshNameHint: 'Shown with your SOS so helpers know who to look for.',
  },
  hi: {
    navNearby: 'आस-पास SOS',
    viewNearbySub: 'आपके आस-पास के फ़ोन से मदद की पुकार। ये ब्लूटूथ से एक फ़ोन से दूसरे फ़ोन तक जाती हैं — इंटरनेट की ज़रूरत नहीं।',
    meshRelayOn: 'ब्लूटूथ रिले चालू',
    meshRelayOff: 'ब्लूटूथ रिले बंद',
    meshPeersNone: 'अभी कोई फ़ोन जुड़ा नहीं। संदेश रखे जाते हैं और किसी के पास आते ही आगे भेजे जाते हैं।',
    meshPeersOne: 'पास के 1 फ़ोन से जुड़ा',
    meshPeersMany: 'पास के {n} फ़ोन से जुड़ा',
    meshCarried: '{n} संदेश साथ हैं',
    meshTurnOn: 'रिले चालू करें',
    meshTurnOff: 'बंद करें',
    meshBtOff: 'ब्लूटूथ बंद है',
    meshBtTurnOn: 'ब्लूटूथ चालू करें',
    meshNeedPerm: 'ब्लूटूथ की अनुमति दें ताकि SOS एक फ़ोन से दूसरे तक जा सके।',
    meshAllow: 'अनुमति दें',
    meshSim: 'ब्राउज़र डेमो: इस साइट के दूसरे खुले टैब पास के फ़ोन की तरह काम करते हैं। Android ऐप असली ब्लूटूथ इस्तेमाल करता है।',
    meshSimTag: 'डेमो',
    meshActiveTitle: 'जिन्हें मदद चाहिए',
    meshNoSos: 'अभी आपके पास कोई SOS नहीं।',
    meshClosedTitle: 'बंद',
    meshSafeTitle: 'सुरक्षित बताया',
    meshImSafe: 'मैं सुरक्षित हूँ',
    meshSafeSent: 'आपका "मैं सुरक्षित हूँ" पास के फ़ोन तक भेजा जा रहा है।',
    meshYourName: 'आपका नाम (वैकल्पिक)',
    meshGoing: 'मैं आ रहा/रही हूँ',
    meshGoingDone: 'आप जा रहे हैं',
    meshRescued: 'बचा लिया',
    meshCancel: 'मेरा SOS रद्द करें',
    meshDirections: 'रास्ता',
    meshMine: 'आपका SOS',
    meshYou: 'आप',
    meshDirect: 'सीधे आप तक पहुँचा',
    meshVia: '{n} फ़ोन से होकर',
    meshResponders: '{n} आ रहे हैं',
    meshPeople: '{n} लोग',
    meshStRescued: 'बचा लिया',
    meshStCancelled: 'रद्द',
    meshNoPlace: 'जगह नहीं बताई',
    meshNeed_medical: 'डॉक्टर की ज़रूरत',
    meshNeed_trapped: 'फँसे हुए हैं',
    meshNeed_water: 'पानी या खाना चाहिए',
    meshNeed_fire: 'आग',
    meshNeed_flood: 'बाढ़',
    meshNeed_other: 'मदद चाहिए',
    meshIncomingTitle: 'पास में SOS',
    meshView: 'जगह देखें',
    meshDismiss: 'बाद में',
    meshSentBt: 'ब्लूटूथ से पास के फ़ोन तक भेजा गया।',
    meshSentKept: 'अभी कोई फ़ोन पास नहीं। आपका SOS रखा है और किसी फ़ोन के पास आते ही चला जाएगा।',
    meshSosCount: 'पास में {n} SOS',
    meshSosNone: 'पास में कोई SOS नहीं',
    meshOpenNearby: 'खोलें',
    meshAlertsTitle: 'फ़ोन से फ़ोन पहुँची सरकारी चेतावनियाँ',
    meshSettingsTitle: 'फ़ोन से फ़ोन SOS (ब्लूटूथ)',
    meshSettingsBody: 'नेटवर्क न होने पर भी पास के फ़ोन से SOS संदेश लेता और आगे भेजता है।',
    meshServerTitle: 'सर्वर का पता',
    meshServerBody: 'ऐप मौसम और चेतावनी यहाँ से लेता है, जैसे 192.168.1.20:8000। खाली = पहले से तय पता।',
    meshServerSave: 'सहेजें',
    meshServerSaved: 'सहेजा गया',
    meshLocating: 'आपकी जगह ढूँढ रहे हैं…',
    meshNameHint: 'आपके SOS के साथ दिखेगा ताकि मदद करने वाले आपको पहचान सकें।',
  },
  te: {
    navNearby: 'దగ్గరలో SOS',
    viewNearbySub: 'మీ చుట్టూ ఉన్న ఫోన్ల నుండి సహాయం కోసం పిలుపులు. ఇవి బ్లూటూత్‌తో ఒక ఫోన్ నుండి మరో ఫోన్‌కు వెళ్తాయి — ఇంటర్నెట్ అవసరం లేదు.',
    meshRelayOn: 'బ్లూటూత్ రిలే ఆన్',
    meshRelayOff: 'బ్లూటూత్ రిలే ఆఫ్',
    meshPeersNone: 'ఇంకా ఏ ఫోన్ కలవలేదు. సందేశాలు దాచి, ఎవరైనా దగ్గరకు రాగానే పంపుతాం.',
    meshPeersOne: 'దగ్గరలోని 1 ఫోన్‌తో కలిసింది',
    meshPeersMany: 'దగ్గరలోని {n} ఫోన్లతో కలిసింది',
    meshCarried: '{n} సందేశాలు వెంట ఉన్నాయి',
    meshTurnOn: 'రిలే ఆన్ చేయండి',
    meshTurnOff: 'ఆఫ్ చేయండి',
    meshBtOff: 'బ్లూటూత్ ఆఫ్‌లో ఉంది',
    meshBtTurnOn: 'బ్లూటూత్ ఆన్ చేయండి',
    meshNeedPerm: 'SOS ఒక ఫోన్ నుండి మరో ఫోన్‌కు వెళ్లేలా బ్లూటూత్‌కు అనుమతి ఇవ్వండి.',
    meshAllow: 'అనుమతించు',
    meshSim: 'బ్రౌజర్ డెమో: ఈ సైట్ యొక్క ఇతర తెరిచిన ట్యాబ్‌లు దగ్గరి ఫోన్లలా పనిచేస్తాయి. Android యాప్ నిజమైన బ్లూటూత్ వాడుతుంది.',
    meshSimTag: 'డెమో',
    meshActiveTitle: 'సహాయం కావలసినవారు',
    meshNoSos: 'ప్రస్తుతం మీ దగ్గర ఏ SOS లేదు.',
    meshClosedTitle: 'ముగిసినవి',
    meshSafeTitle: 'క్షేమంగా ఉన్నామని చెప్పినవారు',
    meshImSafe: 'నేను క్షేమంగా ఉన్నాను',
    meshSafeSent: 'మీ "క్షేమంగా ఉన్నాను" దగ్గరి ఫోన్లకు వెళ్తోంది.',
    meshYourName: 'మీ పేరు (ఐచ్ఛికం)',
    meshGoing: 'నేను వస్తున్నాను',
    meshGoingDone: 'మీరు వెళ్తున్నారు',
    meshRescued: 'కాపాడాం',
    meshCancel: 'నా SOS రద్దు చేయి',
    meshDirections: 'దారి',
    meshMine: 'మీ SOS',
    meshYou: 'మీరు',
    meshDirect: 'నేరుగా మీకు చేరింది',
    meshVia: '{n} ఫోన్ల ద్వారా',
    meshResponders: '{n} మంది వస్తున్నారు',
    meshPeople: '{n} మంది',
    meshStRescued: 'కాపాడారు',
    meshStCancelled: 'రద్దయింది',
    meshNoPlace: 'స్థలం పంచుకోలేదు',
    meshNeed_medical: 'వైద్య సహాయం కావాలి',
    meshNeed_trapped: 'చిక్కుకున్నారు',
    meshNeed_water: 'నీరు లేదా ఆహారం కావాలి',
    meshNeed_fire: 'మంటలు',
    meshNeed_flood: 'వరద',
    meshNeed_other: 'సహాయం కావాలి',
    meshIncomingTitle: 'దగ్గరలో SOS',
    meshView: 'ఎక్కడో చూడండి',
    meshDismiss: 'తర్వాత',
    meshSentBt: 'బ్లూటూత్‌తో దగ్గరి ఫోన్లకు పంపాం.',
    meshSentKept: 'ఇంకా దగ్గర ఏ ఫోన్ లేదు. మీ SOS దాచాం, ఫోన్ దగ్గరకు రాగానే వెళ్తుంది.',
    meshSosCount: 'దగ్గరలో {n} SOS',
    meshSosNone: 'దగ్గరలో SOS లేదు',
    meshOpenNearby: 'తెరవండి',
    meshAlertsTitle: 'ఫోన్ నుండి ఫోన్‌కు వచ్చిన అధికారిక హెచ్చరికలు',
    meshSettingsTitle: 'ఫోన్ నుండి ఫోన్ SOS (బ్లూటూత్)',
    meshSettingsBody: 'నెట్‌వర్క్ లేకపోయినా దగ్గరి ఫోన్లతో SOS సందేశాలు తీసుకుని పంపుతుంది.',
    meshServerTitle: 'సర్వర్ చిరునామా',
    meshServerBody: 'యాప్ వాతావరణం, హెచ్చరికలు ఇక్కడి నుండి తీసుకుంటుంది, ఉదా. 192.168.1.20:8000. ఖాళీ = ముందే ఉన్న చిరునామా.',
    meshServerSave: 'సేవ్ చేయండి',
    meshServerSaved: 'సేవ్ అయింది',
    meshLocating: 'మీ స్థానం కనుగొంటున్నాం…',
    meshNameHint: 'సహాయం చేసేవారు మిమ్మల్ని గుర్తించేలా మీ SOSతో చూపిస్తాం.',
  },
};
